//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.19 at 08:13:21 PM BRT 
//


package br.com.facilpagar.util.bb.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroConvenio" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroCarteira" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroVariacaoCarteira" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoModalidadeTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dataEmissaoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dataVencimentoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="valorOriginalTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="17"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoDesconto" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dataDescontoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="percentualDescontoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="valorDescontoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="17"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="valorAbatimentoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="17"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="quantidadeDiaProtesto" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoJuroMora" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="percentualJuroMoraTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="valorJuroMoraTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="17"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoMulta" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dataMultaTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="percentualMultaTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="valorMultaTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="17"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoAceiteTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoDescricaoTipoTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indicadorPermissaoRecebimentoParcial" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoNumeroTituloBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoCampoUtilizacaoBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoContaCaucao" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoNumeroTituloCliente" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoMensagemBloquetoOcorrencia" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="220"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoInscricaoPagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroInscricaoPagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;totalDigits value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomePagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoEnderecoPagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroCepPagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomeMunicipioPagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomeBairroPagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="siglaUfPagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoNumeroTelefonePagador" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoInscricaoAvalista" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroInscricaoAvalista" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;totalDigits value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomeAvalistaTitulo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoChaveUsuario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoCanalSolicitacao" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numeroConvenio",
    "numeroCarteira",
    "numeroVariacaoCarteira",
    "codigoModalidadeTitulo",
    "dataEmissaoTitulo",
    "dataVencimentoTitulo",
    "valorOriginalTitulo",
    "codigoTipoDesconto",
    "dataDescontoTitulo",
    "percentualDescontoTitulo",
    "valorDescontoTitulo",
    "valorAbatimentoTitulo",
    "quantidadeDiaProtesto",
    "codigoTipoJuroMora",
    "percentualJuroMoraTitulo",
    "valorJuroMoraTitulo",
    "codigoTipoMulta",
    "dataMultaTitulo",
    "percentualMultaTitulo",
    "valorMultaTitulo",
    "codigoAceiteTitulo",
    "codigoTipoTitulo",
    "textoDescricaoTipoTitulo",
    "indicadorPermissaoRecebimentoParcial",
    "textoNumeroTituloBeneficiario",
    "textoCampoUtilizacaoBeneficiario",
    "codigoTipoContaCaucao",
    "textoNumeroTituloCliente",
    "textoMensagemBloquetoOcorrencia",
    "codigoTipoInscricaoPagador",
    "numeroInscricaoPagador",
    "nomePagador",
    "textoEnderecoPagador",
    "numeroCepPagador",
    "nomeMunicipioPagador",
    "nomeBairroPagador",
    "siglaUfPagador",
    "textoNumeroTelefonePagador",
    "codigoTipoInscricaoAvalista",
    "numeroInscricaoAvalista",
    "nomeAvalistaTitulo",
    "codigoChaveUsuario",
    "codigoTipoCanalSolicitacao"
})
@XmlRootElement(name = "requisicao")
public class Requisicao {

    protected Integer numeroConvenio;
    protected Short numeroCarteira;
    protected Short numeroVariacaoCarteira;
    protected Short codigoModalidadeTitulo;
    protected String dataEmissaoTitulo;
    protected String dataVencimentoTitulo;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal valorOriginalTitulo;
    protected Short codigoTipoDesconto;
    protected String dataDescontoTitulo;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal percentualDescontoTitulo;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal valorDescontoTitulo;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal valorAbatimentoTitulo;
    @XmlElement(defaultValue = "0")
    protected Short quantidadeDiaProtesto;
    protected Short codigoTipoJuroMora;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal percentualJuroMoraTitulo;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal valorJuroMoraTitulo;
    protected Short codigoTipoMulta;
    protected String dataMultaTitulo;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal percentualMultaTitulo;
    @XmlElement(defaultValue = "0.0")
    protected BigDecimal valorMultaTitulo;
    protected String codigoAceiteTitulo;
    @XmlElement(defaultValue = "0")
    protected Short codigoTipoTitulo;
    protected String textoDescricaoTipoTitulo;
    protected String indicadorPermissaoRecebimentoParcial;
    protected String textoNumeroTituloBeneficiario;
    protected String textoCampoUtilizacaoBeneficiario;
    @XmlElement(defaultValue = "0")
    protected Short codigoTipoContaCaucao;
    protected String textoNumeroTituloCliente;
    protected String textoMensagemBloquetoOcorrencia;
    @XmlElement(defaultValue = "0")
    protected Short codigoTipoInscricaoPagador;
    @XmlElement(defaultValue = "0")
    protected Long numeroInscricaoPagador;
    protected String nomePagador;
    protected String textoEnderecoPagador;
    @XmlElement(defaultValue = "0")
    protected Integer numeroCepPagador;
    protected String nomeMunicipioPagador;
    protected String nomeBairroPagador;
    protected String siglaUfPagador;
    protected String textoNumeroTelefonePagador;
    @XmlElement(defaultValue = "0")
    protected Short codigoTipoInscricaoAvalista;
    @XmlElement(defaultValue = "0")
    protected Long numeroInscricaoAvalista;
    protected String nomeAvalistaTitulo;
    protected String codigoChaveUsuario;
    @XmlElement(defaultValue = "5")
    protected Short codigoTipoCanalSolicitacao;

    /**
     * Gets the value of the numeroConvenio property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroConvenio() {
        return numeroConvenio;
    }

    /**
     * Sets the value of the numeroConvenio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroConvenio(Integer value) {
        this.numeroConvenio = value;
    }

    /**
     * Gets the value of the numeroCarteira property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNumeroCarteira() {
        return numeroCarteira;
    }

    /**
     * Sets the value of the numeroCarteira property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNumeroCarteira(Short value) {
        this.numeroCarteira = value;
    }

    /**
     * Gets the value of the numeroVariacaoCarteira property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNumeroVariacaoCarteira() {
        return numeroVariacaoCarteira;
    }

    /**
     * Sets the value of the numeroVariacaoCarteira property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNumeroVariacaoCarteira(Short value) {
        this.numeroVariacaoCarteira = value;
    }

    /**
     * Gets the value of the codigoModalidadeTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoModalidadeTitulo() {
        return codigoModalidadeTitulo;
    }

    /**
     * Sets the value of the codigoModalidadeTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoModalidadeTitulo(Short value) {
        this.codigoModalidadeTitulo = value;
    }

    /**
     * Gets the value of the dataEmissaoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataEmissaoTitulo() {
        return dataEmissaoTitulo;
    }

    /**
     * Sets the value of the dataEmissaoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataEmissaoTitulo(String value) {
        this.dataEmissaoTitulo = value;
    }

    /**
     * Gets the value of the dataVencimentoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataVencimentoTitulo() {
        return dataVencimentoTitulo;
    }

    /**
     * Sets the value of the dataVencimentoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataVencimentoTitulo(String value) {
        this.dataVencimentoTitulo = value;
    }

    /**
     * Gets the value of the valorOriginalTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorOriginalTitulo() {
        return valorOriginalTitulo;
    }

    /**
     * Sets the value of the valorOriginalTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorOriginalTitulo(BigDecimal value) {
        this.valorOriginalTitulo = value;
    }

    /**
     * Gets the value of the codigoTipoDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoDesconto() {
        return codigoTipoDesconto;
    }

    /**
     * Sets the value of the codigoTipoDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoDesconto(Short value) {
        this.codigoTipoDesconto = value;
    }

    /**
     * Gets the value of the dataDescontoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataDescontoTitulo() {
        return dataDescontoTitulo;
    }

    /**
     * Sets the value of the dataDescontoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataDescontoTitulo(String value) {
        this.dataDescontoTitulo = value;
    }

    /**
     * Gets the value of the percentualDescontoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentualDescontoTitulo() {
        return percentualDescontoTitulo;
    }

    /**
     * Sets the value of the percentualDescontoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentualDescontoTitulo(BigDecimal value) {
        this.percentualDescontoTitulo = value;
    }

    /**
     * Gets the value of the valorDescontoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorDescontoTitulo() {
        return valorDescontoTitulo;
    }

    /**
     * Sets the value of the valorDescontoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorDescontoTitulo(BigDecimal value) {
        this.valorDescontoTitulo = value;
    }

    /**
     * Gets the value of the valorAbatimentoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorAbatimentoTitulo() {
        return valorAbatimentoTitulo;
    }

    /**
     * Sets the value of the valorAbatimentoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorAbatimentoTitulo(BigDecimal value) {
        this.valorAbatimentoTitulo = value;
    }

    /**
     * Gets the value of the quantidadeDiaProtesto property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getQuantidadeDiaProtesto() {
        return quantidadeDiaProtesto;
    }

    /**
     * Sets the value of the quantidadeDiaProtesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setQuantidadeDiaProtesto(Short value) {
        this.quantidadeDiaProtesto = value;
    }

    /**
     * Gets the value of the codigoTipoJuroMora property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoJuroMora() {
        return codigoTipoJuroMora;
    }

    /**
     * Sets the value of the codigoTipoJuroMora property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoJuroMora(Short value) {
        this.codigoTipoJuroMora = value;
    }

    /**
     * Gets the value of the percentualJuroMoraTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentualJuroMoraTitulo() {
        return percentualJuroMoraTitulo;
    }

    /**
     * Sets the value of the percentualJuroMoraTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentualJuroMoraTitulo(BigDecimal value) {
        this.percentualJuroMoraTitulo = value;
    }

    /**
     * Gets the value of the valorJuroMoraTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorJuroMoraTitulo() {
        return valorJuroMoraTitulo;
    }

    /**
     * Sets the value of the valorJuroMoraTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorJuroMoraTitulo(BigDecimal value) {
        this.valorJuroMoraTitulo = value;
    }

    /**
     * Gets the value of the codigoTipoMulta property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoMulta() {
        return codigoTipoMulta;
    }

    /**
     * Sets the value of the codigoTipoMulta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoMulta(Short value) {
        this.codigoTipoMulta = value;
    }

    /**
     * Gets the value of the dataMultaTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataMultaTitulo() {
        return dataMultaTitulo;
    }

    /**
     * Sets the value of the dataMultaTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataMultaTitulo(String value) {
        this.dataMultaTitulo = value;
    }

    /**
     * Gets the value of the percentualMultaTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentualMultaTitulo() {
        return percentualMultaTitulo;
    }

    /**
     * Sets the value of the percentualMultaTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentualMultaTitulo(BigDecimal value) {
        this.percentualMultaTitulo = value;
    }

    /**
     * Gets the value of the valorMultaTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorMultaTitulo() {
        return valorMultaTitulo;
    }

    /**
     * Sets the value of the valorMultaTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorMultaTitulo(BigDecimal value) {
        this.valorMultaTitulo = value;
    }

    /**
     * Gets the value of the codigoAceiteTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoAceiteTitulo() {
        return codigoAceiteTitulo;
    }

    /**
     * Sets the value of the codigoAceiteTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoAceiteTitulo(String value) {
        this.codigoAceiteTitulo = value;
    }

    /**
     * Gets the value of the codigoTipoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoTitulo() {
        return codigoTipoTitulo;
    }

    /**
     * Sets the value of the codigoTipoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoTitulo(Short value) {
        this.codigoTipoTitulo = value;
    }

    /**
     * Gets the value of the textoDescricaoTipoTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoDescricaoTipoTitulo() {
        return textoDescricaoTipoTitulo;
    }

    /**
     * Sets the value of the textoDescricaoTipoTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoDescricaoTipoTitulo(String value) {
        this.textoDescricaoTipoTitulo = value;
    }

    /**
     * Gets the value of the indicadorPermissaoRecebimentoParcial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorPermissaoRecebimentoParcial() {
        return indicadorPermissaoRecebimentoParcial;
    }

    /**
     * Sets the value of the indicadorPermissaoRecebimentoParcial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorPermissaoRecebimentoParcial(String value) {
        this.indicadorPermissaoRecebimentoParcial = value;
    }

    /**
     * Gets the value of the textoNumeroTituloBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoNumeroTituloBeneficiario() {
        return textoNumeroTituloBeneficiario;
    }

    /**
     * Sets the value of the textoNumeroTituloBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoNumeroTituloBeneficiario(String value) {
        this.textoNumeroTituloBeneficiario = value;
    }

    /**
     * Gets the value of the textoCampoUtilizacaoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoCampoUtilizacaoBeneficiario() {
        return textoCampoUtilizacaoBeneficiario;
    }

    /**
     * Sets the value of the textoCampoUtilizacaoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoCampoUtilizacaoBeneficiario(String value) {
        this.textoCampoUtilizacaoBeneficiario = value;
    }

    /**
     * Gets the value of the codigoTipoContaCaucao property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoContaCaucao() {
        return codigoTipoContaCaucao;
    }

    /**
     * Sets the value of the codigoTipoContaCaucao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoContaCaucao(Short value) {
        this.codigoTipoContaCaucao = value;
    }

    /**
     * Gets the value of the textoNumeroTituloCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoNumeroTituloCliente() {
        return textoNumeroTituloCliente;
    }

    /**
     * Sets the value of the textoNumeroTituloCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoNumeroTituloCliente(String value) {
        this.textoNumeroTituloCliente = value;
    }

    /**
     * Gets the value of the textoMensagemBloquetoOcorrencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoMensagemBloquetoOcorrencia() {
        return textoMensagemBloquetoOcorrencia;
    }

    /**
     * Sets the value of the textoMensagemBloquetoOcorrencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoMensagemBloquetoOcorrencia(String value) {
        this.textoMensagemBloquetoOcorrencia = value;
    }

    /**
     * Gets the value of the codigoTipoInscricaoPagador property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoInscricaoPagador() {
        return codigoTipoInscricaoPagador;
    }

    /**
     * Sets the value of the codigoTipoInscricaoPagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoInscricaoPagador(Short value) {
        this.codigoTipoInscricaoPagador = value;
    }

    /**
     * Gets the value of the numeroInscricaoPagador property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumeroInscricaoPagador() {
        return numeroInscricaoPagador;
    }

    /**
     * Sets the value of the numeroInscricaoPagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumeroInscricaoPagador(Long value) {
        this.numeroInscricaoPagador = value;
    }

    /**
     * Gets the value of the nomePagador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomePagador() {
        return nomePagador;
    }

    /**
     * Sets the value of the nomePagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomePagador(String value) {
        this.nomePagador = value;
    }

    /**
     * Gets the value of the textoEnderecoPagador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoEnderecoPagador() {
        return textoEnderecoPagador;
    }

    /**
     * Sets the value of the textoEnderecoPagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoEnderecoPagador(String value) {
        this.textoEnderecoPagador = value;
    }

    /**
     * Gets the value of the numeroCepPagador property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroCepPagador() {
        return numeroCepPagador;
    }

    /**
     * Sets the value of the numeroCepPagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroCepPagador(Integer value) {
        this.numeroCepPagador = value;
    }

    /**
     * Gets the value of the nomeMunicipioPagador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeMunicipioPagador() {
        return nomeMunicipioPagador;
    }

    /**
     * Sets the value of the nomeMunicipioPagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeMunicipioPagador(String value) {
        this.nomeMunicipioPagador = value;
    }

    /**
     * Gets the value of the nomeBairroPagador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeBairroPagador() {
        return nomeBairroPagador;
    }

    /**
     * Sets the value of the nomeBairroPagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeBairroPagador(String value) {
        this.nomeBairroPagador = value;
    }

    /**
     * Gets the value of the siglaUfPagador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaUfPagador() {
        return siglaUfPagador;
    }

    /**
     * Sets the value of the siglaUfPagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaUfPagador(String value) {
        this.siglaUfPagador = value;
    }

    /**
     * Gets the value of the textoNumeroTelefonePagador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoNumeroTelefonePagador() {
        return textoNumeroTelefonePagador;
    }

    /**
     * Sets the value of the textoNumeroTelefonePagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoNumeroTelefonePagador(String value) {
        this.textoNumeroTelefonePagador = value;
    }

    /**
     * Gets the value of the codigoTipoInscricaoAvalista property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoInscricaoAvalista() {
        return codigoTipoInscricaoAvalista;
    }

    /**
     * Sets the value of the codigoTipoInscricaoAvalista property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoInscricaoAvalista(Short value) {
        this.codigoTipoInscricaoAvalista = value;
    }

    /**
     * Gets the value of the numeroInscricaoAvalista property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumeroInscricaoAvalista() {
        return numeroInscricaoAvalista;
    }

    /**
     * Sets the value of the numeroInscricaoAvalista property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumeroInscricaoAvalista(Long value) {
        this.numeroInscricaoAvalista = value;
    }

    /**
     * Gets the value of the nomeAvalistaTitulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeAvalistaTitulo() {
        return nomeAvalistaTitulo;
    }

    /**
     * Sets the value of the nomeAvalistaTitulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeAvalistaTitulo(String value) {
        this.nomeAvalistaTitulo = value;
    }

    /**
     * Gets the value of the codigoChaveUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoChaveUsuario() {
        return codigoChaveUsuario;
    }

    /**
     * Sets the value of the codigoChaveUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoChaveUsuario(String value) {
        this.codigoChaveUsuario = value;
    }

    /**
     * Gets the value of the codigoTipoCanalSolicitacao property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoCanalSolicitacao() {
        return codigoTipoCanalSolicitacao;
    }

    /**
     * Sets the value of the codigoTipoCanalSolicitacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoCanalSolicitacao(Short value) {
        this.codigoTipoCanalSolicitacao = value;
    }

}
