
package br.com.pagcontascarne.webservices.bancoDoBrasil.homologacao.com.example.xmlns._1466775928160;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistroCobrancaService.serviceagent", targetNamespace = "http://xmlns.example.com/1466775928160", wsdlLocation = "https://cobranca.homologa.bb.com.br:7101/Processos/Ws/RegistroCobrancaService.serviceagent?wsdl")
public class RegistroCobrancaServiceServiceagent
    extends Service
{

    private final static URL REGISTROCOBRANCASERVICESERVICEAGENT_WSDL_LOCATION;
    private final static WebServiceException REGISTROCOBRANCASERVICESERVICEAGENT_EXCEPTION;
    private final static QName REGISTROCOBRANCASERVICESERVICEAGENT_QNAME = new QName("http://xmlns.example.com/1466775928160", "RegistroCobrancaService.serviceagent");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cobranca.homologa.bb.com.br:7101/Processos/Ws/RegistroCobrancaService.serviceagent?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTROCOBRANCASERVICESERVICEAGENT_WSDL_LOCATION = url;
        REGISTROCOBRANCASERVICESERVICEAGENT_EXCEPTION = e;
    }

    public RegistroCobrancaServiceServiceagent() {
        super(__getWsdlLocation(), REGISTROCOBRANCASERVICESERVICEAGENT_QNAME);
    }

    public RegistroCobrancaServiceServiceagent(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTROCOBRANCASERVICESERVICEAGENT_QNAME, features);
    }

    public RegistroCobrancaServiceServiceagent(URL wsdlLocation) {
        super(wsdlLocation, REGISTROCOBRANCASERVICESERVICEAGENT_QNAME);
    }

    public RegistroCobrancaServiceServiceagent(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTROCOBRANCASERVICESERVICEAGENT_QNAME, features);
    }

    public RegistroCobrancaServiceServiceagent(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistroCobrancaServiceServiceagent(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "RegistroCobrancaEndpoint")
    public PortType getRegistroCobrancaEndpoint() {
        return super.getPort(new QName("http://xmlns.example.com/1466775928160", "RegistroCobrancaEndpoint"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "RegistroCobrancaEndpoint")
    public PortType getRegistroCobrancaEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1466775928160", "RegistroCobrancaEndpoint"), PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTROCOBRANCASERVICESERVICEAGENT_EXCEPTION!= null) {
            throw REGISTROCOBRANCASERVICESERVICEAGENT_EXCEPTION;
        }
        return REGISTROCOBRANCASERVICESERVICEAGENT_WSDL_LOCATION;
    }

}
