//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.19 at 08:13:21 PM BRT 
//


package carnepagcontas.bb.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.criativasoft.eduaccess.bb.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.criativasoft.eduaccess.bb.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Erro }
     * 
     */
    public Erro createErro() {
        return new Erro();
    }

    /**
     * Create an instance of {@link Resposta }
     * 
     */
    public Resposta createResposta() {
        return new Resposta();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Requisicao }
     * 
     */
    public Requisicao createRequisicao() {
        return new Requisicao();
    }

}
