//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.19 at 08:13:21 PM BRT 
//


package carnepagcontas.bb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="siglaSistemaMensagem" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoRetornoPrograma" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="nomeProgramaErro" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoMensagemErro" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="68"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroPosicaoErroPrograma" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoRetornoPrograma" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="textoNumeroTituloCobrancaBb" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroCarteiraCobranca" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroVariacaoCarteiraCobranca" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoPrefixoDependenciaBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroContaCorrenteBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoCliente" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="linhaDigitavel" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="47"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoBarraNumerico" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="52"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoTipoEnderecoBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomeLogradouroBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomeBairroBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomeMunicipioBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoMunicipioBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="siglaUfBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codigoCepBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indicadorComprovacaoBeneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numeroContratoCobranca" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "siglaSistemaMensagem",
    "codigoRetornoPrograma",
    "nomeProgramaErro",
    "textoMensagemErro",
    "numeroPosicaoErroPrograma",
    "codigoTipoRetornoPrograma",
    "textoNumeroTituloCobrancaBb",
    "numeroCarteiraCobranca",
    "numeroVariacaoCarteiraCobranca",
    "codigoPrefixoDependenciaBeneficiario",
    "numeroContaCorrenteBeneficiario",
    "codigoCliente",
    "linhaDigitavel",
    "codigoBarraNumerico",
    "codigoTipoEnderecoBeneficiario",
    "nomeLogradouroBeneficiario",
    "nomeBairroBeneficiario",
    "nomeMunicipioBeneficiario",
    "codigoMunicipioBeneficiario",
    "siglaUfBeneficiario",
    "codigoCepBeneficiario",
    "indicadorComprovacaoBeneficiario",
    "numeroContratoCobranca"
})
@XmlRootElement(name = "resposta")
public class Resposta {

    protected String siglaSistemaMensagem;
    protected Short codigoRetornoPrograma;
    protected String nomeProgramaErro;
    protected String textoMensagemErro;
    protected Short numeroPosicaoErroPrograma;
    protected Short codigoTipoRetornoPrograma;
    protected String textoNumeroTituloCobrancaBb;
    protected Short numeroCarteiraCobranca;
    protected Short numeroVariacaoCarteiraCobranca;
    protected Short codigoPrefixoDependenciaBeneficiario;
    protected Integer numeroContaCorrenteBeneficiario;
    protected Integer codigoCliente;
    protected String linhaDigitavel;
    protected String codigoBarraNumerico;
    protected Short codigoTipoEnderecoBeneficiario;
    protected String nomeLogradouroBeneficiario;
    protected String nomeBairroBeneficiario;
    protected String nomeMunicipioBeneficiario;
    protected Integer codigoMunicipioBeneficiario;
    protected String siglaUfBeneficiario;
    protected Integer codigoCepBeneficiario;
    protected String indicadorComprovacaoBeneficiario;
    protected Integer numeroContratoCobranca;

    /**
     * Gets the value of the siglaSistemaMensagem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaSistemaMensagem() {
        return siglaSistemaMensagem;
    }

    /**
     * Sets the value of the siglaSistemaMensagem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaSistemaMensagem(String value) {
        this.siglaSistemaMensagem = value;
    }

    /**
     * Gets the value of the codigoRetornoPrograma property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoRetornoPrograma() {
        return codigoRetornoPrograma;
    }

    /**
     * Sets the value of the codigoRetornoPrograma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoRetornoPrograma(Short value) {
        this.codigoRetornoPrograma = value;
    }

    /**
     * Gets the value of the nomeProgramaErro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeProgramaErro() {
        return nomeProgramaErro;
    }

    /**
     * Sets the value of the nomeProgramaErro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeProgramaErro(String value) {
        this.nomeProgramaErro = value;
    }

    /**
     * Gets the value of the textoMensagemErro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoMensagemErro() {
        return textoMensagemErro;
    }

    /**
     * Sets the value of the textoMensagemErro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoMensagemErro(String value) {
        this.textoMensagemErro = value;
    }

    /**
     * Gets the value of the numeroPosicaoErroPrograma property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNumeroPosicaoErroPrograma() {
        return numeroPosicaoErroPrograma;
    }

    /**
     * Sets the value of the numeroPosicaoErroPrograma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNumeroPosicaoErroPrograma(Short value) {
        this.numeroPosicaoErroPrograma = value;
    }

    /**
     * Gets the value of the codigoTipoRetornoPrograma property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoRetornoPrograma() {
        return codigoTipoRetornoPrograma;
    }

    /**
     * Sets the value of the codigoTipoRetornoPrograma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoRetornoPrograma(Short value) {
        this.codigoTipoRetornoPrograma = value;
    }

    /**
     * Gets the value of the textoNumeroTituloCobrancaBb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextoNumeroTituloCobrancaBb() {
        return textoNumeroTituloCobrancaBb;
    }

    /**
     * Sets the value of the textoNumeroTituloCobrancaBb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextoNumeroTituloCobrancaBb(String value) {
        this.textoNumeroTituloCobrancaBb = value;
    }

    /**
     * Gets the value of the numeroCarteiraCobranca property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNumeroCarteiraCobranca() {
        return numeroCarteiraCobranca;
    }

    /**
     * Sets the value of the numeroCarteiraCobranca property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNumeroCarteiraCobranca(Short value) {
        this.numeroCarteiraCobranca = value;
    }

    /**
     * Gets the value of the numeroVariacaoCarteiraCobranca property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNumeroVariacaoCarteiraCobranca() {
        return numeroVariacaoCarteiraCobranca;
    }

    /**
     * Sets the value of the numeroVariacaoCarteiraCobranca property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNumeroVariacaoCarteiraCobranca(Short value) {
        this.numeroVariacaoCarteiraCobranca = value;
    }

    /**
     * Gets the value of the codigoPrefixoDependenciaBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoPrefixoDependenciaBeneficiario() {
        return codigoPrefixoDependenciaBeneficiario;
    }

    /**
     * Sets the value of the codigoPrefixoDependenciaBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoPrefixoDependenciaBeneficiario(Short value) {
        this.codigoPrefixoDependenciaBeneficiario = value;
    }

    /**
     * Gets the value of the numeroContaCorrenteBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroContaCorrenteBeneficiario() {
        return numeroContaCorrenteBeneficiario;
    }

    /**
     * Sets the value of the numeroContaCorrenteBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroContaCorrenteBeneficiario(Integer value) {
        this.numeroContaCorrenteBeneficiario = value;
    }

    /**
     * Gets the value of the codigoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodigoCliente() {
        return codigoCliente;
    }

    /**
     * Sets the value of the codigoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodigoCliente(Integer value) {
        this.codigoCliente = value;
    }

    /**
     * Gets the value of the linhaDigitavel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinhaDigitavel() {
        return linhaDigitavel;
    }

    /**
     * Sets the value of the linhaDigitavel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinhaDigitavel(String value) {
        this.linhaDigitavel = value;
    }

    /**
     * Gets the value of the codigoBarraNumerico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoBarraNumerico() {
        return codigoBarraNumerico;
    }

    /**
     * Sets the value of the codigoBarraNumerico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoBarraNumerico(String value) {
        this.codigoBarraNumerico = value;
    }

    /**
     * Gets the value of the codigoTipoEnderecoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCodigoTipoEnderecoBeneficiario() {
        return codigoTipoEnderecoBeneficiario;
    }

    /**
     * Sets the value of the codigoTipoEnderecoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCodigoTipoEnderecoBeneficiario(Short value) {
        this.codigoTipoEnderecoBeneficiario = value;
    }

    /**
     * Gets the value of the nomeLogradouroBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeLogradouroBeneficiario() {
        return nomeLogradouroBeneficiario;
    }

    /**
     * Sets the value of the nomeLogradouroBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeLogradouroBeneficiario(String value) {
        this.nomeLogradouroBeneficiario = value;
    }

    /**
     * Gets the value of the nomeBairroBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeBairroBeneficiario() {
        return nomeBairroBeneficiario;
    }

    /**
     * Sets the value of the nomeBairroBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeBairroBeneficiario(String value) {
        this.nomeBairroBeneficiario = value;
    }

    /**
     * Gets the value of the nomeMunicipioBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeMunicipioBeneficiario() {
        return nomeMunicipioBeneficiario;
    }

    /**
     * Sets the value of the nomeMunicipioBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeMunicipioBeneficiario(String value) {
        this.nomeMunicipioBeneficiario = value;
    }

    /**
     * Gets the value of the codigoMunicipioBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodigoMunicipioBeneficiario() {
        return codigoMunicipioBeneficiario;
    }

    /**
     * Sets the value of the codigoMunicipioBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodigoMunicipioBeneficiario(Integer value) {
        this.codigoMunicipioBeneficiario = value;
    }

    /**
     * Gets the value of the siglaUfBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaUfBeneficiario() {
        return siglaUfBeneficiario;
    }

    /**
     * Sets the value of the siglaUfBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaUfBeneficiario(String value) {
        this.siglaUfBeneficiario = value;
    }

    /**
     * Gets the value of the codigoCepBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodigoCepBeneficiario() {
        return codigoCepBeneficiario;
    }

    /**
     * Sets the value of the codigoCepBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodigoCepBeneficiario(Integer value) {
        this.codigoCepBeneficiario = value;
    }

    /**
     * Gets the value of the indicadorComprovacaoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorComprovacaoBeneficiario() {
        return indicadorComprovacaoBeneficiario;
    }

    /**
     * Sets the value of the indicadorComprovacaoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorComprovacaoBeneficiario(String value) {
        this.indicadorComprovacaoBeneficiario = value;
    }

    /**
     * Gets the value of the numeroContratoCobranca property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroContratoCobranca() {
        return numeroContratoCobranca;
    }

    /**
     * Sets the value of the numeroContratoCobranca property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroContratoCobranca(Integer value) {
        this.numeroContratoCobranca = value;
    }

}
