INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01101,011012593 ,'2593','FORTALECIMENTO DA GESTÃO DA ALEPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01101,011012143 ,'2143','AMPLIAÇÃO DA ESTRUTURA DA TV E RÁDIO ASSEMBLEIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01101,011012665 ,'2665','MANUTENÇÃO E AMPLIAÇÃO DA ESCOLA DO PODER LEGISLATIVO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01201,012012802 ,'2802','AMPLIAÇÃO DA ESTRUTURA DA TV E RÁDIO ASSEMBLEIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,021012623 ,'2623','GESTÃO E MANUTENÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,021012662 ,'2662','INTERIORIZAÇÃO DAS AÇÕES DO TRIBUNAL DE CONTAS DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,021012738 ,'2738','TRIBUNAL ON-LINE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,021012702 ,'2702','PROGRAMA - PESSOAS EM FOCO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02102,021022654 ,'2654','INFRAESTRUTURAÇÃO DO TCE E EDUCAÇÃO CONTINUADA DOS SERVIDORES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04101,041012618 ,'2618','GESTÃO DE PESSOAS - CRIAÇÃO, INSTALAÇÃO E PROVIMENTO DE VARAS E JUIZADOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04101,041012332 ,'2332','APOIO ADMINISTRATIVO ¿ TRIBUNAL DE JUSTIÇA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04103,041032328 ,'2328','APOIO ADMINISTRATIVO ¿ CORREGEDORIA GERAL DE JUSTIÇA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04103,041032434 ,'2434','APOIO, CONTROLE E FISCALIZAÇÃO JUDICIAL E EXTRAJUDICIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,041052661 ,'2661','INFRAESTRUTURA E REAPARELHAMENTO DE TECNOLOGIA DA INFORMAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,041052720 ,'2720','REAPARELHAMENTO DA JUSTIÇA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,041052655 ,'2655','INFRAESTRUTURA DE PRÉDIOS DA JUSTIÇA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04106,041062737 ,'2737','TREINAMENTO E CAPACITAÇÃO DE SERVIDORES E MAGISTRADOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11102,111021594 ,'1594','GESTÃO DA VICE-GOVERNADORIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11103,111031547 ,'1547','COORDENAÇÃO GERAL DO GABINETE MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,111102669 ,'2669','MELHORIA DAS CONDIÇÕES DE CONSERVAÇÃO E PRESERVAÇÃO DOS DOCUMENTOS HISTÓRICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,111102106 ,'2106','ACOMPANHAMENTO E ASSESSORAMENTO DAS AÇÕES GOVERNAMENTAIS NAS ESFERAS MUNICIPAL , ESTADUAL E FEDERAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,111102600 ,'2600','FORTALECIMENTO DAS RELAÇÕES INSTITUCIONAIS ENTRE OS VÁRIOS ENTES DA FEDERAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,111102327 ,'2327','APOIO ADMINISTRATIVO À COORDENAÇÃO GERAL DA SECRETARIA DE GOVERNO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11111,111112538 ,'2538','COORDENAÇÃO GERAL DA SURPI ¿ BSB',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11111,111112559 ,'2559','DIVULGAÇÃO CULTURAL E DE POTENCIALIDADES DO PIAUÍ EM BRASÍLIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11111,111112391 ,'2391','APOIO A IMIGRANTES PIAUIENSES EM VULNERABILIDADE SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,111131616 ,'1616','MODERNIZAÇÃO DA COORDENADORIA ESTADUAL DA JUVENTUDE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,111131596 ,'1596','GESTÃO E MANUTENÇÃO DA COORDENADORIA ESTADUAL DA JUVENTUDE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,111131584 ,'1584','FORTALECIMENTO DO CONSELHO ESTADUAL DE DIREITOS DA JUVENTUDE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,111131558 ,'1558','EMPREENDA JOVEM',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,111131609 ,'1609','JUVENTUDE E CULTURA VIVA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,111131554 ,'1554','EDUCAÇÃO, CIDADANIA E DESENVOLVIMENTO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,111131532 ,'1532','CIDADANIA INCLUSIVA: JUVENTUDE, ESPORTE E LAZER',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,111142604 ,'2604','FORTALECIMENTO DOS CONSELHOS DE POLÍTICAS PÚBLICAS SOBRE DROGAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,111142642 ,'2642','IMPLEMENTAÇÃO DE AÇÕES DE PREVENÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,111142573 ,'2573','ESTRUTURAÇÃO E FORTALECIMENTO DA REDE DE ATENÇÃO PSICOSSOCIAL DO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,111141592 ,'1592','GESTÃO DA COORDENADORIA DE ENFRENTAMENTO ÀS DROGAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,111152127 ,'2127','ADMINISTRAÇÃO GERAL DA COORDENADORIA ESTADUAL DE POLÍTICAS PARA AS MULHERES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,111152713 ,'2713','PROMOÇÃO DO ATENDIMENTO AS MULHERES EM SITUAÇÃO DE VIOLÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,111152724 ,'2724','REESTRUTURAÇÃO E MANUTENÇÃO DO CONSELHO ESTADUAL DE DEFESA DOS DIREITOS DA MULHER E APOIO À CRIAÇÃO DE CONSELHOS MUNICIPAIS DE DEFESA DOS DIREITOS DA MULHER',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,111152294 ,'2294','APOIO, ACOMPANHAMENTO E MONITORAMENTO À IMPLEMENTAÇÃO DE POLÍTICAS PÚBLICAS DIRECIONADAS PARA A GARANTIA DOS DIREITOS DAS MULHERES.',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11116,111162613 ,'2613','GESTÃO DA COORDENADORIA DE DESENVOLVIMENTO SOCIAL E LAZER',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11116,111162603 ,'2603','FORTALECIMENTO DO LAZER E DESENVOLVIMENTO SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,111172614 ,'2614','GESTÃO DA COORDENADORIA DE FOMENTO À IRRIGAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,111172597 ,'2597','FORTALECIMENTO DA INFRAESTRUTURA HÍDRICA PARA A IRRIGAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,111171580 ,'1580','FORTALECIMENTO DA INFRAESTRUTURA DA AGRICULTURA FAMILIAR IRRIGADA NO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,111171588 ,'1588','FORTALECIMENTO E AMPLIAÇÃO DA IRRIGAÇÃO VOLTADA AO AGRONEGÓCIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,111171581 ,'1581','FORTALECIMENTO DA INFRAESTRUTURA DE IRRIGAÇÃO NO SEMIÁRIDO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11118,111182615 ,'2615','GESTÃO DA COORDENADORIA DE FOMENTO AO SANEAMENTO RURAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11118,111182631 ,'2631','IMPLANTAÇÃO DE MELHORIAS SANITÁRIAS DOMICILIARES NAS COMUNIDADES RURAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11118,111182638 ,'2638','IMPLANTAÇÃO E RECUPERAÇÃO DE SISTEMAS DE ABASTECIMENTO DE ÁGUA E ESGOTAMENTO SANITÁRIO NAS COMUNIDADES RURAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11201,112012810 ,'2810','ADMINISTRAÇÃO GERAL DA AGRESPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11201,112012811 ,'2811','MODERNIZAÇÃO DA AGRESPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012534 ,'2534','COORDENAÇÃO GERAL DA SECRETARIA DE SEGURANÇA PÚBLICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012685 ,'2685','MODERNIZAÇÃO DAS ESTRUTURAS, CAPACITAÇÃO E TREINAMENTO PARA OS PROFISSIONAIS DE SEGURANÇA PÚBLICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012704 ,'2704','PROJETO MIRIM CIDADÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012157 ,'2157','AMPLIAÇÃO DAS ESTRUTURAS DE SEGURANÇA PÚBLICA DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012264 ,'2264','APERFEIÇOAMENTO DO SISTEMA DE INTELIGÊNCIA E POTENCIALIZAÇÃO DO PARQUE TECNOLÓGICO E POLÍCIA TÉCNICO-CIENTÍFICA DA SEGURANÇA PÚBLICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012630 ,'2630','IMPLANTAÇÃO DE ESTRATÉGIA DE POLÍCIA COMUNITÁRIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012549 ,'2549','CRIAÇÃO DE UNIDADES REGIONAIS INTEGRADAS DE BAIXA, MÉDIA E ALTA COMPLEXIDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012568 ,'2568','ESTRATÉGIAS DE ATENDIMENTO ADEQUADO ÀS VÍTIMAS ESPECÍFICAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012561 ,'2561','ELABORAÇÃO DO MAPA DA SEGURANÇA PÚBLICA DO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,121012436 ,'2436','AQUISIÇÃO DE MATERIAL BÉLICO, EQUIPAMENTO DE PROTEÇÃO INDIVIDUAL, MATERIAL DE INFORMÁTICA E TELEMÁTICA E VEÍCULOS AUTOMOTORES, AÉREOS E MARÍTIMOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12102,121022428 ,'2428','COORDENAÇÃO DA DELEGACIA GERAL DA POLÍCIA CIVIL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12102,121024004 ,'4004','MANUTENÇÃO E REESTRUTURAÇÃO DAS UNIDADES DE SEGURANÇA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13101,131012689 ,'2689','MODERNIZAÇÃO E APERFEIÇOAMENTO DA GESTÃO FISCAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13101,131011627 ,'1627','MODERNIZAÇÃO E APERFEIÇOAMENTO DA GESTÃO ADMINISTRATIVA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13116,131162674 ,'2674','MODERNIZAÇÃO DA ADMINISTRAÇÃO TRIBUTÁRIA E APERFEIÇOAMENTO NA GESTÃO DE RECURSOS HUMANOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13203,132032583 ,'2583','FOMENTO AO DESENVOLVIMENTO DO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13204,132042417 ,'2417','APOIO AO FUNDO GARANTIDOR DOS MICRO E PEQUENOS EMPREENDIMENTOS DO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13205,132052416 ,'2416','APOIO AO FUNDO ESPECIAL DE PRODUCÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13206,132062467 ,'2467','FUNDO ESPECIAL DE CRÉDITO INADIMPLIDOS E DÍVIDA ATIVA - FECIDAPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14101,141012679 ,'2679','MODERNIZAÇÃO DA GESTÃO DA SEDUC',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14101,141012579 ,'2579','EXPANSÃO E FORTALECIMENTO DA UNIVERSIDADE ABERTA NO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022594 ,'2594','FORTALECIMENTO DA GESTÃO DEMOCRÁTICA DA EDUCAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022276 ,'2276','APLICAÇÃO DOS RECURSOS DO FUNDEB',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022648 ,'2648','IMPLEMENTAÇÃO DO PROGRAMA DE INCENTIVO AO ALUNO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022575 ,'2575','EXPANSÃO DA REDE E-TEC',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022577 ,'2577','EXPANSÃO DO PRONATEC',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022641 ,'2641','IMPLEMENTAÇÃO DAS AÇÕES DO PROGRAMA BRASIL PROFISSIONALIZADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022649 ,'2649','IMPLEMENTAÇÃO DO PROGRAMA PROJOVEM URBANO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022580 ,'2580','EXPANSÃO E REESTRUTURAÇÃO DA REDE DE EDUCAÇÃO DE JOVENS E ADULTOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022647 ,'2647','IMPLEMENTAÇÃO DO PROGRAMA DE ALFABETIZAÇÃO DE JOVENS E ADULTOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022740 ,'2740','UNIVERSALIZAÇÃO DO ATENDIMENTO DA EDUCAÇÃO BÁSICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022454 ,'2454','AVALIAÇÃO DOS INDICADORES EDUCACIONAIS DA REDE ESTADUAL DE ENSINO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141022643 ,'2643','IMPLEMENTAÇÃO DE AÇÕES DE VALORIZAÇÃO DOS PROFISSIONAIS DA EDUCAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,141021555 ,'1555','EDUCAÇÃO CONTEXTUALIZADA NA REGIÃO DO SEMIÁRIDO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14103,141032767 ,'2767','FORTALECIMENTO DA GESTÃO DEMOCRÁTICA DA EDUCAÇÃO NO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14103,141032764 ,'2764','MODERNIZAÇÃO DA GESTÃO DA COORDENADORIA DO PROGRAMA DE EDUCAÇÃO POR MEIO DE MEDIAÇÕES TECNOLÓGICAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14103,141032765 ,'2765','IMPLEMENTAÇÃO DAS AÇÕES DO PROGRAMA BRASIL PROFISSIONALIZADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14103,141032805 ,'2805','EXPANSÃO E FORTALECIMENTO DA UNIVERSIDADE ABERTA NO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,142012499 ,'2499','COORDENAÇÃO GERAL DA FUESPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,142012686 ,'2686','MODERNIZAÇÃO DAS INSTALAÇÕES DA UESPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,142012581 ,'2581','EXTENSÃO UNIVERSITÁRIA E ASSISTÊNCIA COMUNITÁRIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,142012566 ,'2566','ENSINO DE GRADUAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,142012567 ,'2567','ENSINO DE PÓS-GRADUAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,142012694 ,'2694','PESQUISA E TECNOLOGIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,142032668 ,'2668','MELHORIA DA GESTÃO ESPORTIVA DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,142032571 ,'2571','ESTRUTURAÇÃO DO SISTEMA ESTADUAL DE ESPORTE E LAZER',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,142032692 ,'2692','ORGANIZAÇÃO E REALIZAÇÃO DE EVENTOS ESPORTIVOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,142032344 ,'2344','APOIO A EVENTOS ESPORTIVOS, FORMAÇÃO, QUALIFICAÇÃO E FOMENTO À PARTICIPAÇÃO DE ATLETAS EM EVENTOS ESPORTIVOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14204,142042134 ,'2134','ADMINISTRAÇÃO GERAL DA FUNDAÇÃO ANTARES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011623 ,'1623','MODERNIZAÇÃO DA SECRETARIA DO DESENVOLVIMENTO RURAL (SDR)',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151012521 ,'2521','COORDENAÇÃO GERAL DA SDR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011590 ,'1590','GERAÇÃO DE EMPREGO E RENDA - PROGERE II',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011653 ,'1653','VIVA O SEMIÁRIDO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011635 ,'1635','POTENCIALIZAÇÃO DOS MERCADOS INSTITUCIONAIS EXISTENTES E VIABILIZAÇÃO DE NOVAS OPORTUNIDADES DE COMERCIALIZAÇÃO DOS PRODUTOS DA AGRICULTURA FAMILIAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011569 ,'1569','FOMENTO AOS SISTEMAS DE PRODUÇÃO FAMILIAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011613 ,'1613','MINHA CASA MINHA VIDA RURAL - PNHR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011516 ,'1516','ÁGUA PARA TODOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011517 ,'1517','AMPLIAÇÃO DA ADESÃO AO PROGRAMA GARANTIA SAFRA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011582 ,'1582','FORTALECIMENTO DAS ORGANIZAÇÕES SOCIAIS E ARTICULAÇÃO DAS INSTITUIÇÕES GOVERNAMENTAIS E NÃO GOVERNAMENTAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011585 ,'1585','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS AGROPECUÁRIOS E DA SOCIOBIODIVERSIDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011586 ,'1586','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS LOCAIS POR MEIO DO FOMENTO À PRODUÇÃO AGROPECUÁRIA.',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011564 ,'1564','EXECUÇÃO DO PROGRAMA NACIONAL DO CRÉDITO FUNDIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,151011523 ,'1523','APROVEITAMENTO DAS POTENCIALIDADES AGROENERGÉTICAS DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,151032746 ,'2746','ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DO AGRONEGÓCIO E DOS CERRADOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,151032747 ,'2747','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS AGROPECUÁRIOS E DA SOCIOBIODIVERSIDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,151032748 ,'2748','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS LOCAIS POR MEIO DO FOMENTO À PRODUÇÃO AGROPECUÁRIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15105,151052753 ,'2753','ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DE COMBATE A POBREZA RURAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15105,151052754 ,'2754','GERAÇÃO DE EMPREGO E RENDA - PROGERE II',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15105,151052755 ,'2755','VIVA O SEMIÁRIDO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15106,151062770 ,'2770','ADMINISTRAÇÃO GERAL DA COORDENADORIA DE APOIO A PISCICULTURA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15106,151061763 ,'1763','CONSTRUÇÃO DE ESTAÇÃO DE PISCICULTURA ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15106,151062771 ,'2771','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS AGROPECUÁRIOS E DA SOCIOBIODIVERSIDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,152011539 ,'1539','COORDENAÇÃO DO INTERPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,152012687 ,'2687','MODERNIZAÇÃO DO INTERPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,152011593 ,'1593','GESTÃO DAS TERRAS PÚBLICAS ESTADUAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,152011650 ,'1650','REGULARIZAÇÃO FUNDIÁRIA EM ÁREAS URBANAS NO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,152022547 ,'2547','COORDENAÇÃO GERAL DO EMATER',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,152021625 ,'1625','MODERNIZAÇÃO DO EMATER',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,152022451 ,'2451','ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,152022452 ,'2452','ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL NO SEMIÁRIDO PIAUIENSE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042624 ,'2624','GESTÃO E MANUTENÇÃO DA ADAPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042489 ,'2489','CONTROLE DE AGROTÓXICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042551 ,'2551','DEFESA ANIMAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042552 ,'2552','DEFESA VEGETAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042700 ,'2700','PROGRAMA ESTADUAL DE ERRADICAÇÃO E PREVENÇÃO DA FEBRE AFTOSA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042735 ,'2735','SERVIÇO DE CLASSIFICAÇÃO DE PRODUTOS DE ORIGEM VEGETAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042705 ,'2705','PROMOÇÃO DA EDUCAÇÃO SANITÁRIA ANIMAL E VEGETAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,152042736 ,'2736','SERVIÇO DE INSPEÇÃO ESTADUAL (SIE)',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,161011563 ,'1563','ESTUDO, PESQUISA, ELABORAÇÃO, EXECUÇÃO E ACOMPANHAMENTO DE ESTUDOS E PROJETOS DE OBRAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,161012536 ,'2536','COORDENAÇÃO GERAL DA SEINFRA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,161011604 ,'1604','INFRAESTRUTURA DE OBRAS, TRANSPORTE E TURISMO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,161011605 ,'1605','INFRAESTRUTURA HÍDRICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,161011652 ,'1652','SANEAMENTO BASICO AMBIENTAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16202,162022142 ,'2142','AMPLIAÇÃO DA COLETA E TRATAMENTO DE ESGOTO SANITÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16202,162022739 ,'2739','UNIVERSALIZAÇÃO DO ACESSO À ÁGUA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081548 ,'1548','COORDENAÇÃO GERAL DO IDEPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081632 ,'1632','PAVIMENTAÇÃO ASFÁLTICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081633 ,'1633','PAVIMENTAÇÃO EM PARALELEPÍPEDO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081536 ,'1536','CONSTRUÇÃO DE MACRODRENAGEM',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081644 ,'1644','RECUPERAÇÃO E REFORMA DE ESTRADAS VICINAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081533 ,'1533','CONSTRUÇÃO DE ADUTORAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081599 ,'1599','IMPLANTAÇÃO DE SISTEMA DE ABASTECIMENTO DE ÁGUA E CONSTRUÇÃO DE ESTAÇÃO DE TRATAMENTO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081537 ,'1537','CONTRATAÇÃO DE CONSULTORIA EM OBRAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081534 ,'1534','CONSTRUÇÃO DE BARRAGENS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081535 ,'1535','CONSTRUÇÃO DE ESTAÇÃO DE PISCICULTURA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081556 ,'1556','ELABORAÇÃO DE ESTUDOS E PROJETOS BÁSICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162081610 ,'1610','MANUTENÇÃO E CONSERVAÇÃO DE BARRAGENS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012596 ,'2596','FORTALECIMENTO DA GESTÃO NO ÂMBITO DO SUS-PI (CONTROLE, PLANEJAMENTO, REGULAÇÃO, AVALIAÇÃO, OUVIDORIA, AUDITORIA, EDUCAÇÃO PERMANENTE DA REDE PÚBLICA DE SAÚDE E DAS UNIDADES ADMINISTRATIVAS DA SESAPI)',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012533 ,'2533','COORDENAÇÃO GERAL DA SECRETARIA DE ESTADO DA SAÚDE - SESAPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012698 ,'2698','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE PARA A POPULAÇÃO DO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171011570 ,'1570','FOMENTO DAS AÇÕES E SERVIÇOS MEDIANTE CONVÊNIOS E CONTRATOS DE REPASSES COM MUNICIPIOS, M.SAÚDE, CEF E OUTROS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012589 ,'2589','FORTALECIMENTO DA ATENÇÃO PRIMÁRIA/SECUNDÁRIA/ESPECIALIZADA NO CONTEXTO DAS AÇÕES E SERVIÇOS DE SAÚDE DO SUS-PI NOS 224 MUNICÍPIOS DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012725 ,'2725','REFORMA, AMPLIAÇÃO, CONSTRUÇÃO E AQUISIÇÃO DE EQUIPAMENTOS PARA AS UNIDADES DESCENTRALIZADAS DA SESAPI E SERVIÇOS DE SAÚDE DA REDE ESTADUAL, COM VISTAS À IMPLEMENTAÇÃO DAS RAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012188 ,'2188','AMPLIAÇÃO E DIVERSIFICAÇÃO DA OFERTA DE CONSULTAS, EXAMES LABORATORIAIS E PROCEDIMENTOS ESPECIALIZADOS DE SAÚDE, DE MÉDIA E ALTA COMPLEXIDADE, NO ÂMBITO DOS SERVIÇOS PÚBLICOS DE REFERÊNCIA REGIONAL E ESTADUAL DO SUS-PI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012691 ,'2691','MODERNIZAÇÃO E QUALIFICAÇÃO DO PROCESSO DE GESTÃO, AQUISIÇÃO, CONTROLE DE ESTOQUE, ARMAZENAMENTO, DISTRIBUIÇÃO E DISPENSAÇÃO DE MEDICAMENTOS EM TODAS AS UNIDADES DE ASSISTÊNCIA FARMACÊUTICA SOB GESTÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012711 ,'2711','PROMOÇÃO DE VIGILÂNCIAS EM SAÚDE EPIDEMIOLÓGICA, AMBIENTAL E SANITÁRIA E SAÚDE DO TRABALHADOR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171012637 ,'2637','IMPLANTAÇÃO E IMPLEMENTAÇÃO DAS REDES TEMÁTICAS NAS REGIÕES DE SAÚDE DO ESTADO, VIABILIZANDO AÇÕES DE PROMOÇÃO, PREVENÇÃO, TRATAMENTO E REABILITAÇÃO, TENDO A ATENÇÃO BÁSICA COMO ORDENADORA DO CUIDADO EM REDE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17102,171021527 ,'1527','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA CHAPADA DAS MANGABEIRAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17103,171031637 ,'1637','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO VALE DOS RIOS PIAUÍ E ITAUEIRA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17104,171041528 ,'1528','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA PLANÍCIE LITORÂNEA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17105,171051636 ,'1636','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DO VALE DO RIO GUARIBAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17106,171061530 ,'1530','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO SERRA DA CAPIVARA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17107,171072118 ,'2118','PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17108,171081529 ,'1529','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DOS CARNAUBAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17109,171091524 ,'1524','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO CHAPADA DAS MANGABEIRAS - CORRENTE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17110,171101638 ,'1638','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO VALE DO CANINDÉ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17111,171111526 ,'1526','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DOS COCAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17112,171121518 ,'1518','AMPLIAÇÃO E DIVERSIFICAÇÃO DA OFERTA DE EXAMES LABORATORIAIS ESPECIALIZADOS DE SAÚDE PÚBLICA, DE MÉDIA E ALTA COMPLEXIDADE NO ÂMBITO DO SUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17113,171132448 ,'2448','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE PARA A POPULAÇÃO INFANTIL DO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17114,171142443 ,'2443','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE A PACIENTES COM TRANSTORNO MENTAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17115,171152447 ,'2447','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO MATERNA E RÉCEM NASCIDOS, REFERENCIADA DO SUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17116,171162449 ,'2449','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL ESPECIALIZADA NA ÁREA DE DOENÇAS INFECCIOSAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17117,171172697 ,'2697','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE DE FORMA INDISSOCIÁVEL E INTEGRADA AO ENSINO, PESQUISA E EXTENSÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17118,171182437 ,'2437','ASSISTÊNCIA HEMATOLÓGICA E HEMOTERÁPICA DE QUALIDADE À POPULAÇÃO DOS 224 MUNICÍPIOS DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17119,171192445 ,'2445','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA PLANÍCIE LITORÂNEA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17121,171212439 ,'2439','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DE ESPERANTINA REFERENCIADA PELO SUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17123,171232441 ,'2441','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO N0 TERRITORIO VALE DO CANINDÉ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17124,171242442 ,'2442','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO NO TERRITÓRIO SERRA DA CAPIVARA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17125,171252440 ,'2440','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO VALE DO SAMBITO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17126,171262696 ,'2696','PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS - TERRITÓRIO ALTO PARNAÍBA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17128,171282438 ,'2438','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17129,171292591 ,'2591','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PARNAÍBA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17130,171302592 ,'2592','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PIRIPIRI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17131,171311521 ,'1521','APOIO TÉCNICO AOS MUNICÍPIOS PARA GARANTIR A INTEGRALIDADE DA ATENÇÃO À SAÚDE NOS MUNICÍPIOS DA SUA ÁREA DE ABRANGÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17132,171321577 ,'1577','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE VALENÇA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17133,171331575 ,'1575','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17134,171341574 ,'1574','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE FLORIANO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17135,171351551 ,'1551','DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE SÃO RAIMUNDO NONATO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17136,171361573 ,'1573','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE BOM JESUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17137,171371576 ,'1576','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE TERESINA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17138,171381525 ,'1525','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE INTEGRADA DO MOCAMBINHO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17139,171391571 ,'1571','FOMENTO DAS AÇÕES E SERVIÇOS MEDIANTE CONVÊNIOS E CONTRATOS DE REPASSES COM MUNICIPIOS, M.SAÚDE, CEF E OUTROS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17139,171392484 ,'2484','CONSTRUÇÃO, REFORMA , AMPLIAÇÃO E AQUISIÇÃO DE EQUIPAMENTOS PARA AS UNIDADES DE SAÚDE NOS MUNICÍPIOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17140,171402111 ,'2111','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE OEIRAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17141,171412116 ,'2116','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA REGIONAL DE SAÚDE - URUÇUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17142,171422135 ,'2135','PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS - TERRITÓRIO ENTRE RIOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17143,171432011 ,'2011','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17144,171442012 ,'2012','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE SAÚDE DE BOCAÍNA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17145,171452015 ,'2015','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17146,171462030 ,'2030','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17147,171472039 ,'2039','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE SAÚDE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17148,171482055 ,'2055','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17149,171492078 ,'2078','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE SANTA FILOMENA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17150,171502104 ,'2104','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17151,171512110 ,'2110','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE ITAINÓPOLIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17152,171522154 ,'2154','PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,191011634 ,'1634','PLANEJA PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,191012107 ,'2107','ACOMPANHAMENTO ESTRATÉGICO E DESENVOLVIMENTO SOCIOECONÔMICO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,191011629 ,'1629','MONITORAMENTO E AVALIAÇÃO DE POLÍTICAS PÚBLICAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,191011618 ,'1618','MODERNIZAÇÃO DA GESTÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,191012537 ,'2537','COORDENAÇÃO GERAL DA SEPLAN',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,192012574 ,'2574','ESTUDOS E PESQUISAS SOCIOECONÔMICAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,192012606 ,'2606','FORTALECIMENTO INSTITUCIONAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,192012693 ,'2693','PESQUISA DE ESTATÍSTICA E INFORMAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,192012502 ,'2502','COORDENAÇÃO GERAL DA FUNDAÇÃO CEPRO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201011542 ,'1542','COORDENAÇÃO GERAL DA SEDET',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012418 ,'2418','APOIO A PESQUISAS E ESTRATÉGIAS PARA O DESENVOLVIMENTO SUSTENTÁVEL E A BIODIVERSIDADE NO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012554 ,'2554','DESENVOLVIMENTO DA BIOTECNOLOGIA NO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012557 ,'2557','DIFUSÃO CIENTÍFICA E TECNOLÓGICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012632 ,'2632','IMPLANTAÇÃO DE PARQUES TECNOLÓGICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012432 ,'2432','APOIO ÀS INICIATIVAS DE DESENVOLVIMENTO E INOVAÇÃO TECNOLÓGICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012588 ,'2588','FORTALECIMENTO AOS ARRANJOS PRODUTIVOS LOCAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012608 ,'2608','FUNDO DE DESENVOLVIMENTO INDUSTRIAL DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201011583 ,'1583','FORTALECIMENTO DO COMÉRCIO E SERVIÇO DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,201012653 ,'2653','INCENTIVO ÀS EXPORTAÇÕES E ATRAÇÃO DE INVESTIMENTOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20103,201032749 ,'2749','ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20201,202012504 ,'2504','COORDENAÇÃO GERAL DA JUCEPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20201,202011611 ,'1611','MELHORIA DA INFRAESTRUTURA DA JUNTA COMERCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20201,202012688 ,'2688','MODERNIZAÇÃO DOS SERVIÇOS NA JUCEPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,202032498 ,'2498','COORDENAÇÃO GERAL DA FAPEPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,202032461 ,'2461','CONCESSÃO DE BOLSAS DE MESTRADO, DOUTORADO E PÓS-DOUTORADO NO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,202032433 ,'2433','APOIO ÀS PESQUISAS CIENTÍFICAS, TECNOLÓGICAS E DE INOVAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20205,202052108 ,'2108','ADEQUAÇÃO E INFORMATIZAÇÃO DA BASE DE VERIFICAÇÃO METROLÓGICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20205,202052548 ,'2548','COORDENAÇÃO GERAL DO IMEPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20205,202052673 ,'2673','METROLOGIA LEGAL E AVALIAÇÃO DE CONFORMIDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20206,202062667 ,'2667','MANUTENÇÃO E IMPLEMENTAÇÃO DAS DEMAIS FASES DA ZPE PARNAÍBA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20206,202062585 ,'2585','FOMENTO E DIFUSÃO DA CULTURA EXPORTADORA NO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20207,202071572 ,'1572','FORTALECER A IMPLENTAÇÃO DOS TERMINAIS ALFANDEGADOS DO PIAUÍ - PORTO PI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,211012678 ,'2678','MODERNIZAÇÃO DA GESTÃO ADMINISTRATIVA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,211012184 ,'2184','AMPLIAÇÃO DOS ESPAÇOS DA CIDADANIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,211012125 ,'2125','ADMINISTRAÇÃO DA GESTÃO ¿ SECRETARIA DA ADMINISTRAÇÃO E PREVIDÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,211012718 ,'2718','QUALIFICAÇÃO E VALORIZAÇÃO DO SERVIDOR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,211012003 ,'2003','ACESSIBILIDADE ÀS PESSOAS COM DEFICIÊNCIA NOS ÓRGÃOS DO CENTRO ADMINISTRATIVO E DEMAIS PRÉDIOS PÚBLICOS PERTENCENTES AO ESTADO ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21102,211022610 ,'2610','FUNDO ROTATIVO DE MATERIAL E CONSERVAÇÃO DE PATRIMÔNIO DO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,212012587 ,'2587','FORTALECIMENTO ADMINISTRATIVO E MELHORIA DA INFRAESTRUTURA DO IASPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,212012681 ,'2681','MODERNIZAÇÃO DA GESTÃO DO IASPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,212012620 ,'2620','GESTÃO DO IASPI SAÚDE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,212012622 ,'2622','GESTÃO DO PLAMTA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21203,212031619 ,'1619','MODERNIZAÇÃO DA GESTÃO E DA INFRAESTRUTURA DA PREVIDÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21203,212031595 ,'1595','GESTÃO DO FUNDO DE PREVIDÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21203,212032460 ,'2460','CONCESSÃO DE BENEFÍCIOS PREVIDENCIÁRIOS AOS SERVIDORES DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,212041538 ,'1538','COORDENAÇÃO DA ATI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,212041614 ,'1614','MODERNIZAÇÃO ADMINISTRATIVA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,212041591 ,'1591','GERENCIAMENTO DOCUMENTAL E SISTEMAS DE INFORMAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,212041603 ,'1603','INCLUSÃO SOCIAL ATRAVÉS DA TECNOLOGIA DA INFORMAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,212041531 ,'1531','CENTRO DE PROCESSAMENTO E ARMAZENAMENTO DE DADOS (DATA CENTER)',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,212041645 ,'1645','REDE GOVERNO INFOVIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212051617 ,'1617','MODERNIZAÇÃO DA EMGERPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212052666 ,'2666','MANUTENÇÃO E GESTÃO DA EMGERPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212052728 ,'2728','REGULARIZAÇÃO FUNDIÁRIA URBANA DE EMPREENDIMENTOS HABITACIONAIS INCORPORADOS PELA EMGERPI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212052726 ,'2726','REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE INFRAESTRUTURA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212051648 ,'1648','REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE UNIDADES HABITACIONAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212051649 ,'1649','REGULARIZAÇÃO DA IMPLANTAÇÃO, REFORMA E AMPLIAÇÃO DE SISTEMAS DE ABASTECIMENTO DE ÁGUA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212051566 ,'1566','EXPLORAÇÃO DE JAZIDAS DE CALCÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,212051647 ,'1647','REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE ESTRADAS E VIAS  ASFÁLTICA, PARALELEPÍPEDO, POLIÉDRICA E VICINAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21206,212061639 ,'1639','PREVIDÊNCIA DOS SERVIDORES DO ESTADO DO PAIUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21207,212072744 ,'2744','MODERNIZAÇÃO DA GESTÃO E INFRAESTRUTURA DA FUNDAÇÃO PIAUÍ PREVIDÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21207,212072478 ,'2478','GESTÃO DA FUNDAÇÃO PIAUÍ PREVIDÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,221012607 ,'2607','FORTALECIMENTO INSTITUCIONAL DA SEJUS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,221012695 ,'2695','POLÍTICAS DE VALORIZAÇÃO DA SECRETARIA DE JUSTIÇA E DO SERVIDOR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,221012488 ,'2488','CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DO SISTEMA PENITENCIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,221012555 ,'2555','DESENVOLVIMENTO DE PROJETOS VOLTADOS A REMISSÃO DE PENAS E PROMOÇÃO DE CIDADANIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,221012708 ,'2708','PROMOÇÃO DE AÇÕES SOCIOECONÔMICAS E EDUCATIVAS AOS DETENTOS E AMPLA MODERNIZAÇÃO DOS ESTABELECIMENTOS PENITENCIÁRIOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22201,222012780 ,'2780','CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DO SISTEMA PENITENCIÁRIO DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (24101,241012564 ,'2564','ENCARGOS PATRONAIS E CONTRIBUTIVOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (24101,241012616 ,'2616','GESTÃO DA DÍVIDA PÚBLICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (24101,241012663 ,'2663','INVESTIMENTO EM PARTICIPAÇÕES SOCIETÁRIAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,251011631 ,'1631','PAGAMENTO DE PASSIVOS DE MEMBROS E SERVIDORES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,251011651 ,'1651','RENOVAÇÃO E OTIMIZAÇÃO DA ESTRUTURA ADMINISTRATIVA DO MINISTÉRIO PÚBLICO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,251011598 ,'1598','IMPLANTAÇÃO DE AÇÕES DE SEGURANÇA INSTITUCIONAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,251011519 ,'1519','APERFEIÇOAMENTO FUNCIONAL DE MEMBROS E SERVIDORES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25102,251021626 ,'1626','MODERNIZAÇÃO DO MINISTÉRIO PÚBLICO ESTADUAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25104,251041513 ,'1513','AÇÕES E SERVIÇOS DE PROTEÇÃO E DEFESA DOS DIREITOS DOS CONSUMIDORES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,261012732 ,'2732','RESTRUTURAÇÃO DAS INSTALAÇÕES FÍSICAS E AQUISIÇÃO DE EQUIPAMENTOS PARA POLÍCIA MILITAR DO PIAUÍ.',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,261012508 ,'2508','COORDENAÇÃO GERAL DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,261012683 ,'2683','MODERNIZAÇÃO DA GESTÃO DOS RECURSOS DA POLÍCIA MILITAR DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,261012565 ,'2565','ENFRENTAMENTO DAS DIVERSAS FORMAS DE VIOLÊNCIAS NO ESTADO DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,261012602 ,'2602','FORTALECIMENTO DE POLÍTICAS DE PREVENÇÃO À VIOLÊNCIA NO TRÂNSITO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26102,261022493 ,'2493','COORDENAÇÃO DO HOSPITAL DIRCEU ARCOVERDE DA PM-PI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26102,261022457 ,'2457','CAPACITAÇÃO TÉCNICA E VALORIZAÇÃO HUMANA DOS FUNCIONÁRIOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26102,261022444 ,'2444','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26103,261032542 ,'2542','COORDENAÇÃO GERAL DO 2º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26104,261042543 ,'2543','COORDENAÇÃO GERAL DO 3º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26105,261052544 ,'2544','COORDENAÇÃO GERAL DO 4º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26106,261062545 ,'2545','COORDENAÇÃO GERAL DO 7º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26107,261072494 ,'2494','COORDENAÇÃO GERAL DA ACADEMIA DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26108,261082539 ,'2539','COORDENAÇÃO GERAL DO 10º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26109,261092540 ,'2540','COORDENAÇÃO GERAL DO 11º BATALHÃO DA POLÍCIA MILITAR - SÃO RAIMUNDO NONATO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26110,261102541 ,'2541','COORDENAÇÃO GERAL DO 12º BATALHÃO DA POLÍCIA MILITAR - PIRIPIRI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26111,261111543 ,'1543','COORDENAÇÃO GERAL DO 14º BATALHÃO DA POLÍCIA MILITAR - OEIRAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26112,261121544 ,'1544','COORDENAÇÃO GERAL DO 15º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26113,261131545 ,'1545','COORDENAÇÃO GERAL DO BATALHÃO DA 5º COMPANHIA DA POLÍCIA MILITAR - PAULISTANA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26114,261141540 ,'1540','COORDENAÇÃO GERAL DA COMPANHIA INDEPENDENTE DE TURISMO - LUÍS CORREIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26115,261154005 ,'4005','COORDENAÇÃO GERAL DO 16º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26116,261164002 ,'4002','COORDENAÇÃO GERAL DO 18º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26117,261174003 ,'4003','COORDENAÇÃO GERAL DO 19º BATALHÃO DA POLÍCIA MILITAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012617 ,'2617','GESTÃO DA SECRETARIA ESTADUAL DE MEIO AMBIENTE E RECURSOS HÍDRICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012553 ,'2553','DESCENTRALIZAÇÃO E MODERNIZAÇÃO DA GESTÃO AMBIENTAL E DOS RECURSOS HÍDRICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012199 ,'2199','AMPLIAÇÃO, ESTRUTURAÇÃO E ADEQUAÇÃO DAS ÁREAS PROTEGIDAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012455 ,'2455','CADASTRAMENTO NO CADASTRO NACIONAL DE USUÁRIOS DE RECURSOS HÍDRICOS (CNARH)',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012570 ,'2570','ESTRUTURAÇÃO DO SISTEMA DE MONITORAMENTO E GESTÃO DA PROTEÇÃO AMBIENTAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012651 ,'2651','IMPLEMENTAÇÃO E GESTÃO DO PROGRAMA ESTADUAL DE EDUCAÇÃO AMBIENTAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012721 ,'2721','RECUPERAÇÃO DAS ÁREAS E ECOSSISTEMAS DEGRADADOS E COMBATE À DESERTIFICAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012650 ,'2650','IMPLEMENTAÇÃO E APERFEIÇOAMENTO DOS INSTRUMENTOS DE GESTÃO DE RECURSOS HÍDRICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,281012124 ,'2124','ADESÃO AO PROGRAMA DE ESTÍMULO DE DIVULGAÇÃO A QUALIDADE DA ÁGUA ¿ QUALIÁGUA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28102,281022774 ,'2774','ADMINISTRAÇÃO DA COORDENADORIA DE GESTÃO DE RECURSOS HÍDRICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28102,281022776 ,'2776','CONSTRUÇÃO DE ADUTORAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28102,281022778 ,'2778','IMPLANTAÇÃO DE SISTEMA DE ABASTECIMENTO DE ÁGUA E CONSTRUÇÃO DE ESTAÇÃO DE TRATAMENTO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28102,281022775 ,'2775','IMPLEMENTAÇÃO E APERFEIÇOAMENTO DOS INSTRUMENTOS DE GESTÃO DE RECURSOS HÍDRICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28102,281022777 ,'2777','CONSTRUÇÃO DE BARRAGENS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28102,281022779 ,'2779','CONSTRUÇÃO DE ESTAÇÃO DE PISCICULTURA ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,301011515 ,'1515','ADMINISTRAÇÃO GERAL DA SECRETARIA DA ASSISTÊNCIA SOCIAL E CIDADANIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,301012576 ,'2576','EXPANSÃO DAS AÇÕES DE INCLUSÃO PRODUTIVA ATRAVÉS DE PROJETOS DE ECONOMIA SOLIDÁRIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,301011602 ,'1602','IMPLEMENTAÇÃO DE AÇÕES DE CIDADANIA A FAMÍLIAS EM SITUAÇÃO DE VULNERABILIDADE SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,301012707 ,'2707','PROMOÇÃO DA SEGURANÇA ALIMENTAR',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,301012716 ,'2716','PROMOÇÃO E DEFESA DE DIREITOS HUMANOS, COM ÊNFASE NAS PESSOAS COM DIREITOS VIOLADOS OU EM SITUAÇÃO DE IMINENTE VIOLAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,301012595 ,'2595','FORTALECIMENTO DA GESTÃO E APRIMORAMENTO DAS INSTÂNCIAS DE PACTUAÇÃO E CONTROLE SOCIAL E DA REDE DE PROTEÇÃO SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,301022682 ,'2682','MODERNIZAÇÃO DA GESTÃO DO SISTEMA ÚNICO DA ASSISTÊNCIA SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,301022459 ,'2459','COFINANCIAMENTO DA PROTEÇÃO SOCIAL ESPECIAL POSSIBILITANDO SUA AMPLIAÇÃO, QUALIFICAÇÃO E MANUTENÇÃO DOS SERVIÇOS E ESTRUTURAÇÃO DA REDE DE PROTEÇÃO SOCIAL ESPECIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,301022714 ,'2714','PROMOÇÃO DOS DIREITOS DE CRIANÇAS E ADOLESCENTES POR MEIO DA PROTEÇÃO SOCIAL BÁSICA E ESPECIAL COM O OBJETIVO DE ENFRENTAR AS SITUAÇÕES DE VIOLÊNCIA, DE TRABALHO INFANTIL E EXPLORAÇÃO SEXUAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,301022633 ,'2633','IMPLANTAÇÃO DE SERVIÇOS DE CARÁTER REGIONAL OU DE UNIDADES REGIONAIS DE PROTEÇÃO SOCIAL ESPECIAL DE MÉDIA E ALTA COMPLEXIDADE, PODENDO TER COMO REFERÊNCIA A EXISTÊNCIA DE COMARCAS, AS MICRORREGIÕES E O MAPA DE RISCO SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,301022458 ,'2458','COFINANCIAMENTO DA PROTEÇÃO SOCIAL BÁSICA POSSIBILITANDO A AMPLIAÇÃO, QUALIFICAÇÃO E MANUTENÇÃO DOS SERVIÇOS SOCIOASSISTENCIAIS, PROGRAMAS, BENEFÍCIOS E PROJETOS NO ÂMBITO DO SUAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,301021522 ,'1522','APRIMORAMENTO DA GESTÃO DO CADASTRO ÚNICO E MONITORAMENTO DO PROGRAMA BOLSA FAMÍLIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30104,301041641 ,'1641','PROMOÇÃO DOS DIREITOS DAS CRIANÇAS E ADOLESCENTES MEDIANTE A PROTEÇÃO SOCIAL BÁSICA E ESPECIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30104,301042729 ,'2729','REORDENAMENTO DO ATENDIMENTO SOCIOEDUCATIVO DO ESTADO DO PIAUÍ, INCLUINDO A INFRAESTRUTURA FÍSICA, CONTRATAÇÃO E CAPACITAÇÃO DE RECURSOS HUMANOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30105,301052745 ,'2745','ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA MAIS VIDA COM CIDADANIA PARA O IDOSO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30105,301052795 ,'2795','PROMOÇÃO E DEFESA DE DIREITOS HUMANOS, COM ÊNFASE NOS IDOSOS COM DIREITOS VIOLADOS OU EM SITUAÇÃO DE IMINENTE VIOLAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (33101,331012139 ,'2139','ADMINISTRAÇÃO GERAL DE COMUNICAÇÃO SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (33101,331012675 ,'2675','MODERNIZAÇÃO DA COMUNICAÇÃO DAS AÇÕES DO GOVERNO À SOCIEDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,351012677 ,'2677','MODERNIZAÇÃO DA DEFENSORIA PÚBLICA DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,351012560 ,'2560','EFETIVAÇÃO DOS DIREITOS SOCIAIS E ASSISTÊNCIA A PESSOA COM DEFICIÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,351012715 ,'2715','PROMOÇÃO E ARTICULAÇÃO DE AÇÕES DE EDUCAÇÃO EM DIREITOS, PROTEÇÃO ÀS MULHERES E ENFRENTAMENTO ÀS DROGAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,351012497 ,'2497','COORDENAÇÃO GERAL DA DEFENSORIA PÚBLICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,351012572 ,'2572','ESTRUTURAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,351012450 ,'2450','ASSISTÊNCIA JURÍDICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35102,351021589 ,'1589','FUNDO DE MODERNIZAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (36101,361011621 ,'1621','MODERNIZAÇÃO DA PROCURADORIA GERAL DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (36101,361012491 ,'2491','COORDENAÇÃO DA PROCURADORIA GERAL DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (37101,371012676 ,'2676','MODERNIZAÇÃO DA CONTROLADORIA GERAL DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (37101,371012612 ,'2612','GESTÃO DA CONTROLADORIA GERAL DO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (37101,371012699 ,'2699','PREVENÇÃO E COMBATE À CORRUPÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,381012680 ,'2680','MODERNIZAÇÃO DA GESTÃO DA SEID',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,381012535 ,'2535','COORDENAÇÃO GERAL DA SEID',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,381012435 ,'2435','APOIO TEÉCNICO E FINANCEIRO ÀS ENTIDADES SEM FINS LUCRATIVOS QUE ATENDEM AS PESSOAS COM DEFICIÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38102,381022640 ,'2640','IMPLEMENTAÇÃO DA POLÍTICA DE ATENDIMENTO À PESSOA COM DEFICIÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (39000,390002731 ,'2731','RESERVA DE CONTINGÊNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (44101,441012481 ,'2481','CONSTRUÇÃO, MODERNIZAÇÃO E AMPLIAÇÃO DO SISTEMA OPERACIONAL E INTEGRAÇÃO BOMBEIRO E SOCIEDADE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (44101,441012546 ,'2546','COORDENAÇÃO GERAL DO CORPO DE BOMBEIROS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,451012293 ,'2293','APOIAR OS MUNÍCIPIOS NA IMPLEMENTAÇÃO DE OBRAS URBANAS DE AMPLA RELEVÂNCIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,451012590 ,'2590','FORTALECIMENTO DA COORDENAÇÃO GERAL DA SECID',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,451012636 ,'2636','IMPLANTAÇÃO E EXECUÇÃO DE PAVIMENTAÇÃO COM PARALELEPÍPEDO, ESTRADA VICINAL E PAVIMENTAÇÃO ASFÁLTICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,451011557 ,'1557','ELABORAÇÃO E EXECUÇÃO DE PROJETOS DE HABITAÇÃO DE INTERESSE SOCIAL EM ÁREAS URBANAS E RURAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,451012734 ,'2734','SANEAMENTO BÁSICO NOS MUNICÍPIOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,451012634 ,'2634','IMPLANTAÇÃO DE SISTEMA ADUTOR E OUTRAS OBRAS HÍDRICAS, EM ÁREAS URBANAS E RURAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,451012644 ,'2644','IMPLEMENTAÇÃO DE INTERVENÇÕES NA ÁREA DE RESÍDUOS SÓLIDOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45201,452011615 ,'1615','MODERNIZAÇÃO ADMINISTRATIVA DO DETRAN',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45201,452011612 ,'1612','MELHORIA NO TRÂNSITO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45201,452011546 ,'1546','COORDENAÇÃO GERAL DO DETRAN',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022495 ,'2495','COORDENAÇÃO GERAL DA ADH',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022474 ,'2474','CONSTRUÇÃO DE UNIDADES HABITACIONAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022609 ,'2609','FUNDO ESTADUAL DE INTERESSE SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022453 ,'2453','AUTOFINANCIAMENTO HABITACIONAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022103 ,'2103','ACOMPANHAMENTO DO TRABALHO TÉCNICO SOCIAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022628 ,'2628','HABITAÇÃO PARA SERVIDORES PÚBLICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022672 ,'2672','MELHORIA HABITACIONAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022727 ,'2727','REGULARIZAÇÃO E AVERBAÇÃO FUNDIÁRIA HABITACIONAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,452022741 ,'2741','URBANIZAÇÃO E CONSTRUÇÃO DE EQUIPAMENTOS SOCIAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45203,452032621 ,'2621','GESTÃO DO INSTITUTO DE ÁGUAS E ESGOTOS DO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45203,452032563 ,'2563','ELABORAÇÃO E IMPLEMENTAÇÃO DE PROJETOS E ATIVIDADES DE ABASTECIMENTO DE ÁGUA POTÁVEL E ESGOTAMENTO SANITÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45203,452032619 ,'2619','GESTÃO DE RESÍDUOS SÓLIDOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012627 ,'2627','GESTÃO MODERNA DA SECRETARIA DOS TRANSPORTES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012656 ,'2656','INFRAESTRUTURA DO MODAL AEROVIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012469 ,'2469','CONSTRUÇÃO DA RODOVIA TRANSCERRADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012473 ,'2473','CONSTRUÇÃO DE RODOANEIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012660 ,'2660','INFRAESTRUTURA DO MODAL RODOVIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012490 ,'2490','CONTROLE E OPERAÇÃO DE TRÁFEGO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012635 ,'2635','IMPLANTAÇÃO DO METRÔ DE TERESINA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012657 ,'2657','INFRAESTRUTURA DO MODAL FERROVIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012659 ,'2659','INFRAESTRUTURA DO MODAL PORTUÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,461012658 ,'2658','INFRAESTRUTURA DO MODAL HIDROVIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46102,461022773 ,'2773','GESTÃO MODERNA DA COORDENADORIA DE INFRAESTRUTURA AEROPORTUÁRIA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46102,461022772 ,'2772','INFRAESTRUTURA DO MODAL AEROVIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46201,462011514 ,'1514','ADMINISTRAÇÃO EFICIENTE DO DER-PI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46201,462011620 ,'1620','MODERNIZAÇÃO DA OPERACIONALIDADE DO DER-PI',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46201,462011553 ,'1553','DESENVOLVIMENTO E OPERACIONALIDADE DA INFRAESTRUTURA RODOVIÁRIA E MOBILIDADE URBANA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,462022730 ,'2730','REQUALIFICAÇÃO FÍSICA E DE RECURSOS HUMANOS DA COMPANHIA METROPOLITANA DE TRANSPORTES PÚBLICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,462022496 ,'2496','COORDENAÇÃO GERAL DA CMTP',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,462022204 ,'2204','AMPLIAÇÃO, MELHORIA E MANUTENÇÃO DO SISTEMA METROVIÁRIO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,462022743 ,'2743','VLT TERESINA - TIMON',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,462022664 ,'2664','LINHA ALTOS - PARNAÍBA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,471011541 ,'1541','COORDENAÇÃO GERAL DA SECRETARIA DE TURISMO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,471011579 ,'1579','FORTALECIMENTO DA GESTÃO MUNICIPAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,471011587 ,'1587','FORTALECIMENTO DO TURISMO SUSTENTÁVEL NO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,471011606 ,'1606','INFRAESTRUTURA TURÍSTICA E MELHORIA DOS SERVIÇOS TURÍSTICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,471011578 ,'1578','FORTALECIMENTO DA GESTÃO INSTITUCIONAL PARA O TURISMO / PRODETUR NACIONAL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,481011597 ,'1597','GESTÃO, MANUTENÇÃO E AMPLIAÇÃO DA SETRE E SINE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,481011630 ,'1630','MONITORAMENTO E AVALIAÇÃO DE POLÍTICAS PÚBLICAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,481011552 ,'1552','DESENVOLVIMENTO EMPRESARIAL E INCENTIVO AO EMPREENDEDORISMO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,481011608 ,'1608','INTERMEDIAÇÃO DE MÃO DE OBRA /SINE',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,481011642 ,'1642','PROTEÇÃO SOCIAL BÁSICA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,481011643 ,'1643','QUALIFICAÇÃO SOCIAL, PROFISSIONAL E EMPREENDEDORA / INTERMEDIAÇÃO DE MÃO DE OBRA COM CAPACITAÇÃO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,481011567 ,'1567','FOMENTO AO EMPREENDEDORISMO JOVEM NO SEMIÁRIDO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48103,481032756 ,'2756','AMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DE MODERNIZAÇÃO E QUALIFICAÇÃO DOS EMPREENDIMENTOS PÚBLICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48103,481032757 ,'2757','DESENVOLVIMENTO EMPRESARIAL E INCENTIVO AO EMPREENDEDORISMO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48103,481032758 ,'2758','MONITORAMENTO E AVALIAÇÃO DE POLÍTICAS PÚBLICAS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,491012532 ,'2532','COORDENAÇÃO GERAL DA SECRETARIA DE DEFESA CIVIL',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,491012070 ,'2070','AÇÕES DE PREVENÇÃO DE DESASTRES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,491012722 ,'2722','RECUPERAÇÃO DOS DANOS CAUSADOS POR DESASTRES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,491012476 ,'2476','CONSTRUÇÃO E RECUPERAÇÃO DE OBRAS ESTRUTURANTES RELACIONADAS A FENÔMENOS CLIMÁTICOS E DESASTRES',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,501012626 ,'2626','GESTÃO GERAL DA SEMINPER',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,501012462 ,'2462','CONSOLIDAÇÃO DA BASE DE DADOS DA MINERAÇÃO NO PIAUÍ',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,501012710 ,'2710','PROMOÇÃO DE NEGÓCIOS MINERAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,501012709 ,'2709','PROMOÇÃO DE NEGÓCIOS ENERGÉTICOS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50201,502012558 ,'2558','DISTRIBUIÇÃO DE GÁS NATURAL ATRAVÉS DO GASODUTO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,511012531 ,'2531','COORDENAÇÃO GERAL DA SECRETARIA DA CULTURA',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,511012717 ,'2717','PROTEÇÃO E PRESERVAÇÃO DOS BENS CULTURAIS E CONHECIMENTOS DOS POVOS E COMUNIDADES TRADICIONAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,511012684 ,'2684','MODERNIZAÇÃO DA INFRAESTRUTURA E QUALIFICAÇÃO DOS GESTORES E AGENTES CULTURAIS',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,511012605 ,'2605','FORTALECIMENTO E AMPLIAÇÃO DO PROGRAMA CULTURA VIVA NO ESTADO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,511012719 ,'2719','REALIZAÇÃO E APOIO A EVENTOS CULTURAIS NOS TERRITÓRIOS DE DESENVOLVIMENTO',true);
INSERT INTO acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,511012582 ,'2582','FOMENTO À CRIAÇÃO E A PRODUÇÃO DE BENS ARTÍSTICOS E CULTURAIS DAS DIVERSAS LINGUAGENS',true);