insert into acaoestrategica (id, nome, orgao_id, ativo) values(2746,'MANUTENÇÃO E REESTRUTURAÇÃO DAS UNIDADES DE SEGURANÇA',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2747,'ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVAÇÃO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2748,'FUNDO ESPECIAL DE CRÉDITOS INADIMPLIDOS E DÍVIDA ATIVA -FECIDAPI',13,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2749,'COORDENAÇÃO DA DELEGACIA GERAL DA POLÍCIA CIVIL',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2750,'GESTÃO DA FUNDAÇÃO PIAUÍ PREVIDÊNCIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2751,'COORDENAÇÃO DA DELEGACIA GERAL DA POLÍCIA CIVIL',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2752,'MODERNIZAÇÃO DA GESTÃO E INFRAESTRUTURA DA FUNDAÇÃO PIAUÍ PREVIDÊNCIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2753,'ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVAÇÃO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2756,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE SANTA FILOMENA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2757,'PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS - TERRITÓRIO ENTRE RIOS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2758,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA REGIONAL DE SAÚDE - URUÇUÍ',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2759,'MODERNIZAÇÃO DA GESTÃO E INFRAESTRUTURA DA FUNDAÇÃO PIAUÍ PREVIDÊNCIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2761,'ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVAÇÃO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2762,'COORDENAÇÃO DA DELEGACIA GERAL DA POLÍCIA CIVIL',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1520,'APOIO ADMINISTRATIVO FERMOJUPI',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1545,'COORDENAÇÃO GERAL DO BATALHÃO DA 5º COMPANHIA DA POLÍCIA MILITAR - PAULISTANA',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2125,'ADMINISTRAÇÃO DA GESTÃO SECRETARIA DA ADMINISTRAÇÃO E PREVIDÊNCIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2257,'APERFEIÇOAMENTO DA PRESTAÇÃO JURISDICIONAL',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2328,'APOIO ADMINISTRATIVO CORREGEDORIA GERAL DE JUSTIÇA',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2763,'COORDENAÇÃO DO HOSPITAL DIRCEU ARCOVERDE DA PM-PI',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2538,'COORDENAÇÃO GERAL DA SURPI BSB',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2654,'INFRAESTRUTURAÇÃO DO TCE E EDUCAÇÃO CONTINUADA DOS SERVIDORES',02,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1513,'AÇÕES E SERVIÇOS DE PROTEÇÃO E DEFESA DOS DIREITOS DOS CONSUMIDORES',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1514,'ADMINISTRAÇÃO EFICIENTE DO DER-PI',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1515,'ADMINISTRAÇÃO GERAL DA SECRETARIA DA ASSISTÊNCIA SOCIAL E CIDADANIA',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1516,'ÁGUA PARA TODOS',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1517,'AMPLIAÇÃO DA ADESÃO AO PROGRAMA GARANTIA SAFRA',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1518,'AMPLIAÇÃO E DIVERSIFICAÇÃO DA OFERTA DE EXAMES LABORATORIAIS ESPECIALIZADOS DE SAÚDE PÚBLICA, DE MÉDIA E ALTA COMPLEXIDADE NO ÂMBITO DO SUS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1519,'APERFEIÇOAMENTO FUNCIONAL DE MEMBROS E SERVIDORES',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1521,'APOIO TÉCNICO AOS MUNICÍPIOS PARA GARANTIR A INTEGRALIDADE DA ATENÇÃO À SAÚDE NOS MUNICÍPIOS DA SUA ÁREA DE ABRANGÊNCIA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1522,'APRIMORAMENTO DA GESTÃO DO CADASTRO ÚNICO E MONITORAMENTO DO PROGRAMA BOLSA FAMÍLIA',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1523,'APROVEITAMENTO DAS POTENCIALIDADES AGROENERGÉTICAS DO ESTADO',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1524,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO CHAPADA DAS MANGABEIRAS - CORRENTE',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1525,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE INTEGRADA DO MOCAMBINHO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1526,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DOS COCAIS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1527,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA CHAPADA DAS MANGABEIRAS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1528,'ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA PLANÍCIE LITORÂNEA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1529,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DOS CARNAUBAIS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1530,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO SERRA DA CAPIVARA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1531,'CENTRO DE PROCESSAMENTO E ARMAZENAMENTO DE DADOS (DATA CENTER)',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1532,'CIDADANIA INCLUSIVA: JUVENTUDE, ESPORTE E LAZER',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1533,'CONSTRUÇÃO DE ADUTORAS',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1534,'CONSTRUÇÃO DE BARRAGENS',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1535,'CONSTRUÇÃO DE ESTAÇÃO DE PISCICULTURA',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1536,'CONSTRUÇÃO DE MACRODRENAGEM',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1537,'CONTRATAÇÃO DE CONSULTORIA EM OBRAS',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1538,'COORDENAÇÃO DA ATI',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1539,'COORDENAÇÃO DO INTERPI',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1540,'COORDENAÇÃO GERAL DA COMPANHIA INDEPENDENTE DE TURISMO - LUÍS CORREIA',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1541,'COORDENAÇÃO GERAL DA SECRETARIA DE TURISMO',47,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1542,'COORDENAÇÃO GERAL DA SEDET',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1543,'COORDENAÇÃO GERAL DO 14º BATALHÃO DA POLÍCIA MILITAR - OEIRAS',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1544,'COORDENAÇÃO GERAL DO 15º BATALHÃO DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1546,'COORDENAÇÃO GERAL DO DETRAN',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1547,'COORDENAÇÃO GERAL DO GABINETE MILITAR',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1548,'COORDENAÇÃO GERAL DO IDEPI',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1549,'CRIAÇÃO E ATUALIZAÇÃO DO MARCO LEGAL DO SISTEMA ESTADUAL DE CULTURA',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1550,'DEFESA DA ORDEM JURÍDICA, DO REGIME DEMOCRÁTICO E DOS INTERESSES SOCIAIS E INDIVIDUAIS INDISPONÍVEIS',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1551,'DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE SÃO RAIMUNDO NONATO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1552,'DESENVOLVIMENTO EMPRESARIAL E INCENTIVO AO EMPREENDEDORISMO',48,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1553,'DESENVOLVIMENTO E OPERACIONALIDADE DA INFRAESTRUTURA RODOVIÁRIA E MOBILIDADE URBANA',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1554,'EDUCAÇÃO, CIDADANIA E DESENVOLVIMENTO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1555,'EDUCAÇÃO CONTEXTUALIZADA NA REGIÃO DO SEMIÁRIDO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1556,'ELABORAÇÃO DE ESTUDOS E PROJETOS BÁSICOS',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1557,'ELABORAÇÃO E EXECUÇÃO DE PROJETOS DE HABITAÇÃO DE INTERESSE SOCIAL EM ÁREAS URBANAS E RURAIS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1558,'EMPREENDA JOVEM',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1559,'EMPREENDER PARA CRESCER',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1560,'ENFRENTAMENTO ÀS DIVERSAS FORMAS DE VIOLÊNCIA, AO CRACK E OUTRAS DROGAS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1561,'ESTRUTURAÇÃO E FORTALECIMENTO DAS AÇÕES DO GRUPO DE ATUAÇÃO ESPECIAL DE COMBATE AO CRIME ORGANIZADO (GAECO)',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1562,'ESTRUTURAÇÃO E MODERNIZAÇÃO DA DEFESA AGROPECUÁRIA DO ESTADO DO PIAUÍ',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1563,'ESTUDO, PESQUISA, ELABORAÇÃO, EXECUÇÃO E ACOMPANHAMENTO DE ESTUDOS E PROJETOS DE OBRAS',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1564,'EXECUÇÃO DO PROGRAMA NACIONAL DO CRÉDITO FUNDIÁRIO',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1565,'EXECUÇÃO, EM PARCERIA COM O GOVERNO FEDERAL, DAS AÇÕES PREVISTAS NO PLANO DE DESENVOLVIMENTO AGROPECUÁRIO DO MATOPIBA',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1566,'EXPLORAÇÃO DE JAZIDAS DE CALCÁRIO',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1567,'FOMENTO AO EMPREENDEDORISMO JOVEM NO SEMIÁRIDO',48,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1568,'FOMENTO AOS ROTEIROS E IMAGENS TURÍSTICAS DO ESTADO / PRODETUR NACIONAL',47,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1569,'FOMENTO AOS SISTEMAS DE PRODUÇÃO FAMILIAR',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1570,'FOMENTO DAS AÇÕES E SERVIÇOS MEDIANTE CONVÊNIOS E CONTRATOS DE REPASSES COM MUNICIPIOS, M.SAÚDE, CEF E OUTROS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1572,'FORTALECER A IMPLENTAÇÃO DOS TERMINAIS ALFANDEGADOS DO PIAUÍ - PORTO PI',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1573,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE BOM JESUS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1574,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE FLORIANO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1575,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PICOS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1576,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE TERESINA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1577,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE VALENÇA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1578,'FORTALECIMENTO DA GESTÃO INSTITUCIONAL PARA O TURISMO / PRODETUR NACIONAL',47,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1579,'FORTALECIMENTO DA GESTÃO MUNICIPAL',47,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1580,'FORTALECIMENTO DA INFRAESTRUTURA DA AGRICULTURA FAMILIAR IRRIGADA NO ESTADO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1581,'FORTALECIMENTO DA INFRAESTRUTURA DE IRRIGAÇÃO NO SEMIÁRIDO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1582,'FORTALECIMENTO DAS ORGANIZAÇÕES SOCIAIS E ARTICULAÇÃO DAS INSTITUIÇÕES GOVERNAMENTAIS E NÃO GOVERNAMENTAIS',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1583,'FORTALECIMENTO DO COMÉRCIO E SERVIÇO DO ESTADO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1584,'FORTALECIMENTO DO CONSELHO ESTADUAL DE DIREITOS DA JUVENTUDE',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1585,'FORTALECIMENTO DOS ARRANJOS PRODUTIVOS AGROPECUÁRIOS E DA SOCIOBIODIVERSIDADE',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1586,'FORTALECIMENTO DOS ARRANJOS PRODUTIVOS LOCAIS POR MEIO DO FOMENTO À PRODUÇÃO AGROPECUÁRIA.',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1587,'FORTALECIMENTO DO TURISMO SUSTENTÁVEL NO PIAUÍ',47,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1588,'FORTALECIMENTO E AMPLIAÇÃO DA IRRIGAÇÃO VOLTADA AO AGRONEGÓCIO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1589,'FUNDO DE MODERNIZAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA',35,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1590,'GERAÇÃO DE EMPREGO E RENDA - PROGERE II',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1591,'GERENCIAMENTO DOCUMENTAL E SISTEMAS DE INFORMAÇÃO',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1592,'GESTÃO DA COORDENADORIA DE ENFRENTAMENTO ÀS DROGAS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1593,'GESTÃO DAS TERRAS PÚBLICAS ESTADUAIS',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1594,'GESTÃO DA VICE-GOVERNADORIA',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1595,'GESTÃO DO FUNDO DE PREVIDÊNCIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1596,'GESTÃO E MANUTENÇÃO DA COORDENADORIA ESTADUAL DA JUVENTUDE',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1597,'GESTÃO, MANUTENÇÃO E AMPLIAÇÃO DA SETRE E SINE',48,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1598,'IMPLANTAÇÃO DE AÇÕES DE SEGURANÇA INSTITUCIONAL',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1599,'IMPLANTAÇÃO DE SISTEMA DE ABASTECIMENTO DE ÁGUA E CONSTRUÇÃO DE ESTAÇÃO DE TRATAMENTO',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1600,'IMPLANTAÇÃO DO PLANO AGRICULTURA DE BAIXO CARBONO (PLANO ABC)',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1601,'IMPLANTAÇÃO DO SISTEMA DE FIBRA ÓTICA NAS ESCOLAS DA REDE ESTADUAL',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1602,'IMPLEMENTAÇÃO DE AÇÕES DE CIDADANIA A FAMÍLIAS EM SITUAÇÃO DE VULNERABILIDADE SOCIAL',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1603,'INCLUSÃO SOCIAL ATRAVÉS DA TECNOLOGIA DA INFORMAÇÃO',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1604,'INFRAESTRUTURA DE OBRAS, TRANSPORTE E TURISMO',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1605,'INFRAESTRUTURA HÍDRICA',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1606,'INFRAESTRUTURA TURÍSTICA E MELHORIA DOS SERVIÇOS TURÍSTICOS',47,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1607,'INTERAÇÃO SOCIAL E TRANSPARÊNCIA',37,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1608,'INTERMEDIAÇÃO DE MÃO DE OBRA /SINE',48,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1609,'JUVENTUDE E CULTURA VIVA',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1610,'MANUTENÇÃO E CONSERVAÇÃO DE BARRAGENS',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1611,'MELHORIA DA INFRAESTRUTURA DA JUNTA COMERCIAL',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1612,'MELHORIA NO TRÂNSITO',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1613,'MINHA CASA MINHA VIDA RURAL - PNHR',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1614,'MODERNIZAÇÃO ADMINISTRATIVA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1615,'MODERNIZAÇÃO ADMINISTRATIVA DO DETRAN',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1616,'MODERNIZAÇÃO DA COORDENADORIA ESTADUAL DA JUVENTUDE',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1617,'MODERNIZAÇÃO DA EMGERPI',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1618,'MODERNIZAÇÃO DA GESTÃO',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1619,'MODERNIZAÇÃO DA GESTÃO E DA INFRAESTRUTURA DA PREVIDÊNCIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1620,'MODERNIZAÇÃO DA OPERACIONALIDADE DO DER-PI',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1621,'MODERNIZAÇÃO DA PROCURADORIA GERAL DO ESTADO',36,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1622,'MODERNIZAÇÃO DA SECRETARIA DO DESENVOLVIMENTO ECONÔMICO E TECNOLÓGICO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1623,'MODERNIZAÇÃO DA SECRETARIA DO DESENVOLVIMENTO RURAL (SDR)',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1624,'MODERNIZAÇÃO DA SECRETARIA DO TURISMO',47,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1625,'MODERNIZAÇÃO DO EMATER',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1626,'MODERNIZAÇÃO DO MINISTÉRIO PÚBLICO ESTADUAL',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1627,'MODERNIZAÇÃO E APERFEIÇOAMENTO DA GESTÃO ADMINISTRATIVA',13,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1628,'MODERNIZAÇÃO E APRIMORAMENTO DA GESTÃO DA SASC',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1629,'MONITORAMENTO E AVALIAÇÃO DE POLÍTICAS PÚBLICAS',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1631,'PAGAMENTO DE PASSIVOS DE MEMBROS E SERVIDORES',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1632,'PAVIMENTAÇÃO ASFÁLTICA',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1633,'PAVIMENTAÇÃO EM PARALELEPÍPEDO',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1634,'PLANEJA PIAUÍ',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1635,'POTENCIALIZAÇÃO DOS MERCADOS INSTITUCIONAIS EXISTENTES E VIABILIZAÇÃO DE NOVAS OPORTUNIDADES DE COMERCIALIZAÇÃO DOS PRODUTOS DA AGRICULTURA FAMILIAR',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1636,'PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DO VALE DO RIO GUARIBAS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1637,'PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO VALE DOS RIOS PIAUÍ E ITAUEIRA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1638,'PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO VALE DO CANINDÉ',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1639,'PREVIDÊNCIA DOS SERVIDORES DO ESTADO DO PAIUÍ',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1640,'PROJETO REDESIM/DESCONCENTRAÇÃO DOS SERVIÇOS',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1641,'PROMOÇÃO DOS DIREITOS DAS CRIANÇAS E ADOLESCENTES MEDIANTE A PROTEÇÃO SOCIAL BÁSICA E ESPECIAL',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1642,'PROTEÇÃO SOCIAL BÁSICA',48,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1643,'QUALIFICAÇÃO SOCIAL, PROFISSIONAL E EMPREENDEDORA / INTERMEDIAÇÃO DE MÃO DE OBRA COM CAPACITAÇÃO',48,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1644,'RECUPERAÇÃO E REFORMA DE ESTRADAS VICINAIS',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1645,'REDE GOVERNO INFOVIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1646,'REESTRUTURAÇÃO ORGANIZACIONAL E DE PROCESSOS',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1647,'REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE ESTRADAS E VIAS ASFÁLTICA, PARALELEPÍPEDO, POLIÉDRICA E VICINAL',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1648,'REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE UNIDADES HABITACIONAIS',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1649,'REGULARIZAÇÃO DA IMPLANTAÇÃO, REFORMA E AMPLIAÇÃO DE SISTEMAS DE ABASTECIMENTO DE ÁGUA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1650,'REGULARIZAÇÃO FUNDIÁRIA EM ÁREAS URBANAS NO ESTADO DO PIAUÍ',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1651,'RENOVAÇÃO E OTIMIZAÇÃO DA ESTRUTURA ADMINISTRATIVA DO MINISTÉRIO PÚBLICO',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1652,'SANEAMENTO BASICO AMBIENTAL',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(1653,'VIVA O SEMIÁRIDO',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2003,'ACESSIBILIDADE ÀS PESSOAS COM DEFICIÊNCIA NOS ÓRGÃOS DA REDE ESTADUAL',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2034,'ACESSO UNIVERSALIZADO A BENS E EQUIPAMENTOS CULTURAIS',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2040,'AÇÕES DE ATENÇÃO À SAÚDE DA PESSOA COM DEFICIÊNCIA',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2070,'AÇÕES DE PREVENÇÃO DE DESASTRES',49,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2103,'ACOMPANHAMENTO DO TRABALHO TÉCNICO SOCIAL',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2106,'ACOMPANHAMENTO E ASSESSORAMENTO DAS AÇÕES GOVERNAMENTAIS NAS ESFERAS MUNICIPAL , ESTADUAL E FEDERAL',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2107,'ACOMPANHAMENTO ESTRATÉGICO E DESENVOLVIMENTO SOCIOECONÔMICO',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2108,'ADEQUAÇÃO E INFORMATIZAÇÃO DA BASE DE VERIFICAÇÃO METROLÓGICA',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2124,'ADESÃO AO PROGRAMA DE ESTÍMULO DE DIVULGAÇÃO A QUALIDADE DA ÁGUA QUALIÁGUA',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2127,'ADMINISTRAÇÃO GERAL DA COORDENADORIA ESTADUAL DE POLÍTICAS PARA AS MULHERES',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2134,'ADMINISTRAÇÃO GERAL DA FUNDAÇÃO ANTARES',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2139,'ADMINISTRAÇÃO GERAL DE COMUNICAÇÃO SOCIAL',33,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2142,'AMPLIAÇÃO DA COLETA E TRATAMENTO DE ESGOTO SANITÁRIO',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2143,'AMPLIAÇÃO DA ESTRUTURA DA TV E RÁDIO ASSEMBLEIA',01,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2157,'AMPLIAÇÃO DAS ESTRUTURAS DE SEGURANÇA PÚBLICA DO ESTADO',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2177,'AMPLIAÇÃO DO ACESSO A POLÍTICAS DE ENFRENTAMENTO ÀS DROGAS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2184,'AMPLIAÇÃO DOS ESPAÇOS DA CIDADANIA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2188,'AMPLIAÇÃO E DIVERSIFICAÇÃO DA OFERTA DE CONSULTAS, EXAMES LABORATORIAIS E PROCEDIMENTOS ESPECIALIZADOS DE SAÚDE, DE MÉDIA E ALTA COMPLEXIDADE, NO ÂMBITO DOS SERVIÇOS PÚBLICOS DE REFERÊNCIA REGIONAL E ESTADUAL DO SUS-PI',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2196,'AMPLIAÇÃO E MODERNIZAÇÃO DA REDE HIDROMETEOROLÓGICA DO ESTADO',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2199,'AMPLIAÇÃO, ESTRUTURAÇÃO E ADEQUAÇÃO DAS ÁREAS PROTEGIDAS',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2204,'AMPLIAÇÃO, MELHORIA E MANUTENÇÃO DO SISTEMA METROVIÁRIO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2264,'APERFEIÇOAMENTO DO SISTEMA DE INTELIGÊNCIA E POTENCIALIZAÇÃO DO PARQUE TECNOLÓGICO E POLÍCIA TÉCNICO-CIENTÍFICA DA SEGURANÇA PÚBLICA',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2276,'APLICAÇÃO DOS RECURSOS DO FUNDEB',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2293,'APOIAR OS MUNÍCIPIOS NA IMPLEMENTAÇÃO DE OBRAS URBANAS DE AMPLA RELEVÂNCIA',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2294,'APOIO, ACOMPANHAMENTO E MONITORAMENTO À IMPLEMENTAÇÃO DE POLÍTICAS PÚBLICAS DIRECIONADAS PARA A GARANTIA DOS DIREITOS DAS MULHERES.',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2327,'APOIO ADMINISTRATIVO À COORDENAÇÃO GERAL DA SECRETARIA DE GOVERNO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2332,'APOIO ADMINISTRATIVO TRIBUNAL DE JUSTIÇA',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2344,'APOIO A EVENTOS ESPORTIVOS, FORMAÇÃO, QUALIFICAÇÃO E FOMENTO À PARTICIPAÇÃO DE ATLETAS EM EVENTOS ESPORTIVOS',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2391,'APOIO A IMIGRANTES PIAUIENSES EM VULNERABILIDADE SOCIAL',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2415,'APOIO AO DESENVOLVIMENTO DE ENERGIAS RENOVÁVEIS',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2416,'APOIO AO FUNDO ESPECIAL DE PRODUCÃO',13,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2417,'APOIO AO FUNDO GARANTIDOR DOS MICRO E PEQUENOS EMPREENDIMENTOS DO ESTADO DO PIAUÍ',13,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2418,'APOIO A PESQUISAS E ESTRATÉGIAS PARA O DESENVOLVIMENTO SUSTENTÁVEL E A BIODIVERSIDADE NO ESTADO DO PIAUÍ',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2429,'APOIO A PROGRAMAS DE TECNOLOGIA SOCIAL',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2432,'APOIO ÀS INICIATIVAS DE DESENVOLVIMENTO E INOVAÇÃO TECNOLÓGICA',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2433,'APOIO ÀS PESQUISAS CIENTÍFICAS, TECNOLÓGICAS E DE INOVAÇÃO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2434,'APOIO, CONTROLE E FISCALIZAÇÃO JUDICIAL E EXTRAJUDICIAL',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2435,'APOIO TEÉCNICO E FINANCEIRO ÀS ENTIDADES SEM FINS LUCRATIVOS QUE ATENDEM AS PESSOAS COM DEFICIÊNCIA',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2436,'AQUISIÇÃO DE MATERIAL BÉLICO, EQUIPAMENTO DE PROTEÇÃO INDIVIDUAL, MATERIAL DE INFORMÁTICA E TELEMÁTICA E VEÍCULOS AUTOMOTORES, AÉREOS E MARÍTIMOS',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2437,'ASSISTÊNCIA HEMATOLÓGICA E HEMOTERÁPICA DE QUALIDADE À POPULAÇÃO DOS 224 MUNICÍPIOS DO ESTADO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2438,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2439,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DE ESPERANTINA REFERENCIADA PELO SUS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2440,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO VALE DO SAMBITO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2441,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO N0 TERRITORIO VALE DO CANINDÉ',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2442,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO NO TERRITÓRIO SERRA DA CAPIVARA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2443,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE A PACIENTES COM TRANSTORNO MENTAL',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2444,'ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2447,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO MATERNA E RÉCEM NASCIDOS, REFERENCIADA DO SUS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2448,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE PARA A POPULAÇÃO INFANTIL DO ESTADO DO PIAUÍ',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2449,'ASSISTÊNCIA HOSPITALAR E AMBULATORIAL ESPECIALIZADA NA ÁREA DE DOENÇAS INFECCIOSAS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2450,'ASSISTÊNCIA JURÍDICA',35,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2451,'ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2452,'ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL NO SEMIÁRIDO PIAUIENSE',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2453,'AUTOFINANCIAMENTO HABITACIONAL',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2454,'AVALIAÇÃO DOS INDICADORES EDUCACIONAIS DA REDE ESTADUAL DE ENSINO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2455,'CADASTRAMENTO NO CADASTRO NACIONAL DE USUÁRIOS DE RECURSOS HÍDRICOS (CNARH)',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2456,'CAPACITAÇÃO E QUALIFICAÇÃO DAS EQUIPES TÉCNICAS MULTIDISCIPLINARES QUE ATUAM NO ENFRENTAMENTO ÀS DROGRAS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2457,'CAPACITAÇÃO TÉCNICA E VALORIZAÇÃO HUMANA DOS FUNCIONÁRIOS',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2458,'COFINANCIAMENTO DA PROTEÇÃO SOCIAL BÁSICA POSSIBILITANDO A AMPLIAÇÃO, QUALIFICAÇÃO E MANUTENÇÃO DOS SERVIÇOS SOCIOASSISTENCIAIS, PROGRAMAS, BENEFÍCIOS E PROJETOS NO ÂMBITO DO SUAS',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2459,'COFINANCIAMENTO DA PROTEÇÃO SOCIAL ESPECIAL POSSIBILITANDO SUA AMPLIAÇÃO, QUALIFICAÇÃO E MANUTENÇÃO DOS SERVIÇOS E ESTRUTURAÇÃO DA REDE DE PROTEÇÃO SOCIAL ESPECIAL',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2460,'CONCESSÃO DE BENEFÍCIOS PREVIDENCIÁRIOS AOS SERVIDORES DO ESTADO',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2461,'CONCESSÃO DE BOLSAS DE MESTRADO, DOUTORADO E PÓS-DOUTORADO NO ESTADO DO PIAUÍ',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2462,'CONSOLIDAÇÃO DA BASE DE DADOS DA MINERAÇÃO NO PIAUÍ',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2463,'CONSOLIDAÇÃO DA BASE DE DADOS DO SETOR ENERGÉTICO NO PIAUÍ',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2464,'CONSOLIDAÇÃO DA BASE LEGAL DE SUPORTE AOS NEGÓCIOS ENERGÉTICOS',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2465,'CONSOLIDAÇÃO DA BASE LEGAL DE SUPORTE AOS NEGÓCIOS MINERAIS',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2469,'CONSTRUÇÃO DA RODOVIA TRANSCERRADO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2473,'CONSTRUÇÃO DE RODOANEIS',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2474,'CONSTRUÇÃO DE UNIDADES HABITACIONAIS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2476,'CONSTRUÇÃO E RECUPERAÇÃO DE OBRAS ESTRUTURANTES RELACIONADAS A FENÔMENOS CLIMÁTICOS E DESASTRES',49,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2481,'CONSTRUÇÃO, MODERNIZAÇÃO E AMPLIAÇÃO DO SISTEMA OPERACIONAL E INTEGRAÇÃO BOMBEIRO E SOCIEDADE',44,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2484,'CONSTRUÇÃO, REFORMA , AMPLIAÇÃO E AQUISIÇÃO DE EQUIPAMENTOS PARA AS UNIDADES DE SAÚDE NOS MUNICÍPIOS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2485,'CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE SEDES ADMINISTRATIVAS E PROMOTORIAS DE JUSTIÇA',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2488,'CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DO SISTEMA PENITENCIÁRIO',22,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2489,'CONTROLE DE AGROTÓXICOS',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2490,'CONTROLE E OPERAÇÃO DE TRÁFEGO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2491,'COORDENAÇÃO DA PROCURADORIA GERAL DO ESTADO',36,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2492,'COORDENAÇÃO DAS AÇÕES PARA A PROMOÇÃO DO DESENVOLVIMENTO DA JUVENTUDE',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2494,'COORDENAÇÃO GERAL DA ACADEMIA DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2495,'COORDENAÇÃO GERAL DA ADH',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2496,'COORDENAÇÃO GERAL DA CMTP',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2497,'COORDENAÇÃO GERAL DA DEFENSORIA PÚBLICA',35,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2498,'COORDENAÇÃO GERAL DA FAPEPI',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2499,'COORDENAÇÃO GERAL DA FUESPI',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2502,'COORDENAÇÃO GERAL DA FUNDAÇÃO CEPRO',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2504,'COORDENAÇÃO GERAL DA JUCEPI',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2508,'COORDENAÇÃO GERAL DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2521,'COORDENAÇÃO GERAL DA SDR',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2531,'COORDENAÇÃO GERAL DA SECRETARIA DA CULTURA',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2532,'COORDENAÇÃO GERAL DA SECRETARIA DE DEFESA CIVIL',49,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2533,'COORDENAÇÃO GERAL DA SECRETARIA DE ESTADO DA SAÚDE - SESAPI',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2534,'COORDENAÇÃO GERAL DA SECRETARIA DE SEGURANÇA PÚBLICA',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2535,'COORDENAÇÃO GERAL DA SEID',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2536,'COORDENAÇÃO GERAL DA SEINFRA',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2537,'COORDENAÇÃO GERAL DA SEPLAN',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2539,'COORDENAÇÃO GERAL DO 10º BATALHÃO DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2540,'COORDENAÇÃO GERAL DO 11º BATALHÃO DA POLÍCIA MILITAR - SÃO RAIMUNDO NONATO',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2541,'COORDENAÇÃO GERAL DO 12º BATALHÃO DA POLÍCIA MILITAR - PIRIPIRI',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2542,'COORDENAÇÃO GERAL DO 2º BATALHÃO DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2543,'COORDENAÇÃO GERAL DO 3º BATALHÃO DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2544,'COORDENAÇÃO GERAL DO 4º BATALHÃO DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2545,'COORDENAÇÃO GERAL DO 7º BATALHÃO DA POLÍCIA MILITAR',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2546,'COORDENAÇÃO GERAL DO CORPO DE BOMBEIROS',44,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2547,'COORDENAÇÃO GERAL DO EMATER',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2548,'COORDENAÇÃO GERAL DO IMEPI',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2549,'CRIAÇÃO DE UNIDADES REGIONAIS INTEGRADAS DE BAIXA, MÉDIA E ALTA COMPLEXIDADE',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2550,'CRIAÇÃO E APOIO NA IMPLANTAÇÃO DOS SISTEMAS MUNICIPAIS DE CULTURA',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2551,'DEFESA ANIMAL',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2552,'DEFESA VEGETAL',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2553,'DESCENTRALIZAÇÃO E MODERNIZAÇÃO DA GESTÃO AMBIENTAL E DOS RECURSOS HÍDRICOS',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2554,'DESENVOLVIMENTO DA BIOTECNOLOGIA NO ESTADO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2555,'DESENVOLVIMENTO DE PROJETOS VOLTADOS A REMISSÃO DE PENAS E PROMOÇÃO DE CIDADANIA',22,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2556,'DESENVOLVIMENTO SOCIOAMBIENTAL DA ÁREA DOS POÇOS JORRANTES DO VALE DO GURGUÉIA',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2557,'DIFUSÃO CIENTÍFICA E TECNOLÓGICA',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2558,'DISTRIBUIÇÃO DE GÁS NATURAL ATRAVÉS DO GASODUTO',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2559,'DIVULGAÇÃO CULTURAL E DE POTENCIALIDADES DO PIAUÍ EM BRASÍLIA',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2560,'EFETIVAÇÃO DOS DIREITOS SOCIAIS E ASSISTÊNCIA A PESSOA COM DEFICIÊNCIA',35,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2561,'ELABORAÇÃO DO MAPA DA SEGURANÇA PÚBLICA DO ESTADO DO PIAUÍ',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2562,'ELABORAÇÃO E IMPLEMENTAÇÃO DE INSTRUMENTOS DE PROMOÇÃO DO ORDENAMENTO E GESTÃO TERRITORIAL: ZEE E CAR',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2563,'ELABORAÇÃO E IMPLEMENTAÇÃO DE PROJETOS E ATIVIDADES DE ABASTECIMENTO DE ÁGUA POTÁVEL E ESGOTAMENTO SANITÁRIO',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2564,'ENCARGOS PATRONAIS E CONTRIBUTIVOS',24,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2565,'ENFRENTAMENTO DAS DIVERSAS FORMAS DE VIOLÊNCIAS NO ESTADO DO PIAUÍ',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2566,'ENSINO DE GRADUAÇÃO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2567,'ENSINO DE PÓS-GRADUAÇÃO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2568,'ESTRATÉGIAS DE ATENDIMENTO ADEQUADO ÀS VÍTIMAS ESPECÍFICAS',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2569,'ESTRUTURAÇÃO DA COORDENAÇÃO DAS PARCERIAS PÚBLICO-PRIVADAS PPPS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2570,'ESTRUTURAÇÃO DO SISTEMA DE MONITORAMENTO E GESTÃO DA PROTEÇÃO AMBIENTAL',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2571,'ESTRUTURAÇÃO DO SISTEMA ESTADUAL DE ESPORTE E LAZER',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2572,'ESTRUTURAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA',35,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2573,'ESTRUTURAÇÃO E FORTALECIMENTO DA REDE DE ATENÇÃO PSICOSSOCIAL DO ESTADO DO PIAUÍ',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2574,'ESTUDOS E PESQUISAS SOCIOECONÔMICAS',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2575,'EXPANSÃO DA REDE E-TEC',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2576,'EXPANSÃO DAS AÇÕES DE INCLUSÃO PRODUTIVA ATRAVÉS DE PROJETOS DE ECONOMIA SOLIDÁRIA',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2577,'EXPANSÃO DO PRONATEC',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2578,'EXPANSÃO DO SINAL DA TV EDUCATIVA E RÁDIO ANTARES',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2579,'EXPANSÃO E FORTALECIMENTO DA UNIVERSIDADE ABERTA NO PIAUÍ',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2580,'EXPANSÃO E REESTRUTURAÇÃO DA REDE DE EDUCAÇÃO DE JOVENS E ADULTOS',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2581,'EXTENSÃO UNIVERSITÁRIA E ASSISTÊNCIA COMUNITÁRIA',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2582,'FOMENTO À CRIAÇÃO E A PRODUÇÃO DE BENS ARTÍSTICOS E CULTURAIS DAS DIVERSAS LINGUAGENS',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2583,'FOMENTO AO DESENVOLVIMENTO DO ESTADO DO PIAUÍ',13,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2584,'FOMENTO À PESQUISA E DESENVOLVIMENTO TÉCNICO, CIENTÍFICO E INOVAÇÃO',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2585,'FOMENTO E DIFUSÃO DA CULTURA EXPORTADORA NO ESTADO DO PIAUÍ',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2586,'FORMAÇÃO DE PESSOAS E CAPACITAÇÃO DE POLICIAIS MILITARES',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2587,'FORTALECIMENTO ADMINISTRATIVO E MELHORIA DA INFRAESTRUTURA DO IASPI',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2588,'FORTALECIMENTO AOS ARRANJOS PRODUTIVOS LOCAIS',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2589,'FORTALECIMENTO DA ATENÇÃO PRIMÁRIA/SECUNDÁRIA/ESPECIALIZADA NO CONTEXTO DAS AÇÕES E SERVIÇOS DE SAÚDE DO SUS-PI NOS 224 MUNICÍPIOS DO ESTADO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2590,'FORTALECIMENTO DA COORDENAÇÃO GERAL DA SECID',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2591,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PARNAÍBA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2592,'FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PIRIPIRI',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2593,'FORTALECIMENTO DA GESTÃO DA ALEPI',01,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2594,'FORTALECIMENTO DA GESTÃO DEMOCRÁTICA DA EDUCAÇÃO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2595,'FORTALECIMENTO DA GESTÃO E APRIMORAMENTO DAS INSTÂNCIAS DE PACTUAÇÃO E CONTROLE SOCIAL E DA REDE DE PROTEÇÃO SOCIAL',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2596,'FORTALECIMENTO DA GESTÃO NO ÂMBITO DO SUS-PI (CONTROLE, PLANEJAMENTO, REGULAÇÃO, AVALIAÇÃO, OUVIDORIA, AUDITORIA, EDUCAÇÃO PERMANENTE DA REDE PÚBLICA DE SAÚDE E DAS UNIDADES ADMINISTRATIVAS DA SESAPI)',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2597,'FORTALECIMENTO DA INFRAESTRUTURA HÍDRICA PARA A IRRIGAÇÃO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2598,'FORTALECIMENTO DA REDE DE PROTEÇÃO SOCIAL VISANDO À AMPLIAÇÃO E QUALIFICAÇÃO DAS MEDIDAS SOCIOASSISTENCIAIS',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2599,'FORTALECIMENTO DAS INSTÂNCIAS COLEGIADAS DE DEFESA DOS DIREITOS DAS PESSOAS COM DEFICIÊNCIA NOS MUNICÍPIOS',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2600,'FORTALECIMENTO DAS RELAÇÕES INSTITUCIONAIS ENTRE OS VÁRIOS ENTES DA FEDERAÇÃO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2601,'FORTALECIMENTO DE PARCERIAS',25,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2602,'FORTALECIMENTO DE POLÍTICAS DE PREVENÇÃO À VIOLÊNCIA NO TRÂNSITO',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2603,'FORTALECIMENTO DO LAZER E DESENVOLVIMENTO SOCIAL',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2604,'FORTALECIMENTO DOS CONSELHOS DE POLÍTICAS PÚBLICAS SOBRE DROGAS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2605,'FORTALECIMENTO E AMPLIAÇÃO DO PROGRAMA CULTURA VIVA NO ESTADO',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2606,'FORTALECIMENTO INSTITUCIONAL',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2607,'FORTALECIMENTO INSTITUCIONAL DA SEJUS',22,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2608,'FUNDO DE DESENVOLVIMENTO INDUSTRIAL DO PIAUÍ',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2609,'FUNDO ESTADUAL DE INTERESSE SOCIAL',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2610,'FUNDO ROTATIVO DE MATERIAL E CONSERVAÇÃO DE PATRIMÔNIO DO ESTADO DO PIAUÍ',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2611,'GARANTIA DO ACESSO E DA PERMANÊNCIA DA PESSOA COM DEFICIÊNCIA A UMA EDUCAÇÃO QUE FAVOREÇA O SEU PLENO DESENVOLVIMENTO E SUA INCLUSÃO SOCIAL',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2612,'GESTÃO DA CONTROLADORIA GERAL DO ESTADO',37,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2613,'GESTÃO DA COORDENADORIA DE DESENVOLVIMENTO SOCIAL E LAZER',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2614,'GESTÃO DA COORDENADORIA DE FOMENTO À IRRIGAÇÃO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2615,'GESTÃO DA COORDENADORIA DE FOMENTO AO SANEAMENTO RURAL',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2616,'GESTÃO DA DÍVIDA PÚBLICA',24,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2617,'GESTÃO DA SECRETARIA ESTADUAL DE MEIO AMBIENTE E RECURSOS HÍDRICOS',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2618,'GESTÃO DE PESSOAS - CRIAÇÃO, INSTALAÇÃO E PROVIMENTO DE VARAS E JUIZADOS',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2619,'GESTÃO DE RESÍDUOS SÓLIDOS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2620,'GESTÃO DO IASPI SAÚDE',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2621,'GESTÃO DO INSTITUTO DE ÁGUAS E ESGOTOS DO PIAUÍ',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2622,'GESTÃO DO PLAMTA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2623,'GESTÃO E MANUTENÇÃO',02,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2624,'GESTÃO E MANUTENÇÃO DA ADAPI',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2625,'GESTÃO E REGULARIZAÇÃO DO SISTEMA DE OFERTA DE ÁGUA DO ESTADO DO PIAUÍ',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2626,'GESTÃO GERAL DA SEMINPER',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2627,'GESTÃO MODERNA DA SECRETARIA DOS TRANSPORTES',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2628,'HABITAÇÃO PARA SERVIDORES PÚBLICOS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2629,'IMPLANTAÇÃO DE ANÉIS VIÁRIOS NOS MUNICÍPIOS PIAUIENSES',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2630,'IMPLANTAÇÃO DE ESTRATÉGIA DE POLÍCIA COMUNITÁRIA',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2631,'IMPLANTAÇÃO DE MELHORIAS SANITÁRIAS DOMICILIARES NAS COMUNIDADES RURAIS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2632,'IMPLANTAÇÃO DE PARQUES TECNOLÓGICOS',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2633,'IMPLANTAÇÃO DE SERVIÇOS DE CARÁTER REGIONAL OU DE UNIDADES REGIONAIS DE PROTEÇÃO SOCIAL ESPECIAL DE MÉDIA E ALTA COMPLEXIDADE, PODENDO TER COMO REFERÊNCIA A EXISTÊNCIA DE COMARCAS, AS MICRORREGIÕES E O MAPA DE RISCO SOCIAL',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2634,'IMPLANTAÇÃO DE SISTEMA ADUTOR E OUTRAS OBRAS HÍDRICAS, EM ÁREAS URBANAS E RURAIS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2635,'IMPLANTAÇÃO DO METRÔ DE TERESINA',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2636,'IMPLANTAÇÃO E EXECUÇÃO DE PAVIMENTAÇÃO COM PARALELEPÍPEDO, ESTRADA VICINAL E PAVIMENTAÇÃO ASFÁLTICA',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2637,'IMPLANTAÇÃO E IMPLEMENTAÇÃO DAS REDES TEMÁTICAS NAS  REGIÕES DE SAÚDE DO ESTADO, VIABILIZANDO AÇÕES DE PROMOÇÃO, PREVENÇÃO, TRATAMENTO E REABILITAÇÃO, TENDO A ATENÇÃO BÁSICA COMO ORDENADORA DO CUIDADO EM REDE',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2638,'IMPLANTAÇÃO E RECUPERAÇÃO DE SISTEMAS DE ABASTECIMENTO DE ÁGUA E ESGOTAMENTO SANITÁRIO NAS COMUNIDADES RURAIS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2639,'IMPLEMENTAÇÃO DA ACESSIBILIDADE NO DESENHO UNIVERSAL',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2640,'IMPLEMENTAÇÃO DA POLÍTICA DE ATENDIMENTO À PESSOA COM DEFICIÊNCIA',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2641,'IMPLEMENTAÇÃO DAS AÇÕES DO PROGRAMA BRASIL PROFISSIONALIZADO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2642,'IMPLEMENTAÇÃO DE AÇÕES DE PREVENÇÃO',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2643,'IMPLEMENTAÇÃO DE AÇÕES DE VALORIZAÇÃO DOS PROFISSIONAIS DA EDUCAÇÃO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2644,'IMPLEMENTAÇÃO DE INTERVENÇÕES NA ÁREA DE RESÍDUOS SÓLIDOS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2645,'IMPLEMENTAÇÃO DE PROJETOS DE EMPODERAMENTO DAS MULHERES, VALORIZANDO E AMPLIANDO SUA PARTICIPAÇÃO NO DESENVOLVIMENTO DO ESTADO.',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2646,'IMPLEMENTAÇÃO DO PLANO ESTADUAL PIAUÍ VIVER SEM LIMITE',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2647,'IMPLEMENTAÇÃO DO PROGRAMA DE ALFABETIZAÇÃO DE JOVENS E ADULTOS',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2648,'IMPLEMENTAÇÃO DO PROGRAMA DE INCENTIVO AO ALUNO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2649,'IMPLEMENTAÇÃO DO PROGRAMA PROJOVEM URBANO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2650,'IMPLEMENTAÇÃO E APERFEIÇOAMENTO DOS INSTRUMENTOS DE GESTÃO DE RECURSOS HÍDRICOS',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2651,'IMPLEMENTAÇÃO E GESTÃO DO PROGRAMA ESTADUAL DE EDUCAÇÃO AMBIENTAL',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2652,'INCENTIVO A PESQUISA TECNOLÓGICA NO SETOR RURAL PARA O DESENVOLVIMENTO SUSTENTÁVEL',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2653,'INCENTIVO ÀS EXPORTAÇÕES E ATRAÇÃO DE INVESTIMENTOS',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2655,'INFRAESTRUTURA DE PRÉDIOS DA JUSTIÇA',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2656,'INFRAESTRUTURA DO MODAL AEROVIÁRIO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2657,'INFRAESTRUTURA DO MODAL FERROVIÁRIO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2658,'INFRAESTRUTURA DO MODAL HIDROVIÁRIO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2659,'INFRAESTRUTURA DO MODAL PORTUÁRIO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2660,'INFRAESTRUTURA DO MODAL RODOVIÁRIO',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2661,'INFRAESTRUTURA E REAPARELHAMENTO DE TECNOLOGIA DA INFORMAÇÃO',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2662,'INTERIORIZAÇÃO DAS AÇÕES DO TRIBUNAL DE CONTAS DO ESTADO',02,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2663,'INVESTIMENTO EM PARTICIPAÇÕES SOCIETÁRIAS',24,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2664,'LINHA ALTOS PARNAÍBA',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2665,'MANUTENÇÃO E AMPLIAÇÃO DA ESCOLA DO PODER LEGISLATIVO',01,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2666,'MANUTENÇÃO E GESTÃO DA EMGERPI',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2667,'MANUTENÇÃO E IMPLEMENTAÇÃO DAS DEMAIS FASES DA ZPE PARNAÍBA',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2668,'MELHORIA DA GESTÃO ESPORTIVA DO ESTADO',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2669,'MELHORIA DAS CONDIÇÕES DE CONSERVAÇÃO E PRESERVAÇÃO DOS DOCUMENTOS HISTÓRICOS',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2670,'MELHORIA E ADEQUAÇÃO DA ESTRUTURA FÍSICA, TÉCNICA E INSTITUCIONAL DA FUNDESPI',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2671,'MELHORIA FÍSICA DO SETOR DE ATENDIMENTO PSICOSSOCIAL',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2672,'MELHORIA HABITACIONAL',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2673,'METROLOGIA LEGAL E AVALIAÇÃO DE CONFORMIDADE',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2674,'MODERNIZAÇÃO DA ADMINISTRAÇÃO TRIBUTÁRIA E APERFEIÇOAMENTO NA GESTÃO DE RECURSOS HUMANOS',13,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2675,'MODERNIZAÇÃO DA COMUNICAÇÃO DAS AÇÕES DO GOVERNO À SOCIEDADE',33,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2676,'MODERNIZAÇÃO DA CONTROLADORIA GERAL DO ESTADO',37,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2677,'MODERNIZAÇÃO DA DEFENSORIA PÚBLICA DO ESTADO',35,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2678,'MODERNIZAÇÃO DA GESTÃO ADMINISTRATIVA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2679,'MODERNIZAÇÃO DA GESTÃO DA SEDUC',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2680,'MODERNIZAÇÃO DA GESTÃO DA SEID',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2681,'MODERNIZAÇÃO DA GESTÃO DO IASPI',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2682,'MODERNIZAÇÃO DA GESTÃO DO SISTEMA ÚNICO DA ASSISTÊNCIA SOCIAL',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2683,'MODERNIZAÇÃO DA GESTÃO DOS RECURSOS DA POLÍCIA MILITAR DO PIAUÍ',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2684,'MODERNIZAÇÃO DA INFRAESTRUTURA E QUALIFICAÇÃO DOS GESTORES E AGENTES CULTURAIS',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2685,'MODERNIZAÇÃO DAS ESTRUTURAS, CAPACITAÇÃO E TREINAMENTO PARA OS PROFISSIONAIS DE SEGURANÇA PÚBLICA',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2686,'MODERNIZAÇÃO DAS INSTALAÇÕES DA UESPI',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2687,'MODERNIZAÇÃO DO INTERPI',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2688,'MODERNIZAÇÃO DOS SERVIÇOS NA JUCEPI',20,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2689,'MODERNIZAÇÃO E APERFEIÇOAMENTO DA GESTÃO FISCAL',13,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2690,'MODERNIZAÇÃO E MELHORIA DE MATERIAL RODANTE',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2691,'MODERNIZAÇÃO E QUALIFICAÇÃO DO PROCESSO DE GESTÃO, AQUISIÇÃO, CONTROLE DE ESTOQUE, ARMAZENAMENTO, DISTRIBUIÇÃO E DISPENSAÇÃO DE MEDICAMENTOS EM TODAS AS UNIDADES DE ASSISTÊNCIA FARMACÊUTICA SOB GESTÃO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2692,'ORGANIZAÇÃO E REALIZAÇÃO DE EVENTOS ESPORTIVOS',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2693,'PESQUISA DE ESTATÍSTICA E INFORMAÇÃO',19,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2694,'PESQUISA E TECNOLOGIA',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2695,'POLÍTICAS DE VALORIZAÇÃO DA SECRETARIA DE JUSTIÇA E DO SERVIDOR',22,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2696,'PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS - TERRITÓRIO ALTO PARNAÍBA',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2697,'PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE DE FORMA INDISSOCIÁVEL E INTEGRADA AO ENSINO, PESQUISA E EXTENSÃO',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2698,'PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE PARA A POPULAÇÃO DO ESTADO DO PIAUÍ',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2699,'PREVENÇÃO E COMBATE À CORRUPÇÃO',37,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2700,'PROGRAMA ESTADUAL DE ERRADICAÇÃO E PREVENÇÃO DA FEBRE AFTOSA',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2701,'PROGRAMA MEMÓRIAS',02,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2702,'PROGRAMA - PESSOAS EM FOCO',02,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2703,'PROGRAMA TREM REGIONAL',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2704,'PROJETO MIRIM CIDADÃO',12,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2705,'PROMOÇÃO DA EDUCAÇÃO SANITÁRIA ANIMAL E VEGETAL',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2706,'PROMOÇÃO DA PESQUISA, DESENVOLVIMENTO TECNOLÓGICO E INOVAÇÃO NO SETOR MINERAL',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2707,'PROMOÇÃO DA SEGURANÇA ALIMENTAR',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2708,'PROMOÇÃO DE AÇÕES SOCIOECONÔMICAS E EDUCATIVAS AOS DETENTOS E AMPLA MODERNIZAÇÃO DOS ESTABELECIMENTOS PENITENCIÁRIOS',22,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2709,'PROMOÇÃO DE NEGÓCIOS ENERGÉTICOS',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2710,'PROMOÇÃO DE NEGÓCIOS MINERAIS',50,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2711,'PROMOÇÃO DE VIGILÂNCIAS EM SAÚDE EPIDEMIOLÓGICA, AMBIENTAL E SANITÁRIA E SAÚDE DO TRABALHADOR',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2712,'PROMOÇÃO DO ACESSO DAS PESSOAS COM DEFICIÊNCIA AO MERCADO DE TRABALHO FORMAL, DE GERAÇÃO DE RENDA E DE EMPREENDEDORISMO',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2713,'PROMOÇÃO DO ATENDIMENTO AS MULHERES EM SITUAÇÃO DE VIOLÊNCIA',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2714,'PROMOÇÃO DOS DIREITOS DE CRIANÇAS E ADOLESCENTES POR MEIO DA PROTEÇÃO SOCIAL BÁSICA E ESPECIAL COM O OBJETIVO DE ENFRENTAR AS SITUAÇÕES DE VIOLÊNCIA, DE TRABALHO INFANTIL E EXPLORAÇÃO SEXUAL',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2715,'PROMOÇÃO E ARTICULAÇÃO DE AÇÕES DE EDUCAÇÃO EM DIREITOS, PROTEÇÃO ÀS MULHERES E ENFRENTAMENTO ÀS DROGAS',35,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2716,'PROMOÇÃO E DEFESA DE DIREITOS HUMANOS, COM ÊNFASE NAS PESSOAS COM DIREITOS VIOLADOS OU EM SITUAÇÃO DE IMINENTE VIOLAÇÃO',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2717,'PROTEÇÃO E PRESERVAÇÃO DOS BENS CULTURAIS E CONHECIMENTOS DOS POVOS E COMUNIDADES TRADICIONAIS',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2718,'QUALIFICAÇÃO E VALORIZAÇÃO DO SERVIDOR',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2719,'REALIZAÇÃO E APOIO A EVENTOS CULTURAIS NOS TERRITÓRIOS DE DESENVOLVIMENTO',51,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2720,'REAPARELHAMENTO DA JUSTIÇA',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2721,'RECUPERAÇÃO DAS ÁREAS E ECOSSISTEMAS DEGRADADOS E COMBATE À DESERTIFICAÇÃO',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2722,'RECUPERAÇÃO DOS DANOS CAUSADOS POR DESASTRES',49,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2723,'REESTRUTURAÇÃO DO ESPAÇO FÍSICO E MODERNIZAÇÃO DA NOVA SEDE DA SEID',38,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2724,'REESTRUTURAÇÃO E MANUTENÇÃO DO CONSELHO ESTADUAL DE DEFESA DOS DIREITOS DA MULHER E APOIO À CRIAÇÃO DE CONSELHOS MUNICIPAIS DE DEFESA DOS DIREITOS DA MULHER',11,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2725,'REFORMA, AMPLIAÇÃO, CONSTRUÇÃO E AQUISIÇÃO DE EQUIPAMENTOS  PARA AS UNIDADES DESCENTRALIZADAS DA SESAPI E SERVIÇOS DE SAÚDE  DA REDE ESTADUAL,  COM VISTAS À IMPLEMENTAÇÃO DAS RAS',17,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2726,'REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE INFRAESTRUTURA',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2727,'REGULARIZAÇÃO E AVERBAÇÃO FUNDIÁRIA HABITACIONAL',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2728,'REGULARIZAÇÃO FUNDIÁRIA URBANA DE EMPREENDIMENTOS HABITACIONAIS INCORPORADOS PELA EMGERPI',21,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2729,'REORDENAMENTO DO ATENDIMENTO SOCIOEDUCATIVO DO ESTADO DO PIAUÍ, INCLUINDO A INFRAESTRUTURA FÍSICA, CONTRATAÇÃO E CAPACITAÇÃO DE RECURSOS HUMANOS',30,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2730,'REQUALIFICAÇÃO FÍSICA E DE RECURSOS HUMANOS DA COMPANHIA METROPOLITANA DE TRANSPORTES PÚBLICOS',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2732,'RESTRUTURAÇÃO DAS INSTALAÇÕES FÍSICAS E AQUISIÇÃO DE EQUIPAMENTOS PARA POLÍCIA MILITAR DO PIAUÍ.',26,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2733,'REVISÃO DO ARCABOUÇO LEGAL AMBIENTAL E HÍDRICO DO ESTADO',28,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2734,'SANEAMENTO BÁSICO NOS MUNICÍPIOS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2735,'SERVIÇO DE CLASSIFICAÇÃO DE PRODUTOS DE ORIGEM VEGETAL',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2736,'SERVIÇO DE INSPEÇÃO ESTADUAL (SIE)',15,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2737,'TREINAMENTO E CAPACITAÇÃO DE SERVIDORES E MAGISTRADOS',04,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2738,'TRIBUNAL ON-LINE',02,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2739,'UNIVERSALIZAÇÃO DO ACESSO À ÁGUA',16,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2740,'UNIVERSALIZAÇÃO DO ATENDIMENTO DA EDUCAÇÃO BÁSICA',14,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2741,'URBANIZAÇÃO E CONSTRUÇÃO DE EQUIPAMENTOS SOCIAIS',45,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2742,'VLT PARNAÍBA',46,true);
insert into acaoestrategica (id, nome, orgao_id, ativo) values(2743,'VLT TERESINA - TIMON',46,true);
