insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01101,1,'2143','AMPLIAÇÃO DA ESTRUTURA DA TV E RÁDIO ASSEMBLEIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01101,2,'2593','FORTALECIMENTO DA GESTÃO DA ALEPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01101,3,'2665','MANUTENÇÃO E AMPLIAÇÃO DA ESCOLA DO PODER LEGISLATIVO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (01201,4,'2143','AMPLIAÇÃO DA ESTRUTURA DA TV E RÁDIO ASSEMBLEIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,5,'2623','GESTÃO E MANUTENÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,6,'2662','INTERIORIZAÇÃO DAS AÇÕES DO TRIBUNAL DE CONTAS DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,7,'2701','PROGRAMA MEMÓRIAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,8,'2702','PROGRAMA - PESSOAS EM FOCO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02101,9,'2738','TRIBUNAL ON-LINE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (02102,10,'2654','INFRAESTRUTURAÇÃO DO TCE E EDUCAÇÃO CONTINUADA DOS SERVIDORES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04101,11,'2332','APOIO ADMINISTRATIVO TRIBUNAL DE JUSTIÇA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04101,12,'2618','GESTÃO DE PESSOAS - CRIAÇÃO, INSTALAÇÃO E PROVIMENTO DE VARAS E JUIZADOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04103,13,'2328','APOIO ADMINISTRATIVO CORREGEDORIA GERAL DE JUSTIÇA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04103,14,'2434','APOIO, CONTROLE E FISCALIZAÇÃO JUDICIAL E EXTRAJUDICIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,15,'1520','APOIO ADMINISTRATIVO FERMOJUPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,16,'2257','APERFEIÇOAMENTO DA PRESTAÇÃO JURISDICIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,17,'2655','INFRAESTRUTURA DE PRÉDIOS DA JUSTIÇA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,18,'2661','INFRAESTRUTURA E REAPARELHAMENTO DE TECNOLOGIA DA INFORMAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04105,19,'2720','REAPARELHAMENTO DA JUSTIÇA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (04106,20,'2737','TREINAMENTO E CAPACITAÇÃO DE SERVIDORES E MAGISTRADOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11102,21,'1594','GESTÃO DA VICE-GOVERNADORIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11103,22,'1547','COORDENAÇÃO GERAL DO GABINETE MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,23,'2106','ACOMPANHAMENTO E ASSESSORAMENTO DAS AÇÕES GOVERNAMENTAIS NAS ESFERAS MUNICIPAL , ESTADUAL E FEDERAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,24,'2327','APOIO ADMINISTRATIVO À COORDENAÇÃO GERAL DA SECRETARIA DE GOVERNO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,25,'2569','ESTRUTURAÇÃO DA COORDENAÇÃO DAS PARCERIAS PÚBLICO-PRIVADAS PPPS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,26,'2600','FORTALECIMENTO DAS RELAÇÕES INSTITUCIONAIS ENTRE OS VÁRIOS ENTES DA FEDERAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11110,27,'2669','MELHORIA DAS CONDIÇÕES DE CONSERVAÇÃO E PRESERVAÇÃO DOS DOCUMENTOS HISTÓRICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11111,28,'2391','APOIO A IMIGRANTES PIAUIENSES EM VULNERABILIDADE SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11111,29,'2538','COORDENAÇÃO GERAL DA SURPI BSB',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11111,30,'2559','DIVULGAÇÃO CULTURAL E DE POTENCIALIDADES DO PIAUÍ EM BRASÍLIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,31,'1532','CIDADANIA INCLUSIVA: JUVENTUDE, ESPORTE E LAZER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,32,'1554','EDUCAÇÃO, CIDADANIA E DESENVOLVIMENTO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,33,'1558','EMPREENDA JOVEM',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,34,'1584','FORTALECIMENTO DO CONSELHO ESTADUAL DE DIREITOS DA JUVENTUDE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,35,'1596','GESTÃO E MANUTENÇÃO DA COORDENADORIA ESTADUAL DA JUVENTUDE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,36,'1609','JUVENTUDE E CULTURA VIVA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,37,'1616','MODERNIZAÇÃO DA COORDENADORIA ESTADUAL DA JUVENTUDE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11113,38,'2492','COORDENAÇÃO DAS AÇÕES PARA A PROMOÇÃO DO DESENVOLVIMENTO DA JUVENTUDE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,39,'1560','ENFRENTAMENTO ÀS DIVERSAS FORMAS DE VIOLÊNCIA, AO CRACK E OUTRAS DROGAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,40,'1592','GESTÃO DA COORDENADORIA DE ENFRENTAMENTO ÀS DROGAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,41,'2177','AMPLIAÇÃO DO ACESSO A POLÍTICAS DE ENFRENTAMENTO ÀS DROGAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,42,'2456','CAPACITAÇÃO E QUALIFICAÇÃO DAS EQUIPES TÉCNICAS MULTIDISCIPLINARES QUE ATUAM NO ENFRENTAMENTO ÀS DROGRAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,43,'2573','ESTRUTURAÇÃO E FORTALECIMENTO DA REDE DE ATENÇÃO PSICOSSOCIAL DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,44,'2604','FORTALECIMENTO DOS CONSELHOS DE POLÍTICAS PÚBLICAS SOBRE DROGAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,45,'2642','IMPLEMENTAÇÃO DE AÇÕES DE PREVENÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11114,46,'2671','MELHORIA FÍSICA DO SETOR DE ATENDIMENTO PSICOSSOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,47,'2127','ADMINISTRAÇÃO GERAL DA COORDENADORIA ESTADUAL DE POLÍTICAS PARA AS MULHERES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,48,'2294','APOIO, ACOMPANHAMENTO E MONITORAMENTO À IMPLEMENTAÇÃO DE POLÍTICAS PÚBLICAS DIRECIONADAS PARA A GARANTIA DOS DIREITOS DAS MULHERES.',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,49,'2645','IMPLEMENTAÇÃO DE PROJETOS DE EMPODERAMENTO DAS MULHERES, VALORIZANDO E AMPLIANDO SUA PARTICIPAÇÃO NO DESENVOLVIMENTO DO ESTADO.',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,50,'2713','PROMOÇÃO DO ATENDIMENTO AS MULHERES EM SITUAÇÃO DE VIOLÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11115,51,'2724','REESTRUTURAÇÃO E MANUTENÇÃO DO CONSELHO ESTADUAL DE DEFESA DOS DIREITOS DA MULHER E APOIO À CRIAÇÃO DE CONSELHOS MUNICIPAIS DE DEFESA DOS DIREITOS DA MULHER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11116,52,'2603','FORTALECIMENTO DO LAZER E DESENVOLVIMENTO SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11116,53,'2613','GESTÃO DA COORDENADORIA DE DESENVOLVIMENTO SOCIAL E LAZER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,54,'1580','FORTALECIMENTO DA INFRAESTRUTURA DA AGRICULTURA FAMILIAR IRRIGADA NO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,55,'1581','FORTALECIMENTO DA INFRAESTRUTURA DE IRRIGAÇÃO NO SEMIÁRIDO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,56,'1588','FORTALECIMENTO E AMPLIAÇÃO DA IRRIGAÇÃO VOLTADA AO AGRONEGÓCIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,57,'2597','FORTALECIMENTO DA INFRAESTRUTURA HÍDRICA PARA A IRRIGAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11117,58,'2614','GESTÃO DA COORDENADORIA DE FOMENTO À IRRIGAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11118,59,'2615','GESTÃO DA COORDENADORIA DE FOMENTO AO SANEAMENTO RURAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11118,60,'2631','IMPLANTAÇÃO DE MELHORIAS SANITÁRIAS DOMICILIARES NAS COMUNIDADES RURAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (11118,61,'2638','IMPLANTAÇÃO E RECUPERAÇÃO DE SISTEMAS DE ABASTECIMENTO DE ÁGUA E ESGOTAMENTO SANITÁRIO NAS COMUNIDADES RURAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,62,'2157','AMPLIAÇÃO DAS ESTRUTURAS DE SEGURANÇA PÚBLICA DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,63,'2264','APERFEIÇOAMENTO DO SISTEMA DE INTELIGÊNCIA E POTENCIALIZAÇÃO DO PARQUE TECNOLÓGICO E POLÍCIA TÉCNICO-CIENTÍFICA DA SEGURANÇA PÚBLICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,64,'2436','AQUISIÇÃO DE MATERIAL BÉLICO, EQUIPAMENTO DE PROTEÇÃO INDIVIDUAL, MATERIAL DE INFORMÁTICA E TELEMÁTICA E VEÍCULOS AUTOMOTORES, AÉREOS E MARÍTIMOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,65,'2534','COORDENAÇÃO GERAL DA SECRETARIA DE SEGURANÇA PÚBLICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,66,'2549','CRIAÇÃO DE UNIDADES REGIONAIS INTEGRADAS DE BAIXA, MÉDIA E ALTA COMPLEXIDADE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,67,'2561','ELABORAÇÃO DO MAPA DA SEGURANÇA PÚBLICA DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,68,'2568','ESTRATÉGIAS DE ATENDIMENTO ADEQUADO ÀS VÍTIMAS ESPECÍFICAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,69,'2630','IMPLANTAÇÃO DE ESTRATÉGIA DE POLÍCIA COMUNITÁRIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,70,'2685','MODERNIZAÇÃO DAS ESTRUTURAS, CAPACITAÇÃO E TREINAMENTO PARA OS PROFISSIONAIS DE SEGURANÇA PÚBLICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12101,71,'2704','PROJETO MIRIM CIDADÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12102,72,'2744','MANUTENÇÃO E REESTRUTURAÇÃO DAS UNIDADES DE SEGURANÇA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (12102,73,'2747','COORDENAÇÃO DA DELEGACIA GERAL DA POLÍCIA CIVIL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13101,74,'1627','MODERNIZAÇÃO E APERFEIÇOAMENTO DA GESTÃO ADMINISTRATIVA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13101,75,'2689','MODERNIZAÇÃO E APERFEIÇOAMENTO DA GESTÃO FISCAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13116,76,'2674','MODERNIZAÇÃO DA ADMINISTRAÇÃO TRIBUTÁRIA E APERFEIÇOAMENTO NA GESTÃO DE RECURSOS HUMANOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13203,77,'2583','FOMENTO AO DESENVOLVIMENTO DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13204,78,'2417','APOIO AO FUNDO GARANTIDOR DOS MICRO E PEQUENOS EMPREENDIMENTOS DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13205,79,'2416','APOIO AO FUNDO ESPECIAL DE PRODUCÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (13206,80,'2746','FUNDO ESPECIAL DE CRÉDITOS INADIMPLIDOS E DÍVIDA ATIVA -FECIDAPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14101,81,'2579','EXPANSÃO E FORTALECIMENTO DA UNIVERSIDADE ABERTA NO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14101,82,'2679','MODERNIZAÇÃO DA GESTÃO DA SEDUC',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,83,'1555','EDUCAÇÃO CONTEXTUALIZADA NA REGIÃO DO SEMIÁRIDO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,84,'1601','IMPLANTAÇÃO DO SISTEMA DE FIBRA ÓTICA NAS ESCOLAS DA REDE ESTADUAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,85,'2276','APLICAÇÃO DOS RECURSOS DO FUNDEB',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,86,'2454','AVALIAÇÃO DOS INDICADORES EDUCACIONAIS DA REDE ESTADUAL DE ENSINO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,87,'2575','EXPANSÃO DA REDE E-TEC',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,88,'2577','EXPANSÃO DO PRONATEC',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,89,'2580','EXPANSÃO E REESTRUTURAÇÃO DA REDE DE EDUCAÇÃO DE JOVENS E ADULTOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,90,'2594','FORTALECIMENTO DA GESTÃO DEMOCRÁTICA DA EDUCAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,91,'2641','IMPLEMENTAÇÃO DAS AÇÕES DO PROGRAMA BRASIL PROFISSIONALIZADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,92,'2643','IMPLEMENTAÇÃO DE AÇÕES DE VALORIZAÇÃO DOS PROFISSIONAIS DA EDUCAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,93,'2647','IMPLEMENTAÇÃO DO PROGRAMA DE ALFABETIZAÇÃO DE JOVENS E ADULTOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,94,'2648','IMPLEMENTAÇÃO DO PROGRAMA DE INCENTIVO AO ALUNO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,95,'2649','IMPLEMENTAÇÃO DO PROGRAMA PROJOVEM URBANO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14102,96,'2740','UNIVERSALIZAÇÃO DO ATENDIMENTO DA EDUCAÇÃO BÁSICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,97,'2499','COORDENAÇÃO GERAL DA FUESPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,98,'2566','ENSINO DE GRADUAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,99,'2567','ENSINO DE PÓS-GRADUAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,100,'2581','EXTENSÃO UNIVERSITÁRIA E ASSISTÊNCIA COMUNITÁRIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,101,'2686','MODERNIZAÇÃO DAS INSTALAÇÕES DA UESPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14201,102,'2694','PESQUISA E TECNOLOGIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,103,'2344','APOIO A EVENTOS ESPORTIVOS, FORMAÇÃO, QUALIFICAÇÃO E FOMENTO À PARTICIPAÇÃO DE ATLETAS EM EVENTOS ESPORTIVOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,104,'2571','ESTRUTURAÇÃO DO SISTEMA ESTADUAL DE ESPORTE E LAZER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,105,'2668','MELHORIA DA GESTÃO ESPORTIVA DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,106,'2670','MELHORIA E ADEQUAÇÃO DA ESTRUTURA FÍSICA, TÉCNICA E INSTITUCIONAL DA FUNDESPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14203,107,'2692','ORGANIZAÇÃO E REALIZAÇÃO DE EVENTOS ESPORTIVOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14204,108,'2134','ADMINISTRAÇÃO GERAL DA FUNDAÇÃO ANTARES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (14204,109,'2578','EXPANSÃO DO SINAL DA TV EDUCATIVA E RÁDIO ANTARES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,110,'1516','ÁGUA PARA TODOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,111,'1523','APROVEITAMENTO DAS POTENCIALIDADES AGROENERGÉTICAS DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,112,'1564','EXECUÇÃO DO PROGRAMA NACIONAL DO CRÉDITO FUNDIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,113,'1565','EXECUÇÃO, EM PARCERIA COM O GOVERNO FEDERAL, DAS AÇÕES PREVISTAS NO PLANO DE DESENVOLVIMENTO AGROPECUÁRIO DO MATOPIBA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,114,'1569','FOMENTO AOS SISTEMAS DE PRODUÇÃO FAMILIAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,115,'1582','FORTALECIMENTO DAS ORGANIZAÇÕES SOCIAIS E ARTICULAÇÃO DAS INSTITUIÇÕES GOVERNAMENTAIS E NÃO GOVERNAMENTAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,116,'1585','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS AGROPECUÁRIOS E DA SOCIOBIODIVERSIDADE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,117,'1586','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS LOCAIS POR MEIO DO FOMENTO À PRODUÇÃO AGROPECUÁRIA.',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,118,'1590','GERAÇÃO DE EMPREGO E RENDA - PROGERE II',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,119,'1600','IMPLANTAÇÃO DO PLANO AGRICULTURA DE BAIXO CARBONO (PLANO ABC)',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,120,'1613','MINHA CASA MINHA VIDA RURAL - PNHR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,121,'1623','MODERNIZAÇÃO DA SECRETARIA DO DESENVOLVIMENTO RURAL (SDR)',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,122,'1635','POTENCIALIZAÇÃO DOS MERCADOS INSTITUCIONAIS EXISTENTES E VIABILIZAÇÃO DE NOVAS OPORTUNIDADES DE COMERCIALIZAÇÃO DOS PRODUTOS DA AGRICULTURA FAMILIAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,123,'1653','VIVA O SEMIÁRIDO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15101,124,'2521','COORDENAÇÃO GERAL DA SDR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,125,'1517','AMPLIAÇÃO DA ADESÃO AO PROGRAMA GARANTIA SAFRA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,126,'1585','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS AGROPECUÁRIOS E DA SOCIOBIODIVERSIDADE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,127,'1586','FORTALECIMENTO DOS ARRANJOS PRODUTIVOS LOCAIS POR MEIO DO FOMENTO À PRODUÇÃO AGROPECUÁRIA.',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,128,'1590','GERAÇÃO DE EMPREGO E RENDA - PROGERE II',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,129,'1613','MINHA CASA MINHA VIDA RURAL - PNHR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15103,130,'1653','VIVA O SEMIÁRIDO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,131,'1539','COORDENAÇÃO DO INTERPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,132,'1593','GESTÃO DAS TERRAS PÚBLICAS ESTADUAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,133,'1650','REGULARIZAÇÃO FUNDIÁRIA EM ÁREAS URBANAS NO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15201,134,'2687','MODERNIZAÇÃO DO INTERPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,135,'1625','MODERNIZAÇÃO DO EMATER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,136,'2451','ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,137,'2452','ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL NO SEMIÁRIDO PIAUIENSE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15202,138,'2547','COORDENAÇÃO GERAL DO EMATER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,139,'1562','ESTRUTURAÇÃO E MODERNIZAÇÃO DA DEFESA AGROPECUÁRIA DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,140,'2489','CONTROLE DE AGROTÓXICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,141,'2551','DEFESA ANIMAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,142,'2552','DEFESA VEGETAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,143,'2624','GESTÃO E MANUTENÇÃO DA ADAPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,144,'2700','PROGRAMA ESTADUAL DE ERRADICAÇÃO E PREVENÇÃO DA FEBRE AFTOSA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,145,'2705','PROMOÇÃO DA EDUCAÇÃO SANITÁRIA ANIMAL E VEGETAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,146,'2735','SERVIÇO DE CLASSIFICAÇÃO DE PRODUTOS DE ORIGEM VEGETAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (15204,147,'2736','SERVIÇO DE INSPEÇÃO ESTADUAL (SIE)',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,148,'1563','ESTUDO, PESQUISA, ELABORAÇÃO, EXECUÇÃO E ACOMPANHAMENTO DE ESTUDOS E PROJETOS DE OBRAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,149,'1604','INFRAESTRUTURA DE OBRAS, TRANSPORTE E TURISMO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,150,'1605','INFRAESTRUTURA HÍDRICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,151,'1652','SANEAMENTO BASICO AMBIENTAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16101,152,'2536','COORDENAÇÃO GERAL DA SEINFRA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16202,153,'2142','AMPLIAÇÃO DA COLETA E TRATAMENTO DE ESGOTO SANITÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16202,154,'2739','UNIVERSALIZAÇÃO DO ACESSO À ÁGUA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,155,'1533','CONSTRUÇÃO DE ADUTORAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,156,'1534','CONSTRUÇÃO DE BARRAGENS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,157,'1535','CONSTRUÇÃO DE ESTAÇÃO DE PISCICULTURA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,158,'1536','CONSTRUÇÃO DE MACRODRENAGEM',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,159,'1537','CONTRATAÇÃO DE CONSULTORIA EM OBRAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,160,'1548','COORDENAÇÃO GERAL DO IDEPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,161,'1556','ELABORAÇÃO DE ESTUDOS E PROJETOS BÁSICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,162,'1599','IMPLANTAÇÃO DE SISTEMA DE ABASTECIMENTO DE ÁGUA E CONSTRUÇÃO DE ESTAÇÃO DE TRATAMENTO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,163,'1610','MANUTENÇÃO E CONSERVAÇÃO DE BARRAGENS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,164,'1632','PAVIMENTAÇÃO ASFÁLTICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,165,'1633','PAVIMENTAÇÃO EM PARALELEPÍPEDO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (16208,166,'1644','RECUPERAÇÃO E REFORMA DE ESTRADAS VICINAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,167,'1570','FOMENTO DAS AÇÕES E SERVIÇOS MEDIANTE CONVÊNIOS E CONTRATOS DE REPASSES COM MUNICIPIOS, M.SAÚDE, CEF E OUTROS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,168,'2188','AMPLIAÇÃO E DIVERSIFICAÇÃO DA OFERTA DE CONSULTAS, EXAMES LABORATORIAIS E PROCEDIMENTOS ESPECIALIZADOS DE SAÚDE, DE MÉDIA E ALTA COMPLEXIDADE, NO ÂMBITO DOS SERVIÇOS PÚBLICOS DE REFERÊNCIA REGIONAL E ESTADUAL DO SUS-PI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,169,'2533','COORDENAÇÃO GERAL DA SECRETARIA DE ESTADO DA SAÚDE - SESAPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,170,'2589','FORTALECIMENTO DA ATENÇÃO PRIMÁRIA/SECUNDÁRIA/ESPECIALIZADA NO CONTEXTO DAS AÇÕES E SERVIÇOS DE SAÚDE DO SUS-PI NOS 224 MUNICÍPIOS DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,171,'2596','FORTALECIMENTO DA GESTÃO NO ÂMBITO DO SUS-PI (CONTROLE, PLANEJAMENTO, REGULAÇÃO, AVALIAÇÃO, OUVIDORIA, AUDITORIA, EDUCAÇÃO PERMANENTE DA REDE PÚBLICA DE SAÚDE E DAS UNIDADES ADMINISTRATIVAS DA SESAPI)',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,172,'2637','IMPLANTAÇÃO E IMPLEMENTAÇÃO DAS REDES TEMÁTICAS NAS  REGIÕES DE SAÚDE DO ESTADO, VIABILIZANDO AÇÕES DE PROMOÇÃO, PREVENÇÃO, TRATAMENTO E REABILITAÇÃO, TENDO A ATENÇÃO BÁSICA COMO ORDENADORA DO CUIDADO EM REDE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,173,'2691','MODERNIZAÇÃO E QUALIFICAÇÃO DO PROCESSO DE GESTÃO, AQUISIÇÃO, CONTROLE DE ESTOQUE, ARMAZENAMENTO, DISTRIBUIÇÃO E DISPENSAÇÃO DE MEDICAMENTOS EM TODAS AS UNIDADES DE ASSISTÊNCIA FARMACÊUTICA SOB GESTÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,174,'2698','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE PARA A POPULAÇÃO DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,175,'2711','PROMOÇÃO DE VIGILÂNCIAS EM SAÚDE EPIDEMIOLÓGICA, AMBIENTAL E SANITÁRIA E SAÚDE DO TRABALHADOR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17101,176,'2725','REFORMA, AMPLIAÇÃO, CONSTRUÇÃO E AQUISIÇÃO DE EQUIPAMENTOS  PARA AS UNIDADES DESCENTRALIZADAS DA SESAPI E SERVIÇOS DE SAÚDE  DA REDE ESTADUAL,  COM VISTAS À IMPLEMENTAÇÃO DAS RAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17102,177,'1527','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA CHAPADA DAS MANGABEIRAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17103,178,'1637','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO VALE DOS RIOS PIAUÍ E ITAUEIRA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17104,179,'1528','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA PLANÍCIE LITORÂNEA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17105,180,'1636','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DO VALE DO RIO GUARIBAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17106,181,'1530','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO SERRA DA CAPIVARA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17108,182,'1529','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DOS CARNAUBAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17109,183,'1524','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO CHAPADA DAS MANGABEIRAS - CORRENTE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17110,184,'1638','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO VALE DO CANINDÉ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17111,185,'1526','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DOS COCAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17112,186,'1518','AMPLIAÇÃO E DIVERSIFICAÇÃO DA OFERTA DE EXAMES LABORATORIAIS ESPECIALIZADOS DE SAÚDE PÚBLICA, DE MÉDIA E ALTA COMPLEXIDADE NO ÂMBITO DO SUS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17113,187,'2448','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE PARA A POPULAÇÃO INFANTIL DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17114,188,'2443','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE A PACIENTES COM TRANSTORNO MENTAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17115,189,'2447','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO MATERNA E RÉCEM NASCIDOS, REFERENCIADA DO SUS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17116,190,'2449','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL ESPECIALIZADA NA ÁREA DE DOENÇAS INFECCIOSAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17117,191,'2697','PRESTAÇÃO DE ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA E ALTA COMPLEXIDADE DE FORMA INDISSOCIÁVEL E INTEGRADA AO ENSINO, PESQUISA E EXTENSÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17118,192,'2437','ASSISTÊNCIA HEMATOLÓGICA E HEMOTERÁPICA DE QUALIDADE À POPULAÇÃO DOS 224 MUNICÍPIOS DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17119,193,'1528','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO DA PLANÍCIE LITORÂNEA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17121,194,'2439','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DE ESPERANTINA REFERENCIADA PELO SUS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17123,195,'2441','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO N0 TERRITORIO VALE DO CANINDÉ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17124,196,'2442','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO NO TERRITÓRIO SERRA DA CAPIVARA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17125,197,'2440','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO DO TERRITÓRIO VALE DO SAMBITO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17126,198,'2696','PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS - TERRITÓRIO ALTO PARNAÍBA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17128,199,'2438','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17129,200,'2591','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PARNAÍBA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17130,201,'2592','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PIRIPIRI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17131,202,'1521','APOIO TÉCNICO AOS MUNICÍPIOS PARA GARANTIR A INTEGRALIDADE DA ATENÇÃO À SAÚDE NOS MUNICÍPIOS DA SUA ÁREA DE ABRANGÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17132,203,'1577','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE VALENÇA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17133,204,'1575','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE PICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17134,205,'1574','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE FLORIANO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17135,206,'1551','DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE SÃO RAIMUNDO NONATO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17136,207,'1573','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE BOM JESUS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17137,208,'1576','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA COORDENAÇÃO REGIONAL DE SAÚDE DE TERESINA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17138,209,'1525','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE INTEGRADA DO MOCAMBINHO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17139,210,'1570','FOMENTO DAS AÇÕES E SERVIÇOS MEDIANTE CONVÊNIOS E CONTRATOS DE REPASSES COM MUNICIPIOS, M.SAÚDE, CEF E OUTROS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17139,211,'2484','CONSTRUÇÃO, REFORMA , AMPLIAÇÃO E AQUISIÇÃO DE EQUIPAMENTOS PARA AS UNIDADES DE SAÚDE NOS MUNICÍPIOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17141,212,'2756','FORTALECIMENTO DA DESCENTRALIZAÇÃO DAS AÇÕES DA POLÍTICA ESTADUAL DE SAÚDE NOS MUNICÍPIOS DA ÁREA DE ABRANGÊNCIA DA REGIONAL DE SAÚDE - URUÇUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17142,213,'2755','PRESTAÇÃO DA ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA DO SUS - TERRITÓRIO ENTRE RIOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17143,214,'2438','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17144,215,'2752','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE SAÚDE DE BOCAÍNA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17147,216,'2753','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE SAÚDE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17148,217,'2444','ASSISTÊNCIA HOSPITALAR E AMBULATÓRIAL DE MÉDIA E ALTA COMPLEXIDADE À POPULAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (17149,218,'2754','ASSISTÊNCIA HOSPITALAR E AMBULATORIAL DE MÉDIA COMPLEXIDADE À POPULAÇÃO REFERENCIADA PELO SUS À UNIDADE MISTA DE SANTA FILOMENA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,219,'1618','MODERNIZAÇÃO DA GESTÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,220,'1629','MONITORAMENTO E AVALIAÇÃO DE POLÍTICAS PÚBLICAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,221,'1634','PLANEJA PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,222,'2107','ACOMPANHAMENTO ESTRATÉGICO E DESENVOLVIMENTO SOCIOECONÔMICO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19101,223,'2537','COORDENAÇÃO GERAL DA SEPLAN',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,224,'2502','COORDENAÇÃO GERAL DA FUNDAÇÃO CEPRO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,225,'2574','ESTUDOS E PESQUISAS SOCIOECONÔMICAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,226,'2606','FORTALECIMENTO INSTITUCIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (19201,227,'2693','PESQUISA DE ESTATÍSTICA E INFORMAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,228,'1542','COORDENAÇÃO GERAL DA SEDET',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,229,'1559','EMPREENDER PARA CRESCER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,230,'1583','FORTALECIMENTO DO COMÉRCIO E SERVIÇO DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,231,'1622','MODERNIZAÇÃO DA SECRETARIA DO DESENVOLVIMENTO ECONÔMICO E TECNOLÓGICO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,232,'2415','APOIO AO DESENVOLVIMENTO DE ENERGIAS RENOVÁVEIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,233,'2418','APOIO A PESQUISAS E ESTRATÉGIAS PARA O DESENVOLVIMENTO SUSTENTÁVEL E A BIODIVERSIDADE NO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,234,'2432','APOIO ÀS INICIATIVAS DE DESENVOLVIMENTO E INOVAÇÃO TECNOLÓGICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,235,'2554','DESENVOLVIMENTO DA BIOTECNOLOGIA NO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,236,'2557','DIFUSÃO CIENTÍFICA E TECNOLÓGICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,237,'2588','FORTALECIMENTO AOS ARRANJOS PRODUTIVOS LOCAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,238,'2608','FUNDO DE DESENVOLVIMENTO INDUSTRIAL DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,239,'2632','IMPLANTAÇÃO DE PARQUES TECNOLÓGICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20101,240,'2653','INCENTIVO ÀS EXPORTAÇÕES E ATRAÇÃO DE INVESTIMENTOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20102,241,'2584','FOMENTO À PESQUISA E DESENVOLVIMENTO TÉCNICO, CIENTÍFICO E INOVAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20103,242,'2432','APOIO ÀS INICIATIVAS DE DESENVOLVIMENTO E INOVAÇÃO TECNOLÓGICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20103,243,'2554','DESENVOLVIMENTO DA BIOTECNOLOGIA NO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20103,244,'2557','DIFUSÃO CIENTÍFICA E TECNOLÓGICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20103,245,'2745','ADMINISTRAÇÃO GERAL DA COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20201,246,'1611','MELHORIA DA INFRAESTRUTURA DA JUNTA COMERCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20201,247,'1640','PROJETO REDESIM/DESCONCENTRAÇÃO DOS SERVIÇOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20201,248,'2504','COORDENAÇÃO GERAL DA JUCEPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20201,249,'2688','MODERNIZAÇÃO DOS SERVIÇOS NA JUCEPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,250,'2429','APOIO A PROGRAMAS DE TECNOLOGIA SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,251,'2433','APOIO ÀS PESQUISAS CIENTÍFICAS, TECNOLÓGICAS E DE INOVAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,252,'2461','CONCESSÃO DE BOLSAS DE MESTRADO, DOUTORADO E PÓS-DOUTORADO NO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,253,'2498','COORDENAÇÃO GERAL DA FAPEPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20203,254,'2652','INCENTIVO A PESQUISA TECNOLÓGICA NO SETOR RURAL PARA O DESENVOLVIMENTO SUSTENTÁVEL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20205,255,'2108','ADEQUAÇÃO E INFORMATIZAÇÃO DA BASE DE VERIFICAÇÃO METROLÓGICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20205,256,'2548','COORDENAÇÃO GERAL DO IMEPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20205,257,'2673','METROLOGIA LEGAL E AVALIAÇÃO DE CONFORMIDADE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20206,258,'2585','FOMENTO E DIFUSÃO DA CULTURA EXPORTADORA NO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20206,259,'2667','MANUTENÇÃO E IMPLEMENTAÇÃO DAS DEMAIS FASES DA ZPE PARNAÍBA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (20207,260,'1572','FORTALECER A IMPLENTAÇÃO DOS TERMINAIS ALFANDEGADOS DO PIAUÍ - PORTO PI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,261,'2003','ACESSIBILIDADE ÀS PESSOAS COM DEFICIÊNCIA NOS ÓRGÃOS DA REDE ESTADUAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,262,'2125','ADMINISTRAÇÃO DA GESTÃO SECRETARIA DA ADMINISTRAÇÃO E PREVIDÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,263,'2184','AMPLIAÇÃO DOS ESPAÇOS DA CIDADANIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,264,'2678','MODERNIZAÇÃO DA GESTÃO ADMINISTRATIVA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21101,265,'2718','QUALIFICAÇÃO E VALORIZAÇÃO DO SERVIDOR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21102,266,'2610','FUNDO ROTATIVO DE MATERIAL E CONSERVAÇÃO DE PATRIMÔNIO DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,267,'2587','FORTALECIMENTO ADMINISTRATIVO E MELHORIA DA INFRAESTRUTURA DO IASPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,268,'2620','GESTÃO DO IASPI SAÚDE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,269,'2622','GESTÃO DO PLAMTA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21201,270,'2681','MODERNIZAÇÃO DA GESTÃO DO IASPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21203,271,'1595','GESTÃO DO FUNDO DE PREVIDÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21203,272,'1619','MODERNIZAÇÃO DA GESTÃO E DA INFRAESTRUTURA DA PREVIDÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21203,273,'2460','CONCESSÃO DE BENEFÍCIOS PREVIDENCIÁRIOS AOS SERVIDORES DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,274,'1531','CENTRO DE PROCESSAMENTO E ARMAZENAMENTO DE DADOS (DATA CENTER)',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,275,'1538','COORDENAÇÃO DA ATI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,276,'1591','GERENCIAMENTO DOCUMENTAL E SISTEMAS DE INFORMAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,277,'1603','INCLUSÃO SOCIAL ATRAVÉS DA TECNOLOGIA DA INFORMAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,278,'1614','MODERNIZAÇÃO ADMINISTRATIVA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21204,279,'1645','REDE GOVERNO INFOVIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,280,'1566','EXPLORAÇÃO DE JAZIDAS DE CALCÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,281,'1617','MODERNIZAÇÃO DA EMGERPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,282,'1647','REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE ESTRADAS E VIAS ASFÁLTICA, PARALELEPÍPEDO, POLIÉDRICA E VICINAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,283,'1648','REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE UNIDADES HABITACIONAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,284,'1649','REGULARIZAÇÃO DA IMPLANTAÇÃO, REFORMA E AMPLIAÇÃO DE SISTEMAS DE ABASTECIMENTO DE ÁGUA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,285,'2666','MANUTENÇÃO E GESTÃO DA EMGERPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,286,'2726','REGULARIZAÇÃO, CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE INFRAESTRUTURA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21205,287,'2728','REGULARIZAÇÃO FUNDIÁRIA URBANA DE EMPREENDIMENTOS HABITACIONAIS INCORPORADOS PELA EMGERPI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21206,288,'1639','PREVIDÊNCIA DOS SERVIDORES DO ESTADO DO PAIUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21207,289,'2748','GESTÃO DA FUNDAÇÃO PIAUÍ PREVIDÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (21207,290,'2750','MODERNIZAÇÃO DA GESTÃO E INFRAESTRUTURA DA FUNDAÇÃO PIAUÍ PREVIDÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,291,'2488','CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DO SISTEMA PENITENCIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,292,'2555','DESENVOLVIMENTO DE PROJETOS VOLTADOS A REMISSÃO DE PENAS E PROMOÇÃO DE CIDADANIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,293,'2607','FORTALECIMENTO INSTITUCIONAL DA SEJUS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,294,'2695','POLÍTICAS DE VALORIZAÇÃO DA SECRETARIA DE JUSTIÇA E DO SERVIDOR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22101,295,'2708','PROMOÇÃO DE AÇÕES SOCIOECONÔMICAS E EDUCATIVAS AOS DETENTOS E AMPLA MODERNIZAÇÃO DOS ESTABELECIMENTOS PENITENCIÁRIOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (22201,296,'2488','CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DO SISTEMA PENITENCIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (24101,297,'2564','ENCARGOS PATRONAIS E CONTRIBUTIVOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (24101,298,'2616','GESTÃO DA DÍVIDA PÚBLICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (24101,299,'2663','INVESTIMENTO EM PARTICIPAÇÕES SOCIETÁRIAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,300,'1519','APERFEIÇOAMENTO FUNCIONAL DE MEMBROS E SERVIDORES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,301,'1550','DEFESA DA ORDEM JURÍDICA, DO REGIME DEMOCRÁTICO E DOS INTERESSES SOCIAIS E INDIVIDUAIS INDISPONÍVEIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,302,'1561','ESTRUTURAÇÃO E FORTALECIMENTO DAS AÇÕES DO GRUPO DE ATUAÇÃO ESPECIAL DE COMBATE AO CRIME ORGANIZADO (GAECO)',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,303,'1598','IMPLANTAÇÃO DE AÇÕES DE SEGURANÇA INSTITUCIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,304,'1631','PAGAMENTO DE PASSIVOS DE MEMBROS E SERVIDORES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,305,'1646','REESTRUTURAÇÃO ORGANIZACIONAL E DE PROCESSOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,306,'1651','RENOVAÇÃO E OTIMIZAÇÃO DA ESTRUTURA ADMINISTRATIVA DO MINISTÉRIO PÚBLICO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,307,'2485','CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DE SEDES ADMINISTRATIVAS E PROMOTORIAS DE JUSTIÇA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25101,308,'2601','FORTALECIMENTO DE PARCERIAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25102,309,'1626','MODERNIZAÇÃO DO MINISTÉRIO PÚBLICO ESTADUAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (25104,310,'1513','AÇÕES E SERVIÇOS DE PROTEÇÃO E DEFESA DOS DIREITOS DOS CONSUMIDORES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,311,'2508','COORDENAÇÃO GERAL DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,312,'2565','ENFRENTAMENTO DAS DIVERSAS FORMAS DE VIOLÊNCIAS NO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,313,'2602','FORTALECIMENTO DE POLÍTICAS DE PREVENÇÃO À VIOLÊNCIA NO TRÂNSITO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,314,'2683','MODERNIZAÇÃO DA GESTÃO DOS RECURSOS DA POLÍCIA MILITAR DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26101,315,'2732','RESTRUTURAÇÃO DAS INSTALAÇÕES FÍSICAS E AQUISIÇÃO DE EQUIPAMENTOS PARA POLÍCIA MILITAR DO PIAUÍ.',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26102,316,'2444','COORDENAÇÃO DO HOSPITAL DIRCEU ARCOVERDE DA PM-PI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26102,318,'2457','CAPACITAÇÃO TÉCNICA E VALORIZAÇÃO HUMANA DOS FUNCIONÁRIOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26103,319,'2542','COORDENAÇÃO GERAL DO 2º BATALHÃO DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26104,320,'2543','COORDENAÇÃO GERAL DO 3º BATALHÃO DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26105,321,'2544','COORDENAÇÃO GERAL DO 4º BATALHÃO DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26106,322,'2545','COORDENAÇÃO GERAL DO 7º BATALHÃO DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26107,323,'2494','COORDENAÇÃO GERAL DA ACADEMIA DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26107,324,'2586','FORMAÇÃO DE PESSOAS E CAPACITAÇÃO DE POLICIAIS MILITARES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26108,325,'2539','COORDENAÇÃO GERAL DO 10º BATALHÃO DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26109,326,'2540','COORDENAÇÃO GERAL DO 11º BATALHÃO DA POLÍCIA MILITAR - SÃO RAIMUNDO NONATO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26110,327,'2541','COORDENAÇÃO GERAL DO 12º BATALHÃO DA POLÍCIA MILITAR - PIRIPIRI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26111,328,'1543','COORDENAÇÃO GERAL DO 14º BATALHÃO DA POLÍCIA MILITAR - OEIRAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26112,329,'1544','COORDENAÇÃO GERAL DO 15º BATALHÃO DA POLÍCIA MILITAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26113,330,'1545','COORDENAÇÃO GERAL DO BATALHÃO DA 5º COMPANHIA DA POLÍCIA MILITAR - PAULISTANA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (26114,331,'1540','COORDENAÇÃO GERAL DA COMPANHIA INDEPENDENTE DE TURISMO - LUÍS CORREIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,332,'2124','ADESÃO AO PROGRAMA DE ESTÍMULO DE DIVULGAÇÃO A QUALIDADE DA ÁGUA QUALIÁGUA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,333,'2196','AMPLIAÇÃO E MODERNIZAÇÃO DA REDE HIDROMETEOROLÓGICA DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,334,'2199','AMPLIAÇÃO, ESTRUTURAÇÃO E ADEQUAÇÃO DAS ÁREAS PROTEGIDAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,335,'2455','CADASTRAMENTO NO CADASTRO NACIONAL DE USUÁRIOS DE RECURSOS HÍDRICOS (CNARH)',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,336,'2553','DESCENTRALIZAÇÃO E MODERNIZAÇÃO DA GESTÃO AMBIENTAL E DOS RECURSOS HÍDRICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,337,'2556','DESENVOLVIMENTO SOCIOAMBIENTAL DA ÁREA DOS POÇOS JORRANTES DO VALE DO GURGUÉIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,338,'2562','ELABORAÇÃO E IMPLEMENTAÇÃO DE INSTRUMENTOS DE PROMOÇÃO DO ORDENAMENTO E GESTÃO TERRITORIAL: ZEE E CAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,339,'2570','ESTRUTURAÇÃO DO SISTEMA DE MONITORAMENTO E GESTÃO DA PROTEÇÃO AMBIENTAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,340,'2617','GESTÃO DA SECRETARIA ESTADUAL DE MEIO AMBIENTE E RECURSOS HÍDRICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,341,'2625','GESTÃO E REGULARIZAÇÃO DO SISTEMA DE OFERTA DE ÁGUA DO ESTADO DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,342,'2650','IMPLEMENTAÇÃO E APERFEIÇOAMENTO DOS INSTRUMENTOS DE GESTÃO DE RECURSOS HÍDRICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,343,'2651','IMPLEMENTAÇÃO E GESTÃO DO PROGRAMA ESTADUAL DE EDUCAÇÃO AMBIENTAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,344,'2721','RECUPERAÇÃO DAS ÁREAS E ECOSSISTEMAS DEGRADADOS E COMBATE À DESERTIFICAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (28101,345,'2733','REVISÃO DO ARCABOUÇO LEGAL AMBIENTAL E HÍDRICO DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,346,'1515','ADMINISTRAÇÃO GERAL DA SECRETARIA DA ASSISTÊNCIA SOCIAL E CIDADANIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,347,'1602','IMPLEMENTAÇÃO DE AÇÕES DE CIDADANIA A FAMÍLIAS EM SITUAÇÃO DE VULNERABILIDADE SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,348,'1628','MODERNIZAÇÃO E APRIMORAMENTO DA GESTÃO DA SASC',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,349,'2576','EXPANSÃO DAS AÇÕES DE INCLUSÃO PRODUTIVA ATRAVÉS DE PROJETOS DE ECONOMIA SOLIDÁRIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,350,'2595','FORTALECIMENTO DA GESTÃO E APRIMORAMENTO DAS INSTÂNCIAS DE PACTUAÇÃO E CONTROLE SOCIAL E DA REDE DE PROTEÇÃO SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,351,'2707','PROMOÇÃO DA SEGURANÇA ALIMENTAR',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30101,352,'2716','PROMOÇÃO E DEFESA DE DIREITOS HUMANOS, COM ÊNFASE NAS PESSOAS COM DIREITOS VIOLADOS OU EM SITUAÇÃO DE IMINENTE VIOLAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,353,'1522','APRIMORAMENTO DA GESTÃO DO CADASTRO ÚNICO E MONITORAMENTO DO PROGRAMA BOLSA FAMÍLIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,354,'2458','COFINANCIAMENTO DA PROTEÇÃO SOCIAL BÁSICA POSSIBILITANDO A AMPLIAÇÃO, QUALIFICAÇÃO E MANUTENÇÃO DOS SERVIÇOS SOCIOASSISTENCIAIS, PROGRAMAS, BENEFÍCIOS E PROJETOS NO ÂMBITO DO SUAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,355,'2459','COFINANCIAMENTO DA PROTEÇÃO SOCIAL ESPECIAL POSSIBILITANDO SUA AMPLIAÇÃO, QUALIFICAÇÃO E MANUTENÇÃO DOS SERVIÇOS E ESTRUTURAÇÃO DA REDE DE PROTEÇÃO SOCIAL ESPECIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,356,'2633','IMPLANTAÇÃO DE SERVIÇOS DE CARÁTER REGIONAL OU DE UNIDADES REGIONAIS DE PROTEÇÃO SOCIAL ESPECIAL DE MÉDIA E ALTA COMPLEXIDADE, PODENDO TER COMO REFERÊNCIA A EXISTÊNCIA DE COMARCAS, AS MICRORREGIÕES E O MAPA DE RISCO SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,357,'2682','MODERNIZAÇÃO DA GESTÃO DO SISTEMA ÚNICO DA ASSISTÊNCIA SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30102,358,'2714','PROMOÇÃO DOS DIREITOS DE CRIANÇAS E ADOLESCENTES POR MEIO DA PROTEÇÃO SOCIAL BÁSICA E ESPECIAL COM O OBJETIVO DE ENFRENTAR AS SITUAÇÕES DE VIOLÊNCIA, DE TRABALHO INFANTIL E EXPLORAÇÃO SEXUAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30104,359,'1641','PROMOÇÃO DOS DIREITOS DAS CRIANÇAS E ADOLESCENTES MEDIANTE A PROTEÇÃO SOCIAL BÁSICA E ESPECIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30104,360,'2729','REORDENAMENTO DO ATENDIMENTO SOCIOEDUCATIVO DO ESTADO DO PIAUÍ, INCLUINDO A INFRAESTRUTURA FÍSICA, CONTRATAÇÃO E CAPACITAÇÃO DE RECURSOS HUMANOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (30105,361,'2716','PROMOÇÃO E DEFESA DE DIREITOS HUMANOS, COM ÊNFASE NAS PESSOAS COM DIREITOS VIOLADOS OU EM SITUAÇÃO DE IMINENTE VIOLAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (33101,362,'2139','ADMINISTRAÇÃO GERAL DE COMUNICAÇÃO SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (33101,363,'2675','MODERNIZAÇÃO DA COMUNICAÇÃO DAS AÇÕES DO GOVERNO À SOCIEDADE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,364,'1589','FUNDO DE MODERNIZAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,365,'2450','ASSISTÊNCIA JURÍDICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,366,'2497','COORDENAÇÃO GERAL DA DEFENSORIA PÚBLICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,367,'2560','EFETIVAÇÃO DOS DIREITOS SOCIAIS E ASSISTÊNCIA A PESSOA COM DEFICIÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,368,'2572','ESTRUTURAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,369,'2677','MODERNIZAÇÃO DA DEFENSORIA PÚBLICA DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (35101,370,'2715','PROMOÇÃO E ARTICULAÇÃO DE AÇÕES DE EDUCAÇÃO EM DIREITOS, PROTEÇÃO ÀS MULHERES E ENFRENTAMENTO ÀS DROGAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (36101,371,'1621','MODERNIZAÇÃO DA PROCURADORIA GERAL DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (36101,372,'2491','COORDENAÇÃO DA PROCURADORIA GERAL DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (37101,373,'1607','INTERAÇÃO SOCIAL E TRANSPARÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (37101,374,'2612','GESTÃO DA CONTROLADORIA GERAL DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (37101,375,'2676','MODERNIZAÇÃO DA CONTROLADORIA GERAL DO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (37101,376,'2699','PREVENÇÃO E COMBATE À CORRUPÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,377,'2040','AÇÕES DE ATENÇÃO À SAÚDE DA PESSOA COM DEFICIÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,378,'2435','APOIO TEÉCNICO E FINANCEIRO ÀS ENTIDADES SEM FINS LUCRATIVOS QUE ATENDEM AS PESSOAS COM DEFICIÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,379,'2535','COORDENAÇÃO GERAL DA SEID',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,380,'2598','FORTALECIMENTO DA REDE DE PROTEÇÃO SOCIAL VISANDO À AMPLIAÇÃO E QUALIFICAÇÃO DAS MEDIDAS SOCIOASSISTENCIAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,381,'2611','GARANTIA DO ACESSO E DA PERMANÊNCIA DA PESSOA COM DEFICIÊNCIA A UMA EDUCAÇÃO QUE FAVOREÇA O SEU PLENO DESENVOLVIMENTO E SUA INCLUSÃO SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,382,'2639','IMPLEMENTAÇÃO DA ACESSIBILIDADE NO DESENHO UNIVERSAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,383,'2646','IMPLEMENTAÇÃO DO PLANO ESTADUAL PIAUÍ VIVER SEM LIMITE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,384,'2680','MODERNIZAÇÃO DA GESTÃO DA SEID',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,385,'2712','PROMOÇÃO DO ACESSO DAS PESSOAS COM DEFICIÊNCIA AO MERCADO DE TRABALHO FORMAL, DE GERAÇÃO DE RENDA E DE EMPREENDEDORISMO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38101,386,'2723','REESTRUTURAÇÃO DO ESPAÇO FÍSICO E MODERNIZAÇÃO DA NOVA SEDE DA SEID',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38102,387,'2599','FORTALECIMENTO DAS INSTÂNCIAS COLEGIADAS DE DEFESA DOS DIREITOS DAS PESSOAS COM DEFICIÊNCIA NOS MUNICÍPIOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (38102,388,'2640','IMPLEMENTAÇÃO DA POLÍTICA DE ATENDIMENTO À PESSOA COM DEFICIÊNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (44101,389,'2481','CONSTRUÇÃO, MODERNIZAÇÃO E AMPLIAÇÃO DO SISTEMA OPERACIONAL E INTEGRAÇÃO BOMBEIRO E SOCIEDADE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (44101,390,'2546','COORDENAÇÃO GERAL DO CORPO DE BOMBEIROS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,391,'1557','ELABORAÇÃO E EXECUÇÃO DE PROJETOS DE HABITAÇÃO DE INTERESSE SOCIAL EM ÁREAS URBANAS E RURAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,392,'2293','APOIAR OS MUNÍCIPIOS NA IMPLEMENTAÇÃO DE OBRAS URBANAS DE AMPLA RELEVÂNCIA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,393,'2590','FORTALECIMENTO DA COORDENAÇÃO GERAL DA SECID',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,394,'2629','IMPLANTAÇÃO DE ANÉIS VIÁRIOS NOS MUNICÍPIOS PIAUIENSES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,395,'2634','IMPLANTAÇÃO DE SISTEMA ADUTOR E OUTRAS OBRAS HÍDRICAS, EM ÁREAS URBANAS E RURAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,396,'2636','IMPLANTAÇÃO E EXECUÇÃO DE PAVIMENTAÇÃO COM PARALELEPÍPEDO, ESTRADA VICINAL E PAVIMENTAÇÃO ASFÁLTICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,397,'2644','IMPLEMENTAÇÃO DE INTERVENÇÕES NA ÁREA DE RESÍDUOS SÓLIDOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45101,398,'2734','SANEAMENTO BÁSICO NOS MUNICÍPIOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45201,399,'1546','COORDENAÇÃO GERAL DO DETRAN',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45201,400,'1612','MELHORIA NO TRÂNSITO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45201,401,'1615','MODERNIZAÇÃO ADMINISTRATIVA DO DETRAN',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,402,'2103','ACOMPANHAMENTO DO TRABALHO TÉCNICO SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,403,'2453','AUTOFINANCIAMENTO HABITACIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,404,'2474','CONSTRUÇÃO DE UNIDADES HABITACIONAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,405,'2495','COORDENAÇÃO GERAL DA ADH',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,406,'2609','FUNDO ESTADUAL DE INTERESSE SOCIAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,407,'2628','HABITAÇÃO PARA SERVIDORES PÚBLICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,408,'2672','MELHORIA HABITACIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,409,'2727','REGULARIZAÇÃO E AVERBAÇÃO FUNDIÁRIA HABITACIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45202,410,'2741','URBANIZAÇÃO E CONSTRUÇÃO DE EQUIPAMENTOS SOCIAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45203,411,'2563','ELABORAÇÃO E IMPLEMENTAÇÃO DE PROJETOS E ATIVIDADES DE ABASTECIMENTO DE ÁGUA POTÁVEL E ESGOTAMENTO SANITÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45203,412,'2619','GESTÃO DE RESÍDUOS SÓLIDOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (45203,413,'2621','GESTÃO DO INSTITUTO DE ÁGUAS E ESGOTOS DO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,414,'2469','CONSTRUÇÃO DA RODOVIA TRANSCERRADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,415,'2473','CONSTRUÇÃO DE RODOANEIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,416,'2490','CONTROLE E OPERAÇÃO DE TRÁFEGO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,417,'2627','GESTÃO MODERNA DA SECRETARIA DOS TRANSPORTES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,418,'2635','IMPLANTAÇÃO DO METRÔ DE TERESINA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,419,'2656','INFRAESTRUTURA DO MODAL AEROVIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,420,'2657','INFRAESTRUTURA DO MODAL FERROVIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,421,'2658','INFRAESTRUTURA DO MODAL HIDROVIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,422,'2659','INFRAESTRUTURA DO MODAL PORTUÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46101,423,'2660','INFRAESTRUTURA DO MODAL RODOVIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46201,424,'1514','ADMINISTRAÇÃO EFICIENTE DO DER-PI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46201,425,'1553','DESENVOLVIMENTO E OPERACIONALIDADE DA INFRAESTRUTURA RODOVIÁRIA E MOBILIDADE URBANA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46201,426,'1620','MODERNIZAÇÃO DA OPERACIONALIDADE DO DER-PI',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,427,'2204','AMPLIAÇÃO, MELHORIA E MANUTENÇÃO DO SISTEMA METROVIÁRIO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,428,'2496','COORDENAÇÃO GERAL DA CMTP',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,429,'2664','LINHA ALTOS PARNAÍBA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,430,'2690','MODERNIZAÇÃO E MELHORIA DE MATERIAL RODANTE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,431,'2703','PROGRAMA TREM REGIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,432,'2730','REQUALIFICAÇÃO FÍSICA E DE RECURSOS HUMANOS DA COMPANHIA METROPOLITANA DE TRANSPORTES PÚBLICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,433,'2742','VLT PARNAÍBA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (46202,434,'2743','VLT TERESINA - TIMON',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,435,'1541','COORDENAÇÃO GERAL DA SECRETARIA DE TURISMO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,436,'1568','FOMENTO AOS ROTEIROS E IMAGENS TURÍSTICAS DO ESTADO / PRODETUR NACIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,437,'1578','FORTALECIMENTO DA GESTÃO INSTITUCIONAL PARA O TURISMO / PRODETUR NACIONAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,438,'1579','FORTALECIMENTO DA GESTÃO MUNICIPAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,439,'1587','FORTALECIMENTO DO TURISMO SUSTENTÁVEL NO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,440,'1606','INFRAESTRUTURA TURÍSTICA E MELHORIA DOS SERVIÇOS TURÍSTICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (47101,441,'1624','MODERNIZAÇÃO DA SECRETARIA DO TURISMO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,442,'1552','DESENVOLVIMENTO EMPRESARIAL E INCENTIVO AO EMPREENDEDORISMO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,443,'1567','FOMENTO AO EMPREENDEDORISMO JOVEM NO SEMIÁRIDO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,444,'1597','GESTÃO, MANUTENÇÃO E AMPLIAÇÃO DA SETRE E SINE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,445,'1608','INTERMEDIAÇÃO DE MÃO DE OBRA /SINE',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,446,'1629','MONITORAMENTO E AVALIAÇÃO DE POLÍTICAS PÚBLICAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,447,'1642','PROTEÇÃO SOCIAL BÁSICA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48101,448,'1643','QUALIFICAÇÃO SOCIAL, PROFISSIONAL E EMPREENDEDORA / INTERMEDIAÇÃO DE MÃO DE OBRA COM CAPACITAÇÃO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48103,449,'1552','DESENVOLVIMENTO EMPRESARIAL E INCENTIVO AO EMPREENDEDORISMO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (48103,450,'1629','MONITORAMENTO E AVALIAÇÃO DE POLÍTICAS PÚBLICAS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,451,'2070','AÇÕES DE PREVENÇÃO DE DESASTRES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,452,'2476','CONSTRUÇÃO E RECUPERAÇÃO DE OBRAS ESTRUTURANTES RELACIONADAS A FENÔMENOS CLIMÁTICOS E DESASTRES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,453,'2532','COORDENAÇÃO GERAL DA SECRETARIA DE DEFESA CIVIL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (49101,454,'2722','RECUPERAÇÃO DOS DANOS CAUSADOS POR DESASTRES',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,455,'2462','CONSOLIDAÇÃO DA BASE DE DADOS DA MINERAÇÃO NO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,456,'2463','CONSOLIDAÇÃO DA BASE DE DADOS DO SETOR ENERGÉTICO NO PIAUÍ',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,457,'2464','CONSOLIDAÇÃO DA BASE LEGAL DE SUPORTE AOS NEGÓCIOS ENERGÉTICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,458,'2465','CONSOLIDAÇÃO DA BASE LEGAL DE SUPORTE AOS NEGÓCIOS MINERAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,459,'2626','GESTÃO GERAL DA SEMINPER',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,460,'2706','PROMOÇÃO DA PESQUISA, DESENVOLVIMENTO TECNOLÓGICO E INOVAÇÃO NO SETOR MINERAL',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,461,'2709','PROMOÇÃO DE NEGÓCIOS ENERGÉTICOS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50101,462,'2710','PROMOÇÃO DE NEGÓCIOS MINERAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (50201,463,'2558','DISTRIBUIÇÃO DE GÁS NATURAL ATRAVÉS DO GASODUTO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,464,'1549','CRIAÇÃO E ATUALIZAÇÃO DO MARCO LEGAL DO SISTEMA ESTADUAL DE CULTURA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,465,'2034','ACESSO UNIVERSALIZADO A BENS E EQUIPAMENTOS CULTURAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,466,'2531','COORDENAÇÃO GERAL DA SECRETARIA DA CULTURA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,467,'2550','CRIAÇÃO E APOIO NA IMPLANTAÇÃO DOS SISTEMAS MUNICIPAIS DE CULTURA',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,468,'2582','FOMENTO À CRIAÇÃO E A PRODUÇÃO DE BENS ARTÍSTICOS E CULTURAIS DAS DIVERSAS LINGUAGENS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,469,'2605','FORTALECIMENTO E AMPLIAÇÃO DO PROGRAMA CULTURA VIVA NO ESTADO',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,470,'2684','MODERNIZAÇÃO DA INFRAESTRUTURA E QUALIFICAÇÃO DOS GESTORES E AGENTES CULTURAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,471,'2717','PROTEÇÃO E PRESERVAÇÃO DOS BENS CULTURAIS E CONHECIMENTOS DOS POVOS E COMUNIDADES TRADICIONAIS',true);
insert into acaoestrategica(unidadeorcamentaria_id, id, codigo, nome, ativo) values (51101,472,'2719','REALIZAÇÃO E APOIO A EVENTOS CULTURAIS NOS TERRITÓRIOS DE DESENVOLVIMENTO',true);
