insert into elementodedespesa (id, codigo, nome, ativo) values (01,'01','Aposentadorias e Reformas',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (03,'03','Pensões',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (04,'04','Contratação por Tempo Determinado',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (05,'05','Outros Benefícios Previdenciários',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (06,'06','Benefício Mensal ao Deficiente e ao Idos',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (07,'07','Contribuição a Entidades Fechadas de Previdência',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (08,'08','Outros Benefícios Assistenciais',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (09,'09','Salários-Família',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (10,'10','Outros Benefícios de Natureza Social',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (11,'11','Vencimentos e Vantagens Fixas - Pessoal Civil',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (12,'12','Vencimentos e Vantagens Fixas - Pessoal Militar',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (13,'13','Obrigações Patronais',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (14,'14','Diárias - Civil',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (15,'15','Diárias - Militar',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (16,'16','Outras Despesas Variáveis - Pessoal Civil',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (17,'17','Outras Despesas Variáveis - Pessoal Militar',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (18,'18','Auxílio Financeiro a Estudantes',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (19,'19','Auxílio-Fardamento',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (20,'20','Auxílio Financeiro a Pesquisadores',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (21,'21','Juros sobre a Dívida por Contrato',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (22,'22','Outros Encargos sobre a Dívida por Contrato',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (23,'23','Juros, Deságio e Descontos da Dívida Mobiliária',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (24,'24','Outros Encargos sobre a Dívida Mobiliária',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (25,'25','Encargos sobre Operações de Crédito por Antecipação da Receita',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (26,'26','Obrigações decorrentes de Política Monetária',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (27,'27','Encargos pela Honra de Avais, Garantias, Seguros e Similares',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (28,'28','Remuneração de Cotas de Fundos Autárquicos',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (30,'30','Material de Consumo',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (31,'31','Premiações Culturais, Artísticas, Científicas, Desportivas e Outras',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (32,'32','Material de Distribuição Gratuita',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (33,'33','Passagens e Despesas com Locomoção',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (34,'34','Outras Despesas de Pessoal decorrentes de Contratos de Terceirização',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (35,'35','Serviços de Consultoria',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (36,'36','Outros Serviços de Terceiros - Pessoa Física',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (37,'37','Locação de Mão-de-Obra',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (38,'38','Arrendamento Mercantil',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (39,'39','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (41,'41','Contribuições',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (42,'42','Auxílios',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (43,'43','Subvenções Sociais',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (45,'45','Subvenções Econômicas',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (46,'46','Auxílio-Alimentação',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (47,'47','Obrigações Tributárias e Contributivas',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (48,'48','Outros Auxílios Financeiros a Pessoas Físicas',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (49,'49','Auxílio-Transporte',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (51,'51','Obras e Instalações',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (52,'52','Equipamentos e Material Permanente',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (61,'61','Aquisição de Imóveis',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (62,'62','Aquisição de Produtos para Revenda',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (63,'63','Aquisição de Títulos de Crédito',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (64,'64','Aquisição de Títulos Representativos de Capital já integralizado',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (65,'65','Constituição ou Aumento de Capital de Empresas',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (66,'66','Concessão de Empréstimos e Financiamentos',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (67,'67','Depósitos Compulsórios',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (71,'71','Principal da Dívida Contratual Resgatado',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (72,'72','Principal da Dívida Mobiliária Resgatado',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (73,'73','Correção Monetária ou Cambial da Dívida Contratual Resgatada',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (74,'74','Correção Monetária ou Cambial da Dívida Mobiliária Resgatada',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (75,'75','Correção Monetária da Dívida de Operações de Crédito por Antecipação da Receita',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (76,'76','Principal Corrigido da Dívida Mobiliária Refinanciada',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (77,'77','Principal Corrigido da Dívida Contratual Refinanciado',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (81,'81','Distribuição Constituicional ou Legal de Receitas',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (91,'91','Sentenças Judiciais',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (92,'92','Despesas de Exercícios Anteriores',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (93,'93','Indenizações e Restituições',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (94,'94','Indenizações e  Restituições Trabalhistas',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (95,'95','Indenização pela Execução de Trabalhos de Campo',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (96,'96','Ressarcimento de Despesas de Pessoal Requisitado',true);
insert into elementodedespesa (id, codigo, nome, ativo) values (99,'99','Reserva de Contingência',true);
