insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (100,'100','RECURSOS ORDINÁRIOS','RECURSOS ORDINÁRIOS','ORDINARIAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (110,'110','RECURSOS DE CONVÊNIO ','RECURSOS DE CONVÊNIO ','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (111,'111','COTA-PARTE DO ESTADO NA RECEITA DA CIDE','COTA-PARTE DO ESTADO NA RECEITA DA CIDE','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (112,'112','RECURSOS DE CONVÊNIOS DE CAPITAL','RECURSOS DE CONVÊNIOS DE CAPITAL','ORDINARIAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (113,'113','RECURSOS DO SUS','RECURSOS DO SUS','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (114,'114','RECURSOS DO FNDE','RECURSOS DO FNDE','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (115,'115','VALORIZAÇÃO DO ENSINO','VALORIZAÇÃO DO ENSINO','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (116,'116','OPERAÇÃO DE CRÉDITO INTERNA','OPERAÇÃO DE CRÉDITO INTERNA','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (117,'117','OPERAÇÃO DE CRÉDITO EXTERNA','OPERAÇÃO DE CRÉDITO EXTERNA','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (118,'118','RECURSOS DOS FUNDOS ESPECIAIS','RECURSOS DOS FUNDOS ESPECIAIS','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (119,'119','RECURSOS DO FUNDO DE PREVIDÊNCIA','RECURSOS DO FUNDO DE PREVIDÊNCIA','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (120,'120','RECURSOS DO FECOP','RECURSOS DO FECOP','ORDINARIAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (121,'121','RECURSOS DO FUNDO INTEGRADO DE BENS, DIREITOS E ATIVOS DA PREVIDÊNCIA','RECURSOS DO FUNDO INTEGRADO DE BENS, DIREITOS E ATIVOS DA PR','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (122,'122','FUNDOS CONSTITUCIONAIS OU ADMINISTRADOS PELA UNIÃO','FUNDOS CONSTITUCIONAIS OU ADMINISTRADOS PELA UNIÃO','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (146,'146','OPERACOES DE CREDITOS INTERNAS - ADM.DIRETA','OPERACOES DE CREDITOS INTERNAS - ADM.DIRETA','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (210,'210','RECURSOS DE CONVÊNIO','RECURSOS DE CONVÊNIO','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (212,'212','RECURSOS DE CONVÊNIOS DE CAPITAL','RECURSOS DE CONVÊNIOS DE CAPITAL','ORDINARIAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (213,'213','RECURSOS DO SUS','RECURSOS DO SUS','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (214,'214','RECURSOS DO FNDE','RECURSOS DO FNDE','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (215,'215','VALORIZAÇÃO DO ENSINO','VALORIZAÇÃO DO ENSINO','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (216,'216','OPERAÇÃO DE CRÉDITO INTERNA','OPERAÇÃO DE CRÉDITO INTERNA','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (217,'217','OPERAÇÃO DE CRÉDITO EXTERNA','OPERAÇÃO DE CRÉDITO EXTERNA','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (218,'218','RECURSOS DOS FUNDOS ESPECIAIS','RECURSOS DOS FUNDOS ESPECIAIS','VINCULADAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (219,'219','RECURSOS DO FUNDO DE PREVIDÊNCIA','RECURSOS DO FUNDO DE PREVIDÊNCIA','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (220,'220','RECURSOS DO FECOP','RECURSOS DO FECOP','ORDINARIAS',false);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (221,'221','RECURSOS DO FUNDO INTEGRADO DE BENS, DIREITOS E ATIVOS DA PREVIDÊNCIA','RECURSOS DO FUNDO INTEGRADO DE BENS, DIREITOS E ATIVOS DA PR','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (222,'222','RECURSOS DO IASP E DO PLAMTA','RECURSOS DO IASP E DO PLAMTA','VINCULADAS',true);
insert into fontederecurso (id, codigo, nome, mnemonico, tipofonte, ativo) values (999,'999','A definir','A definir','VINCULADAS',false);
