insert into funcao (id, codigo, nome, ativo) values (01,'01','LEGISLATIVA',true);
insert into funcao (id, codigo, nome, ativo) values (02,'02','JUDICIÁRIA',true);
insert into funcao (id, codigo, nome, ativo) values (03,'03','ESSENCIAL  À JUSTIÇA',true);
insert into funcao (id, codigo, nome, ativo) values (04,'04','ADMINISTRAÇÃO',true);
insert into funcao (id, codigo, nome, ativo) values (05,'05','DEFESA NACIONAL',true);
insert into funcao (id, codigo, nome, ativo) values (06,'06','SEGURANÇA PÚBLICA',true);
insert into funcao (id, codigo, nome, ativo) values (07,'07','RELAÇÕES EXTERIORES',true);
insert into funcao (id, codigo, nome, ativo) values (08,'08','ASSISTÊNCIA SOCIAL',true);
insert into funcao (id, codigo, nome, ativo) values (09,'09','PREVIDÊNCIA SOCIAL',true);
insert into funcao (id, codigo, nome, ativo) values (10,'10','SAÚDE',true);
insert into funcao (id, codigo, nome, ativo) values (11,'11','TRABALHO',true);
insert into funcao (id, codigo, nome, ativo) values (12,'12','EDUCAÇÃO',true);
insert into funcao (id, codigo, nome, ativo) values (13,'13','CULTURA',true);
insert into funcao (id, codigo, nome, ativo) values (14,'14','DIREITOS DA CIDADANIA',true);
insert into funcao (id, codigo, nome, ativo) values (15,'15','URBANISMO',true);
insert into funcao (id, codigo, nome, ativo) values (16,'16','HABITAÇÃO',true);
insert into funcao (id, codigo, nome, ativo) values (17,'17','SANEAMENTO',true);
insert into funcao (id, codigo, nome, ativo) values (18,'18','GESTÃO AMBIENTAL',true);
insert into funcao (id, codigo, nome, ativo) values (19,'19','CIÊNCIA E TECNOLOGIA',true);
insert into funcao (id, codigo, nome, ativo) values (20,'20','AGRICULTURA',true);
insert into funcao (id, codigo, nome, ativo) values (21,'21','ORGANIZAÇÃO AGRÁRIA',true);
insert into funcao (id, codigo, nome, ativo) values (22,'22','INDÚSTRIA',true);
insert into funcao (id, codigo, nome, ativo) values (23,'23','COMÉRCIO E SERVIÇOS',true);
insert into funcao (id, codigo, nome, ativo) values (24,'24','COMUNICAÇÕES',true);
insert into funcao (id, codigo, nome, ativo) values (25,'25','ENERGIA',true);
insert into funcao (id, codigo, nome, ativo) values (26,'26','TRANSPORTE',true);
insert into funcao (id, codigo, nome, ativo) values (27,'27','DESPORTO E LAZER',true);
insert into funcao (id, codigo, nome, ativo) values (28,'28','ENCARGOS ESPECIAIS',true);
insert into funcao (id, codigo, nome, ativo) values (98,'98','A CLASSIFICAR',true);
insert into funcao (id, codigo, nome, ativo) values (99,'99','RESERVA DE CONTINGÊNCIA',true);
