insert into naturezadedespesa (id, codigo, nome, ativo) values (313041,'313041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (317111,'317111','Vencimentos e Vantagens Fixas - Pessoal Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (317113,'317113','Obrigações Patronais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (318004,'318004','Contratação por Tempo Determinado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (318034,'318034','Outras Despesas de Pessoal decorrentes de Contratos de Terceirização',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319001,'319001','Aposentadorias e Reformas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319003,'319003','Pensões',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319004,'319004','Contratação por Tempo Determinado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319007,'319007','Contribuição a Entidades Fechadas de Previdência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319009,'319009','Salários-Família',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319010,'319010','Outros Benefícios de Natureza Social',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319011,'319011','Vencimentos e Vantagens Fixas - Pessoal Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319012,'319012','Vencimentos e Vantagens Fixas - Pessoal Militar',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319013,'319013','Obrigações Patronais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319016,'319016','Outras Despesas Variáveis - Pessoal Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319017,'319017','Outras Despesas Variáveis - Pessoal Militar',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319034,'319034','Outras Despesas de Pessoal decorrentes de Contratos de Terceirização',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319035,'319035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319067,'319067','Depósitos Compulsórios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319091,'319091','Sentenças Judiciais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319092,'319092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319093,'319093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319094,'319094','Indenizações e  Restituições Trabalhistas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319096,'319096','Ressarcimento de Despesas de Pessoal Requisitado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319107,'319107','Contribuição a Entidades Fechadas de Previdência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319113,'319113','Obrigações Patronais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319192,'319192','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (319999,'319999','Reserva de Contingência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329021,'329021','Juros sobre a Dívida por Contrato',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329022,'329022','Outros Encargos sobre a Dívida por Contrato',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329023,'329023','Juros, Deságio e Descontos da Dívida Mobiliária',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329024,'329024','Outros Encargos sobre a Dívida Mobiliária',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329025,'329025','Encargos sobre Operações de Crédito por Antecipação da Receita',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329091,'329091','Sentenças Judiciais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329092,'329092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329093,'329093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329121,'329121','Juros sobre a Dívida por Contrato',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329122,'329122','Outros Encargos sobre a Dívida por Contrato',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (329999,'329999','Reserva de Contingência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332001,'332001','Aposentadorias e Reformas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332014,'332014','Diárias - Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332030,'332030','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332035,'332035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332036,'332036','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332039,'332039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332041,'332041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332092,'332092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (332093,'332093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333014,'333014','Diárias - Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333030,'333030','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333035,'333035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333036,'333036','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333039,'333039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333041,'333041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333043,'333043','Subvenções Sociais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333081,'333081','Distribuição Constituicional ou Legal de Receitas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333092,'333092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (333093,'333093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334030,'334030','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334035,'334035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334036,'334036','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334039,'334039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334041,'334041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334042,'334042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334043,'334043','Subvenções Sociais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334051,'334051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334081,'334081','Distribuição Constituicional ou Legal de Receitas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334092,'334092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334093,'334093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (334141,'334141','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335030,'335030','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335035,'335035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335036,'335036','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335039,'335039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335041,'335041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335043,'335043','Subvenções Sociais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335047,'335047','Obrigações Tributárias e Contributivas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335048,'335048','Outros Auxílios Financeiros a Pessoas Físicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (335092,'335092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (336041,'336041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (336045,'336045','Subvenções Econômicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (336048,'336048','Outros Auxílios Financeiros a Pessoas Físicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337041,'337041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337092,'337092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337114,'337114','Diárias - Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337130,'337130','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337133,'337133','Passagens e Despesas com Locomoção',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337135,'337135','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337136,'337136','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337137,'337137','Locação de Mão-de-Obra',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337139,'337139','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337141,'337141','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (337192,'337192','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338004,'338004','Contratação por Tempo Determinado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338014,'338014','Diárias - Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338030,'338030','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338033,'338033','Passagens e Despesas com Locomoção',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338035,'338035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338036,'338036','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338037,'338037','Locação de Mão-de-Obra',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338039,'338039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338041,'338041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (338092,'338092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339001,'339001','Aposentadorias e Reformas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339003,'339003','Pensões',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339004,'339004','Contratação por Tempo Determinado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339005,'339005','Outros Benefícios Previdenciários',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339006,'339006','Benefício Mensal ao Deficiente e ao Idos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339008,'339008','Outros Benefícios Assistenciais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339009,'339009','Salários-Família',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339010,'339010','Outros Benefícios de Natureza Social',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339013,'339013','Obrigações Patronais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339014,'339014','Diárias - Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339015,'339015','Diárias - Militar',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339016,'339016','Outras Despesas Variáveis - Pessoal Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339017,'339017','Outras Despesas Variáveis - Pessoal Militar',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339018,'339018','Auxílio Financeiro a Estudantes',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339019,'339019','Auxílio-Fardamento',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339020,'339020','Auxílio Financeiro a Pesquisadores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339022,'339022','Outros Encargos sobre a Dívida por Contrato',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339026,'339026','Obrigações decorrentes de Política Monetária',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339027,'339027','Encargos pela Honra de Avais, Garantias, Seguros e Similares',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339028,'339028','Remuneração de Cotas de Fundos Autárquicos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339030,'339030','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339031,'339031','Premiações Culturais, Artísticas, Científicas, Desportivas e Outras',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339032,'339032','Material de Distribuição Gratuita',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339033,'339033','Passagens e Despesas com Locomoção',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339034,'339034','Outras Despesas de Pessoal decorrentes de Contratos de Terceirização',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339035,'339035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339036,'339036','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339037,'339037','Locação de Mão-de-Obra',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339038,'339038','Arrendamento Mercantil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339039,'339039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339041,'339041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339043,'339043','Subvenções Sociais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339045,'339045','Subvenções Econômicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339046,'339046','Auxílio-Alimentação',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339047,'339047','Obrigações Tributárias e Contributivas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339048,'339048','Outros Auxílios Financeiros a Pessoas Físicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339049,'339049','Auxílio-Transporte',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339067,'339067','Depósitos Compulsórios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339091,'339091','Sentenças Judiciais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339092,'339092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339093,'339093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339094,'339094','Indenizações e  Restituições Trabalhistas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339095,'339095','Indenização pela Execução de Trabalhos de Campo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339139,'339139','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339141,'339141','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339192,'339192','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (339999,'339999','Reserva de Contingência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (442041,'442041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (442042,'442042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (442051,'442051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (442052,'442052','Equipamentos e Material Permanente',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (442092,'442092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (442093,'442093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (443041,'443041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (443042,'443042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (443051,'443051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (443052,'443052','Equipamentos e Material Permanente',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (443092,'443092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (443093,'443093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444041,'444041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444042,'444042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444045,'444045','Subvenções Econômicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444051,'444051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444052,'444052','Equipamentos e Material Permanente',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444092,'444092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444093,'444093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (444141,'444141','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (445039,'445039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (445041,'445041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (445042,'445042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (445051,'445051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (445052,'445052','Equipamentos e Material Permanente',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (445092,'445092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (446041,'446041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (446045,'446045','Subvenções Econômicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (446051,'446051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (446066,'446066','Concessão de Empréstimos e Financiamentos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (447041,'447041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (447042,'447042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (447142,'447142','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (447151,'447151','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (447152,'447152','Equipamentos e Material Permanente',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (448041,'448041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (448042,'448042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (448051,'448051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (448052,'448052','Equipamentos e Material Permanente',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449004,'449004','Contratação por Tempo Determinado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449014,'449014','Diárias - Civil',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449017,'449017','Outras Despesas Variáveis - Pessoal Militar',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449018,'449018','Auxílio Financeiro a Estudantes',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449020,'449020','Auxílio Financeiro a Pesquisadores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449030,'449030','Material de Consumo',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449032,'449032','Material de Distribuição Gratuita',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449033,'449033','Passagens e Despesas com Locomoção',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449034,'449034','Outras Despesas de Pessoal decorrentes de Contratos de Terceirização',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449035,'449035','Serviços de Consultoria',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449036,'449036','Outros Serviços de Terceiros - Pessoa Física',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449037,'449037','Locação de Mão-de-Obra',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449039,'449039','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449041,'449041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449045,'449045','Subvenções Econômicas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449047,'449047','Obrigações Tributárias e Contributivas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449051,'449051','Obras e Instalações',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449052,'449052','Equipamentos e Material Permanente',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449061,'449061','Aquisição de Imóveis',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449062,'449062','Aquisição de Produtos para Revenda',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449091,'449091','Sentenças Judiciais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449092,'449092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449093,'449093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449139,'449139','Outros Serviços de Terceiros - Pessoa Jurídica',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (449999,'449999','Reserva de Contingência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (453041,'453041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (453042,'453042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (453061,'453061','Aquisição de Imóveis',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (453064,'453064','Aquisição de Títulos Representativos de Capital já integralizado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (453065,'453065','Constituição ou Aumento de Capital de Empresas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (453066,'453066','Concessão de Empréstimos e Financiamentos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (454041,'454041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (454042,'454042','Auxílios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (454064,'454064','Aquisição de Títulos Representativos de Capital já integralizado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (454066,'454066','Concessão de Empréstimos e Financiamentos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (455066,'455066','Concessão de Empréstimos e Financiamentos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (456066,'456066','Concessão de Empréstimos e Financiamentos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (458066,'458066','Concessão de Empréstimos e Financiamentos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459041,'459041','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459061,'459061','Aquisição de Imóveis',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459062,'459062','Aquisição de Produtos para Revenda',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459063,'459063','Aquisição de Títulos de Crédito',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459064,'459064','Aquisição de Títulos Representativos de Capital já integralizado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459065,'459065','Constituição ou Aumento de Capital de Empresas',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459066,'459066','Concessão de Empréstimos e Financiamentos',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459067,'459067','Depósitos Compulsórios',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459091,'459091','Sentenças Judiciais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459092,'459092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459093,'459093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459141,'459141','Contribuições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (459999,'459999','Reserva de Contingência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469071,'469071','Principal da Dívida Contratual Resgatado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469072,'469072','Principal da Dívida Mobiliária Resgatado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469073,'469073','Correção Monetária ou Cambial da Dívida Contratual Resgatada',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469074,'469074','Correção Monetária ou Cambial da Dívida Mobiliária Resgatada',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469075,'469075','Correção Monetária da Dívida de Operações de Crédito por Antecipação da Receita',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469076,'469076','Principal Corrigido da Dívida Mobiliária Refinanciada',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469077,'469077','Principal Corrigido da Dívida Contratual Refinanciado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469091,'469091','Sentenças Judiciais',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469092,'469092','Despesas de Exercícios Anteriores',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469093,'469093','Indenizações e Restituições',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469171,'469171','Principal da Dívida Contratual Resgatado',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (469999,'469999','Reserva de Contingência',true);
insert into naturezadedespesa (id, codigo, nome, ativo) values (999999,'999999','Reserva de Contingência',true);
