insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (01,'01','ASSEMBLEIA LEGISLATIVA',null,'LEGISLATIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (02,'02','TRIBUNAL DE CONTAS DO ESTADO',null,'LEGISLATIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (04,'04','TRIBUNAL DE JUSTIÇA',null,'JUDICIARIO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (09,'09','TESOURO ESTADUAL','TESOURO ESTADUAL','EXECUTIVO',null,false);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (11,'11','GOVERNADORIA DO ESTADO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (12,'12','SECRETARIA DA SEGURANÇA PÚBLICA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (13,'13','SECRETARIA DA FAZENDA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (14,'14','SECRETARIA DA EDUCAÇÃO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (15,'15','SECRETARIA DO DESENVOLVIMENTO RURAL',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (16,'16','SECRETARIA DA INFRAESTRUTURA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (17,'17','SECRETARIA DA SAÚDE',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (19,'19','SECRETARIA DO PLANEJAMENTO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (20,'20','SECRETARIA DO DESENVOLVIMENTO ECONÔMICO E TECNOLÓGICO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (21,'21','SECRETARIA DA ADMINISTRAÇÃO E PREVIDÊNCIA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (22,'22','SECRETARIA DA JUSTIÇA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (24,'24','ENCARGOS GERAIS DO ESTADO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (25,'25','MINISTÉRIO PÚBLICO',null,'MINISTERIO_PUBLICO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (26,'26','POLÍCIA MILITAR DO PIAUÍ',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (28,'28','SECRETARIA DO MEIO AMBIENTE E DOS RECURSOS HÍDRICOS',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (30,'30','SECRETARIA DA ASSISTÊNCIA SOCIAL E CIDADANIA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (33,'33','COORDENADORIA DE COMUNICAÇÃO SOCIAL',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (35,'35','DEFENSORIA PÚBLICA DO ESTADO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (36,'36','PROCURADORIA GERAL DO ESTADO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (37,'37','CONTROLADORIA GERAL DO ESTADO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (38,'38','SECRETARIA ESTADUAL PARA INCLUSÃO DA PESSOA COM DEFICIÊNCIA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (39,'39','RESERVA DE CONTINGÊNCIA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (40,'40','COORDENADORIA DE SEGURANÇA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (44,'44','CORPO DE BOMBEIROS MILITAR',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (45,'45','SECRETARIA DAS CIDADES',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (46,'46','SECRETARIA DOS TRANSPORTES',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (47,'47','SECRETARIA DO TURISMO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (48,'48','SECRETARIA DO TRABALHO E EMPREENDEDORISMO',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (49,'49','SECRETARIA DE DEFESA CIVIL',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (50,'50','SECRETARIA ESTADUAL DE MINERAÇÃO, PETRÓLEO E ENERGIAS RENOVÁVEIS',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (51,'51','SECRETARIA DA CULTURA',null,'EXECUTIVO',null,true);
insert into orgao  (id, codigo, nome, sigla, poder, orgaosuperior_id, ativo) values (90,'90','TESOURO ESTADUAL',null,'EXECUTIVO',null,true);
