insert into programadegoverno (id, codigo, nome, poder, ativo) values (0001,'0001','GESTÃO MODERNA ORIENTADA PARA RESULTADOS','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0002,'0002','MODERNIZAÇÃO TECNOLÓGICA DO ESTADO DO PIAUÍ','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0003,'0003','SAÚDE PÚBLICA COM ACESSO E QUALIDADE PARA TODOS','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0004,'0004','ASSISTÊNCIA, INCLUSÃO SOCIAL E GARANTIA DE DIREITOS','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0005,'0005','GARANTIA DOS DIREITOS E INCLUSÃO DA PESSOA COM DEFICIÊNCIA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0006,'0006','PIAUÍ, SEGURANÇA E CIDADANIA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0007,'0007','PIAUÍ COM SEGURANÇA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0008,'0008','JUSTIÇA COM EDUCAÇÃO, TRABALHO E HUMANIZAÇÃO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0009,'0009','GESTÃO DE RISCOS E RESPOSTA A DESASTRES','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0010,'0010','UNIVERSIDADE DE QUALIDADE PARA TODOS','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0011,'0011','FORTALECIMENTO E EXPANSÃO DA EDUCAÇÃO PROFISSIONAL','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0012,'0012','EDUCAÇÃO E DESENVOLVIMENTO SOCIAL INCLUSIVO E SUSTENTÁVEL','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0013,'0013','DESENVOLVIMENTO DO ESPORTE EDUCACIONAL, DE LAZER E RENDIMENTO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0014,'0014','CULTURA: PROMOÇÃO, PRESERVAÇÃO E ACESSO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0015,'0015','CIÊNCIA, TECNOLOGIA E INOVAÇÃO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0016,'0016','TURISMO E SUSTENTABILIDADE','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0017,'0017','PIAUÍ SUSTENTÁVEL','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0018,'0018','MORADIA DIGNA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0019,'0019','SANEAMENTO, DIREITO DE TODOS','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0020,'0020','DESENVOLVIMENTO E INTEGRAÇÃO DOS TRANSPORTES E LOGÍSTICA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0021,'0021','INFRAESTRUTURA E QUALIDADE DE VIDA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0022,'0022','PIAUÍ PRODUTIVO E SUSTENTÁVEL - AGRICULTURA FAMILIAR','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0023,'0023','PIAUÍ PRODUTIVO E SUSTENTÁVEL - AGRONEGÓCIO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0024,'0024','TERRA PARA QUEM PRODUZ','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0025,'0025','VIVER BEM NO SEMIÁRIDO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0026,'0026','QUALIFICAÇÃO, TRABALHO E RENDA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0027,'0027','AVANÇA PIAUÍ','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0028,'0028','ENERGIAS RENOVÁVEIS PARA O DESENVOLVIMENTO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0029,'0029','MINERAÇÃO PARA O DESENVOLVIMENTO SUSTENTÁVEL','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0030,'0030','TRÂNSITO SEGURO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0031,'0031','VIVA SEM DROGAS','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0032,'0032','JOVEM É PARA VIVER','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0033,'0033','MAIS MULHER','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0034,'0034','ATIVO VERDE','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0080,'0080','GESTÃO E MANUTENÇÃO DO PODER LEGISLATIVO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0081,'0081','GESTÃO EFICIENTE E TRANSPARENTE DO PODER JUDICIÁRIO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0082,'0082','GESTÃO E MANUTENÇÃO DO MINISTÉRIO PÚBLICO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0083,'0083','DEFESA DA SOCIEDADE','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0084,'0084','FISCALIZAÇÃO FINANCEIRA E ORÇAMENTÁRIA EXTERNA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0085,'0085','INFRAESTRUTURA, TECNOLOGIA E INOVAÇÃO DO PODER JUDICIÁRIO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0086,'0086','JUSTIÇA E CIDADANIA','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0090,'0090','GESTÃO E MANUTENÇÃO DO PODER EXECUTIVO','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0091,'0091','ENCARGOS DE NATUREZA ESPECIAL','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0092,'0092','PREVIDÊNCIA SOCIAL DO SERVIDOR','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0093,'0093','SAÚDE DO SERVIDOR','EXECUTIVO',true);
insert into programadegoverno (id, codigo, nome, poder, ativo) values (0099,'0099','RESERVA DE CONTINGÊNCIA','EXECUTIVO',true);
