insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (01,'01','GESTAO MODERNA ORIENTADA PARA RESULTADOS','DIRETRIZ_IV','TEMATICO',6,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (02,'02','MODERNIZAÇÃO TECNOLÓGICA DO ESTADO DO PIAUÍ','DIRETRIZ_I','TEMATICO',6,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (03,'03','SAÚDE PÚBLICA COM ACESSO E QUALIDADE PARA TODOS','DIRETRIZ_I','TEMATICO',8,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (04,'04','ASSISTÊNCIA, INCLUSÃO SOCIAL E GARANTIA DE DIREITOS','DIRETRIZ_I','TEMATICO',8,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (05,'05','GARANTIA DOS DIREITOS E INCLUSÃO DA PESSOA COM DEFICIÊNCIA','DIRETRIZ_I','TEMATICO',8,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (06,'06','PIAUÍ, SEGURANÇA E CIDADANIA','DIRETRIZ_I','TEMATICO',9,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (07,'07','PIAUÍ COM SEGURANÇA','DIRETRIZ_I','TEMATICO',9,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (08,'08','JUSTIÇA COM EDUCAÇÃO, TRABALHO E HUMANIZAÇÃO','DIRETRIZ_I','TEMATICO',9,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (09,'09','GESTAO DE RISCOS E RESPOSTA A DESASTRES','DIRETRIZ_I','TEMATICO',9,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (10,'10','UNIVERSIDADE DE QUALIDADE PARA TODOS','DIRETRIZ_I','TEMATICO',3,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (11,'11','FORTALECIMENTO E EXPANSÃO DA EDUCAÇÃO PROFISSIONAL','DIRETRIZ_I','TEMATICO',3,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (12,'12','EDUCAÇÃO E DESENVOLVIMENTO SOCIAL INCLUSIVO E SUSTENTÁVEL','DIRETRIZ_I','TEMATICO',3,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (13,'13','DESENVOLVIMENTO DO ESPORTE EDUCACIONAL, DE LAZER E RENDIMENTO','DIRETRIZ_I','TEMATICO',3,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (14,'14','CULTURA: PROMOÇÃO, PRESERVAÇÃO E ACESSO','DIRETRIZ_I','TEMATICO',3,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (15,'15','CIÊNCIA, TECNOLOGIA E INOVAÇÃO','DIRETRIZ_I','TEMATICO',3,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (16,'16','TURISMO E SUSTENTABILIDADE','DIRETRIZ_II','TEMATICO',1,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (17,'17','PIAUÍ SUSTENTÁVEL','DIRETRIZ_II','TEMATICO',7,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (18,'18','MORADIA DIGNA','DIRETRIZ_III','TEMATICO',4,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (19,'19','SANEAMENTO, DIREITO DE TODOS','DIRETRIZ_III','TEMATICO',5,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (20,'20','DESENVOLVIMENTO E INTEGRAÇÃO DOS TRANSPORTES E LOGÍSTICA','DIRETRIZ_III','TEMATICO',5,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (21,'21','INFRAESTRUTURA E QUALIDADE DE VIDA','DIRETRIZ_III','TEMATICO',5,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (22,'22','PIAUÍ PRODUTIVO E SUSTENTÁVEL - AGRICULTURA FAMILIAR','DIRETRIZ_II','TEMATICO',2,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (23,'23','PIAUÍ PRODUTIVO E SUSTENTÁVEL - AGRONEGÓCIO','DIRETRIZ_II','TEMATICO',2,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (24,'24','TERRA PARA QUEM PRODUZ','DIRETRIZ_II','TEMATICO',2,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (25,'25','VIVER BEM NO SEMIÁRIDO','DIRETRIZ_II','TEMATICO',2,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (26,'26','QUALIFICAÇÃO, TRABALHO E RENDA','DIRETRIZ_II','TEMATICO',1,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (27,'27','AVANÇA PIAUÍ','DIRETRIZ_II','TEMATICO',1,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (28,'28','ENERGIAS RENOVÁVEIS PARA O DESENVOLVIMENTO','DIRETRIZ_II','TEMATICO',1,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (29,'29','MINERAÇÃO PARA O DESENVOLVIMENTO SUSTENTÁVEL','DIRETRIZ_II','TEMATICO',1,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (30,'30','TRÂNSITO SEGURO','DIRETRIZ_I','TEMATICO',5,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (31,'31','VIVA SEM DROGAS','DIRETRIZ_I','TEMATICO',8,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (32,'32','JOVEM É PARA VIVER','DIRETRIZ_I','TEMATICO',4,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (33,'33','MAIS MULHER','DIRETRIZ_I','TEMATICO',4,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (34,'34','ATIVO VERDE','DIRETRIZ_II','TEMÁTIMO',1,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (80,'80','GESTAO E MANUTENÇÃO DO PODER LEGISLATIVO','DIRETRIZ_IV','GESTAO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (81,'81','GESTAO EFICIENTE E TRANSPARENTE DO PODER JUDICIÁRIO','DIRETRIZ_IV','GESTAO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (82,'82','GESTAO E MANUTENÇÃO DO MINISTÉRIO PÚBLICO','DIRETRIZ_IV','GESTAO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (83,'83','DEFESA DA SOCIEDADE','DIRETRIZ_IV','TEMATICO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (84,'84','FISCALIZAÇÃO FINANCEIRA E ORÇAMENTÁRIA EXTERNA','DIRETRIZ_IV','TEMATICO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (85,'85','INFRAESTRUTURA, TECNOLOGIA E INOVAÇÃO DO PODER JUDICIÁRIO','DIRETRIZ_IV','TEMATICO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (86,'86','JUSTIÇA E CIDADANIA','DIRETRIZ_I','TEMATICO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (90,'90','GESTAO E MANUTENÇÃO DO PODER EXECUTIVO','DIRETRIZ_IV','GESTAO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (91,'91','ENCARGOS DE NATUREZA ESPECIAL','DIRETRIZ_IV','GESTAO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (92,'92','PREVIDÊNCIA SOCIAL DO SERVIDOR','DIRETRIZ_IV','GESTAO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (93,'93','SAÚDE DO SERVIDOR','DIRETRIZ_IV','GESTAO',null,true);
insert into programadegoverno (id, codigo, nome, diretriz, tipo, areatematica_id, ativo) values (99,'99','RESERVA DE CONTINGÊNCIA','DIRETRIZ_IV','GESTAO',null,true);
