insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (031,'031','AÇÃO LEGISLATIVA',1,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (032,'032','CONTROLE EXTERNO',1,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (061,'061','AÇÃO JUDICIÁRIA',2,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (062,'062','DEFESA DO INTERESSE PÚBLICO NO PROCESSO JUDICIÁRIO',2,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (091,'091','DEFESA DA ORDEM JUDICIÁRIA',3,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (092,'092','REPRESENTAÇÃO  JUDICIAL E EXTRAJUDICIAL',3,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (121,'121','PLANEJAMENTO E ORÇAMENTO',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (122,'122','ADMINISTRAÇÃO GERAL',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (123,'123','ADMINISTRAÇÃO  FINANCEIRA',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (124,'124','CONTROLE INTERNO',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (125,'125','NORMATIZAÇÃO  E FISCALIZAÇÃO',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (126,'126','TECNOLOGIA DA  INFORMAÇÃO',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (127,'127','ORDENAMENTO TERRITORIAL',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (128,'128','FORMAÇÃO DE RECURSOS HUMANOS',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (129,'129','ADMINISTRAÇÃO  DE RECEITAS',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (130,'130','ADMINISTRAÇÃO DE CONCESSÕES',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (131,'131','COMUNICAÇÃO  SOCIAL',4,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (151,'151','DEFESA AÉREA',5,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (152,'152','DEFESA NACIONAL',5,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (153,'153','DEFESA TERRESTRE',5,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (181,'181','POLICIAMENTO',6,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (182,'182','DEFESA CIVIL',6,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (183,'183','INFORMAÇÃO E INTELIGÊNCIA',6,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (211,'211','RELAÇÕES DIPLOMÁTICAS',7,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (212,'212','COOPERAÇÃO INTERNACIONAL',7,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (241,'241','ASSISTÊNCIA AO IDOSO',8,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (242,'242','ASSISTÊNCIA AO PORTADOR DE DEFICIÊNCIA',8,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (243,'243','ASSISTENCIA A CRIANÇA E AO ADOLESCENTE',8,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (244,'244','ASSISTENCIA COMUNITÁRIA',8,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (271,'271','PREVIDÊNCIA BÁSICA',9,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (272,'272','PREVIDÊNCIA DO REGIME ESTATUTÁRIO',9,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (273,'273','PREVIDÊNCIA COMPLEMENTAR',9,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (274,'274','PREVIDÊNCIA ESPECIAL',9,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (301,'301','ATENÇÃO BÁSICA',10,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (302,'302','ASSISTÊNCIA  HOSPITALAR E AMBULATORIAL',10,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (303,'303','SUPORTE PROFILÁTICO E TERAPÊUTICO',10,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (304,'304','VIGILÂNCIA SANITÁRIA',10,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (305,'305','VIGILÂNCIA EPIDEMIOLÓGICA',10,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (306,'306','ALIMENTAÇÃO E NUTRIÇÃO',10,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (331,'331','PROTEÇÃO E BENEFÍCIOS AO TRABALHADOR',11,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (332,'332','RELAÇÕES DE TRABALHO',11,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (333,'333','EMPREGABILIDADE',11,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (334,'334','FOMENTO AO TRABALHO',11,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (361,'361','ENSINO FUNDAMENTAL',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (362,'362','ENSINO MÉDIO',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (363,'363','ENSINO PROFISSIONAL',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (364,'364','ENSINO SUPERIOR',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (365,'365','EDUCAÇÃO INFANTIL',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (366,'366','EDUCAÇÃO DE JOVENS E ADULTOS',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (367,'367','EDUCAÇÃO ESPECIAL',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (368,'368','EDUCAÇÃO BÁSICA',12,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (391,'391','PATRIMÔNIO HISTÓRICO, ARTÍSTICO  E ARQUEOLÓGICO',13,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (392,'392','DIFUSÃO CULTURAL',13,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (421,'421','CUSTÓDIA E REINTEGRAÇÃO SOCIAL',14,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (422,'422','DIREITOS INDIVIDUAIS, COLETIVOS E DIFUSOS',14,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (423,'423','ASSISTÊNCIA AOS POVOS INDÍGENAS',14,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (451,'451','INFRAESTRUTURA URBANA',15,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (452,'452','SERVIÇOS URBANOS',15,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (453,'453','TRANSPORTES COLETIVOS URBANOS',15,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (481,'481','HABITAÇÃO RURAL',16,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (482,'482','HABITAÇÃO URBANA',16,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (511,'511','SANEAMENTO BÁSICO RURAL',17,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (512,'512','SANEAMENTO BÁSICO URBANO',17,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (541,'541','PRESERVAÇÃO E CONSERVAÇÃO AMBIENTAL',18,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (542,'542','CONTROLE AMBIENTAL',18,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (543,'543','RECUPERAÇÃO DE ÁREAS DEGRADADAS',18,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (544,'544','RECURSOS HÍDRICOS',18,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (545,'545','METEOROLOGIA',18,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (571,'571','DESENVOLVIMENTO CIENTÍFICO',19,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (572,'572','DESENVOLVIMENTO TECNOLÓGICO E ENGENHARIA',19,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (573,'573','DIFUSÃO DO CONHECIMENTO CIENTÍFICO E TECNOLÓGICO',19,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (601,'601','PROMOÇÃO DA PRODUÇÃO VEGETAL',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (602,'602','PROMOÇÃO DA PRODUÇÃO ANIMAL',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (603,'603','DEFESA SANITÁRIA VEGETAL',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (604,'604','DEFESA SANITÁRIA ANIMAL',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (605,'605','ABASTECIMENTO',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (606,'606','EXTENSÃO RURAL',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (607,'607','IRRIGAÇÃO',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (608,'608','PROMOÇÃO DA PRODUÇÃO AGROPECUÁRIA',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (609,'609','DEFESA AGROPECUÁRIA',20,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (631,'631','REFORMA AGRÁRIA',21,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (632,'632','COLONIZAÇÃO',21,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (661,'661','PROMOÇÃO INDUSTRIAL',22,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (662,'662','PRODUÇÃO INDUSTRIAL',22,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (663,'663','MINERAÇÃO',22,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (664,'664','PROPRIEDADE INDUSTRIAL',22,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (665,'665','NORMALIZAÇÃO E QUALIDADE',22,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (691,'691','PROMOÇÃO COMERCIAL',23,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (692,'692','COMERCIALIZAÇÃO',23,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (693,'693','COMÉRCIO EXTERIOR',23,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (694,'694','SERVIÇOS FINANCEIROS',23,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (695,'695','TURISMO',23,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (721,'721','COMUNICAÇÕES POSTAIS',24,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (722,'722','TELECOMUNICAÇÕES',24,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (751,'751','CONSERVAÇÃO DE ENERGIA',25,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (752,'752','ENERGIA ELÉTRICA',25,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (753,'753','PETRÓLEO',25,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (754,'754','ÁLCOOL',25,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (781,'781','TRANSPORTE AÉREO',26,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (782,'782','TRANSPORTE RODOVIÁRIO',26,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (783,'783','TRANSPORTE FERROVIÁRIO',26,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (784,'784','TRANSPORTE HIDROVIÁRIO',26,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (785,'785','TRANSPORTES ESPECIAIS',26,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (811,'811','DESPORTO DE RENDIMENTO',27,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (812,'812','DESPORTO COMUNITÁRIO',27,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (813,'813','LAZER',27,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (841,'841','REFINANCIAMENTO DA DÍVIDA INTERNA',28,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (842,'842','REFINANCIAMENTO DA DÍVIDA EXTERNA',28,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (843,'843','SERVIÇO DA DÍVIDA INTERNA',28,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (844,'844','SERVIÇO DA DÍVIDA EXTERNA',28,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (845,'845','TRANSFERÊNCIAS',28,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (846,'846','OUTROS ENCARGOS ESPECIAIS',28,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (998,'998','A CLASSIFICAR',99,true);
insert into subfuncao (id, codigo, nome, funcao_id, ativo) values (999,'999','RESERVA DE CONTINGÊNCIA',99,true);
