insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (085,'085','% EXECUTADO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (002,'002','A Classificar',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (084,'084','AERÓDROMO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (083,'083','AEROPORTO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (001,'001','AGRICULTOR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (121,'121','AGRICULTOR FAMILIAR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (086,'086','AGRICULTORES E QUILOMBOLAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (004,'004','ALUNOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (087,'087','APL',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (157,'157','AQUISIÇÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (149,'149','ÁREA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (082,'082','ASSENTAMENTO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (145,'145','ATENDIMENTOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (005,'005','ATIVIDADES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (107,'107','ATLETA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (006,'006','BAIRROS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (173,'173','BLITZ',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (166,'166','Boletim de Ocorrencia',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (007,'007','BOLSAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (171,'171','BOLSAS CONCEDIDAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (148,'148','CADEAIS PRODUTIVAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (143,'143','CAMPANHAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (008,'008','CAMPOS DE FUTEBOL',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (009,'009','CANDIDATOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (088,'088','CAPACITAÇÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (114,'114','CAVALO VAPOR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (010,'010','CENTROS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (089,'089','CENTROS ESPORTIVOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (011,'011','COLÔNIA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (012,'012','COMPUTADOR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (152,'152','CONCURSO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (138,'138','CONSELHO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (155,'155','CONTRATAÇÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (158,'158','CONVÊNIO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (113,'113','CRIANÇA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (013,'013','CRIANÇAS/JOVENS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (014,'014','CURSO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (090,'090','CURSO RECONHECIDOS/REAVALIADOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (015,'015','DETENTO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (091,'091','DISCENTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (016,'016','DOCENTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (126,'126','DÓLAR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (017,'017','DOMICÍLIOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (132,'132','EMPRESA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (140,'140','ENTIDADE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (018,'018','EQUIPAMENTOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (019,'019','ESCOLA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (092,'092','ESCOLAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (141,'141','ESPAÇO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (021,'021','ESTÁDIOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (151,'151','ESTUDO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (022,'022','EVENTO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (023,'023','EXEMPLAR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (025,'025','FAMÍLIAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (026,'026','FISCALIZAÇÕES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (164,'164','FUNDO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (028,'028','GERENCIA REGIONAL',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (099,'099','GERÊNCIAS REGIONAIS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (030,'030','GESTÃO ADMINISTRATIVA  MELHORADA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (029,'029','GESTOR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (031,'031','GINÁSIO POLIESPORTIVO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (167,'167','HABITANTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (102,'102','HECTARE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (034,'034','HECTARES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (106,'106','HOMENS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (112,'112','IDOSO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (146,'146','IMÓVEIS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (168,'168','ÍNDICE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (035,'035','JOVEM',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (036,'036','KM',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (103,'103','KM SINALIZADO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (156,'156','LICITAÇÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (111,'111','LITRO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (037,'037','LITROS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (038,'038','MATRÍCULA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (039,'039','MESES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (040,'040','METROS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (042,'042','METROS CÚBICOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (043,'043','METROS CÚBICOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (104,'104','METROS CÚBICOS/DIA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (044,'044','METROS QUADRADOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (105,'105','MILHEIRO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (101,'101','MILHÕES DE METROS CÚBICOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (150,'150','MONITORAMENTO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (046,'046','MONITORES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (135,'135','MORADIA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (047,'047','MULHERES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (049,'049','MUNICÍPIO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (108,'108','MUNICÍPIO BENEFICIADO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (110,'110','MUNICÍPIOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (109,'109','MUNICÍPIOS BENEFICIADOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (154,'154','NORMA IMPLANTADA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (165,'165','NUMERO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (050,'050','OBRA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (081,'081','ÓRGÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (051,'051','PACIENTE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (139,'139','PARCERIA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (052,'052','PARTICIPANTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (169,'169','PATENTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (053,'053','PERCENTAGEM',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (054,'054','PERCENTUAL',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (120,'120','PESSOA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (057,'057','PESSOAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (059,'059','PLACAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (060,'060','PLANO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (122,'122','POLICIAL',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (061,'061','POPULAÇÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (161,'161','POPULAÇÃO ATENDIDA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (162,'162','POPULAÇÃO COBERTA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (116,'116','POR CEM MIL HABITANTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (119,'119','POR CEM MIL PESSOAS ENTRE QUARENTA E SESSENTA E NOVE ANOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (130,'130','POR CEM MIL VEÍCULOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (118,'118','POR DEZ MIL PESSOAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (131,'131','POR DEZ MIL VEÍCULOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (117,'117','POR MIL CRIANÇAS MENORES DE CINCO ANOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (098,'098','POR MIL HABITANTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (097,'097','POR MIL NASCIDOS VIVOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (129,'129','PRESO POR VAGA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (062,'062','PRODUTO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (063,'063','PRODUTORES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (064,'064','PROFESSOR',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (065,'065','PROFISSIONAL',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (067,'067','PROJETO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (123,'123','PROJETO DE PESQUISA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (124,'124','PROJETOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (170,'170','PUBLICAÇÃO CIENTÍFICA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (125,'125','QUADRA POLIESPORTIVA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (068,'068','QUADRAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (069,'069','QUANTIDADE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (115,'115','QUILOGRAMA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (163,'163','RAZÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (070,'070','REAIS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (071,'071','REFEIÇÃO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (072,'072','RESIDENTES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (073,'073','ROTEIRO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (160,'160','ROUBOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (147,'147','SALAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (127,'127','SELEÇÃO DE CANDIDATOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (076,'076','SERVIÇOS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (128,'128','SERVIDOR CAPACITADO',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (075,'075','SERVIDORES',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (137,'137','SISTEMA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (159,'159','TERABYTE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (134,'134','TONELADA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (077,'077','TRANSPLANTE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (172,'172','TURISTA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (078,'078','UNIDADE',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (144,'144','VAGAS',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (142,'142','VIA SINALIZADA',null,true);
insert into unidadedemedida (id, codigo, nome, descricao,ativo) values (133,'133','WATT',null,true);
