insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (01101,'01101','ASSEMBLEIA LEGISLATIVA','ALEPI',01,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (02101,'02101','TRIBUNAL DE CONTAS DO ESTADO','TCE',02,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (02102,'02102','FUNDO DE MODERNIZAÇÃO DO TRIBUNAL DE CONTAS ','FMTC',02,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (04101,'04101','TRIBUNAL DE JUSTIÇA','TJ',04,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (04103,'04103','CORREGEDORIA GERAL DA JUSTIÇA','CGJ',04,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (04105,'04105','FUNDO ESPECIAL DE REAPARELHAMENTO E MODERNIZAÇÃO DO PODER JUDICIÁRIO DO ESTADO DO PIAUÍ','FERMOJUPI',04,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (04106,'04106','ESCOLA JUDICIÁRIA DO ESTADO DO PIAUÍ','EJUD',04,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11102,'11102','GABINETE DO VICE GOVERNADOR','VICE GOVERN.',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11103,'11103','GABINETE MILITAR','GAMIL',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11110,'11110','SECRETARIA DE GOVERNO','SEGOV',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11111,'11111','SUPERINTENDÊNCIA DE REPRESENTAÇÃO DO ESTADO EM BRASÍLIA','SURPI',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11112,'11112','COORDENADORIA DE RELAÇÕES INTERNACIONAIS','A DEFINIR',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11113,'11113','COORDENADORIA DA JUVENTUDE','COJUV',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11114,'11114','COORDENADORIA DE ENFRENTAMENTO ÀS DROGAS','CENDROGAS',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11115,'11115','COORDENADORIA ESTADUAL DE POLÍTICAS PARA AS MULHERES','CEPM',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11116,'11116','COORDENADORIA DE DESENVOLVIMENTO SOCIAL E LAZER','CDSOL',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11117,'11117','COORDENADORIA DE FOMENTO À IRRIGAÇÃO','COFIR',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (11118,'11118','COORDENADORIA DE FOMENTO AO SANEAMENTO RURAL','CFSR',11,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (12101,'12101','SECRETARIA DA SEGURANÇA PÚBLICA','SSP',12,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (12102,'12102','DELEGACIA GERAL DA POLÍCIA CIVIL','DG-PC',12,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13101,'13101','SECRETARIA DA FAZENDA','SEFAZ',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13116,'13116','FUNDO DE DESENVOLVIMENTO E APERFEIÇOAMENTO DA ADMINISTRAÇÃO TRIBUTÁRIA - FUNDAT','FUNDAT',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13118,'13118','COORDENAÇÃO DE GERÊNCIAS REGIONAIS DE ATENDIMENTO - CGERAT','A DEFINIR',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13202,'13202','LOTERIA DO ESTADO DO PIAUÍ - LOTEPI','A DEFINIR',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13203,'13203','AGÊNCIA DE FOMENTO E DESENVOLVIMENTO DO ESTADO DO PIAUÍ S.A - PIAUÍ FOMENTO','FOMENTO',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13204,'13204','FUNDO GARANTIDOR AOS MICRO E PEQUENOS EMPREENDIMENTOS DO ESTADO DO PIAUÍ - FUNGEP','FUNGEP',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13205,'13205','FUNDO ESPECIAL DE PRODUÇÃO - FEP','FEP',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (13206,'13206','FUNDO ESPECIAL DE CRÉDITO INADIMPLIDOS E DÍVIDA ATIVA  - FECIDAPI','FECIDAPI',13,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14101,'14101','SECRETARIA DA EDUCAÇÃO','SEDUC 101',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14102,'14102','RECURSOS PARA O DESENVOLVIMENTO DA EDUCAÇÃO BÁSICA','SEDUC 102',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14103,'14103','COORDENADORIA DO PROGRAMA DE EDUCAÇÃO POR MEIO DE MEDIAÇÕES TECNOLÓGICAS','COORD MED TEC',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14201,'14201','FUNDAÇÃO UNIVERSIDADE ESTADUAL DO PIAUÍ - FUESPI','FUESPI',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14202,'14202','FUNDAÇÃO CULTURAL DO PIAUÍ - FUNDAC','A DEFINIR',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14203,'14203','FUNDAÇÃO DOS ESPORTES DO PIAUÍ - FUNDESPI','FUNDESPI',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14204,'14204','FUNDAÇÃO RÁDIO E TV EDUCATIVA DO PIAUÍ','FUNART',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14205,'14205','FUNDO DE INCENTIVO AO ESPORTE E LAZER','A DEFINIR',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (14207,'14207','INSTITUTO SUPERIOR DE EDUCAÇÃO ANTONINO FREIRE - ISEAF','A DEFINIR',14,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15101,'15101','SECRETARIA DO DESENVOLVIMENTO RURAL','SDR',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15103,'15103','COORDENADORIA DO PROGRAMA DO AGRONEGÓCIO E DOS CERRADOS','COORD. AGRONEGÓCIO',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15104,'15104','COORDENADORIA DE CONVIVÊNCIA COM O SEMI-ÁRIDO','A DEFINIR',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15105,'15105','COORDENADORIA DO PROGRAMA DE COMBATE A POBREZA RURAL','CCPR',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15106,'15106','COORDENADORIA DO PROGRAMA DE APOIO A PISCICULTURA','COOR DE AP PISCIC',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15201,'15201','INSTITUTO DE TERRAS DO PIAUÍ - INTERPI','INTERPI',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15202,'15202','INSTITUTO DE ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL DO ESTADO DO PIAUÍ - EMATER','EMATER',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (15204,'15204','AGÊNCIA DE DEFESA AGROPECUÁRIA DO ESTADO DO PIAUÍ - ADAPI','ADAPI',15,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (16101,'16101','SECRETARIA DA INFRAESTRUTURA','SEINFRA',16,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (16202,'16202','ÁGUAS E ESGOTOS DO PIAUÍ S/A - AGESPISA','AGESPISA',16,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (16208,'16208','INSTITUTO DE DESENVOLVIMENTO DO PIAUÍ - IDEPI','IDEPI',16,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (16209,'16209','INSTITUTO DE ÁGUAS E ESGOTOS DO PIAUÍ - AGESPISA','A DEFINIR',16,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17101,'17101','FUNSAUDE/SUS-GESTÃO PLENA ESTADUAL','FUNSAUDE',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17102,'17102','HOSPITAL REGIONAL MANOEL  SOUSA SANTOS - BOM JESUS','HRMSS - BOM JESUS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17103,'17103','HOSPITAL REGIONAL TIBÉRIO NUNES - FLORIANO','HRTN - FLORIANO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17104,'17104','HOSPITAL COLÔNIA DO CARPINA - PARNAÍBA','HCC - PARNAÍBA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17105,'17105','HOSPITAL REGIONAL JUSTINO LUZ - PICOS','HRJL - PICOS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17106,'17106','HOSPITAL SENADOR CÂNDIDO FERRAZ -  SÃO RAIMUNDO NONATO','HRCF - S.R. NONATO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17107,'17107','HOSPITAL REGIONAL DR. LEONIDAS MELO - BARRAS','HRLM - BARRAS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17108,'17108','HOSPITAL REGIONAL DE CAMPO MAIOR - CAMPO MAIOR','HRCM - CAMPO MAIOR',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17109,'17109','HOSPITAL REGIONAL DR. JOÃO PACHECO CAVALCANTE - CORRENTE','HRJPC - CORRENTE',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17110,'17110','HOSPITAL REGIONAL DEOLINDO COUTO - OEIRAS','HRDC - OEIRAS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17111,'17111','HOSPITAL REGIONAL DR. CHAGAS RODRIGUES - PIRIPIRI','HRCR - PIRIPIRI',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17112,'17112','LABORATÓRIO CENTRAL DR. COSTA ALVARENGA - TERESINA','LACEN',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17113,'17113','HOSPITAL INFANTIL DR. LUCÍDIO PORTELA - TERESINA','HILP',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17114,'17114','HOSPITAL PSIQUIÁTRICO AREOLINO DE ABREU - TERESINA','HAA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17115,'17115','MATERNIDADE DONA EVANGELINA ROSA - TERESINA','MDER',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17116,'17116','INSTITUTO DE DOENÇAS TROPICAIS DR. NATAN PORTELA - TERESINA','IDTNP',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17117,'17117','HOSPITAL GETÚLIO VARGAS - TERESINA','HGV',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17118,'17118','CENTRO DE HEMATOLOGIA E HEMOTERAPIA DO PIAUÍ - HEMOPI -  TERESINA','HEMOPI',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17119,'17119','HOSPITAL DIRCEU ARCOVERDE - PARNAÍBA','HEDA - PARNAÍBA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17121,'17121','HOSPITAL ESTADUAL DR. JÚLIO HARTMAN - ESPERANTINA','HEJH - ESPERANTINA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17123,'17123','HOSPITAL LOCAL JOSÉ DE MOURA FÉ - SIMPLÍCIO MENDES','HLJMF - SIMPLÍCIO MENDES',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17124,'17124','HOSPITAL REGIONAL TERESINHA NUNES DE BARROS - SÃO JOÃO DO PIAUÍ','HRTNB - SÃO JOÃO DO PI',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17125,'17125','HOSPITAL REGIONAL EUSTÁQUIO PORTELA - VALENÇA  DO PIAUÍ','HREP - VALENÇA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17126,'17126','HOSPITAL REGIONAL DIRCEU ARCOVERDE - URUÇUÍ','HRDA - URUÇUÍ',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17128,'17128','HOSPITAL LOCAL DOMINGOS CHAVES - CANTO DO BURITI','HLDC - CANTO DO BURITI',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17129,'17129','I - COORDENAÇÃO  REGIONAL DE SAÚDE - PARNAÍBA','1 CRS - PARNAÍBA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17130,'17130','III - COORDENAÇÃO REGIONAL DE SAÚDE - PIRIPIRI','3 CRS - PIRIPIRI',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17131,'17131','V - COORDENAÇÃO REGIONAL DE SAÚDE - CAMPO MAIOR','5 CRS - CAMPO MAIOR',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17132,'17132','VII - COORDENAÇÃO REGIONAL DE SAÚDE - VALENÇA DO PIAUÍ','7 CRS - VALENÇA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17133,'17133','IX - COORDENAÇÃO  REGIONAL DE SAÚDE - PICOS','9 CRS - PICOS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17134,'17134','X - COORDENAÇÃO REGIONAL DE SAÚDE - FLORIANO','10 CRS - FLORIANO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17135,'17135','XII - COORDENAÇÃO REGIONAL DE SAÚDE - SÃO RAIMUNDO NONATO','12 CRS - S.R. NONATO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17136,'17136','XIII -  COORDENAÇÃO REGIONAL DE SAÚDE - BOM JESUS','13 CRS - BOM JESUS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17137,'17137','IV - COORDENAÇÃO REGIONAL DE SAÚDE - TERESINA','4 CRS - TERESINA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17138,'17138','UNIDADE INTEGRADA DE SAÚDE DO MOCAMBINHO','UIS - MOCAMBINHO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17139,'17139','SECRETARIA ESTADUAL DE SAÚDE','SESAPI',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17140,'17140','VIII - COORDENAÇÃO REGIONAL DE SAÚDE - OEIRAS','8 CRS - OEIRAS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17141,'17141','XV - COORDENAÇÃO REGIONAL DE SAÚDE - URUÇUI','15 CRS - URUÇUÍ',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17142,'17142','HOSPITAL REGIONAL DR. FRANCISCO AYRES CAVALCANTE - AMARANTE','HRFAC - AMARANTE',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17143,'17143','HOSPITAL LOCAL GERSON CASTELO BRANCO','HLGCB - LUZILÂNDIA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17144,'17144','UNIDADE MISTA DE SAÚDE DE BOCÁINA','UMS - BOCÁINA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17145,'17145','HOSPITAL ESTADUAL JÚLIO BORGES DE MACÊDO','HEJBC - SÃO MIGUEL DO TAPUIO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17146,'17146','HOSPITAL ESTADUAL JOÃO LUIS DE MORAIS','HEJLM - DEMERVAL LOBÃO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17147,'17147','UNIDADE MISTA DE SAÚDE DE AVELINO LOPES','UMS - AVELINO LOPES',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17148,'17148','HOSPITAL ESTADUAL JOSÉ FURTADO DE MENDONÇA','HEJFM - SÃO MIGUEL DO TAPUIO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17149,'17149','UNIDADE MISTA DE SANTA FILOMENA','UMS - SANTA FILOMENA',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17150,'17150','UNIDADE MISTA PEDRO LOPES - FRANCINÓPOLIS','UMS - FRANCINÓPOLIS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17151,'17151','UNIDADE MISTA DE ITAINÓPOLIS','UMS - ITAINÓPOLIS',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (17152,'17152','HOSPITAL ESTADUAL NORBERTO MOURA','HENM - ELESBÃO VELOSO',17,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (19101,'19101','SECRETARIA DO PLANEJAMENTO','SEPLAN',19,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (19103,'19103','FUNDO DE INVESTIMENTOS ECONÔMICOS E SOCIAIS - FIES','A DEFINIR',19,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (19105,'19105','COORDENADORIA DE COMBATE A POBREZA RURAL','A DEFINIR',19,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (19106,'19106','COORDENADORIA DE CRÉDITO FUNDIÁRIO','A DEFINIR',19,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (19201,'19201','FUNDAÇÃO CENTRO DE PESQUISAS ECONÔMICAS E SOCIAIS DO PIAUÍ - CEPRO','CEPRO',19,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (19202,'19202','AGÊNCIA DE REGULAÇÃO DOS SERVIÇOS PÚBLICOS DELEGADOS DO ESTADO DO PIAUÍ - AGRESP','A DEFINIR',19,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20101,'20101','SECRETARIA DO DESENVOLVIMENTO ECONÔMICO E TECNOLÓGICO','SEDET',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20103,'20103','COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVAÇÃO','COORD. TECNOLOGIA',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20201,'20201','JUNTA COMERCIAL DO ESTADO DO PIAUÍ - JUCEPI','JUCEPI',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20203,'20203','FUNDAÇÃO DE AMPARO A PESQUISA DO ESTADO DO PIAUÍ - FAPEPI','FAPEPI',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20204,'20204','COMPANHIA DE GÁS DO ESTADO DO PIAUÍ - GASPISA','A DEFINIR',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20205,'20205','INSTITUTO DE METROLOGIA DO ESTADO DO PIAUÍ - IMEPI','IMEPI',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20206,'20206','COMPANHIA ADMINISTRADORA DA ZONA DE PROCESSAMENTO DE EXPORTAÇÃO DE PARNAÍBA - ZPE','ZPE - PARNAÍBA',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (20207,'20207','COMPANHIA DE TERMINAIS ALFANDEGADOS DO PIAUÍ - PORTO-PI','PORTO',20,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21101,'21101','SECRETARIA DA ADMINISTRAÇÃO E PREVIDÊNCIA','SEADPREV',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21102,'21102','FUNDO ROTATIVO DE MATERIAL E CONSERVAÇÃO DE PATRIMÔNIO DO ESTADO DO PIAUÍ','FUNDO ROTATIVO',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21103,'21103','ESCOLA DE GOVERNO','A DEFINIR',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21104,'21104','FUNDO DE INFORMÁTICA DO PIAUÍ','A DEFINIR',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21105,'21105','COORDENADORIA DE CONTROLE DAS LICITAÇÕES DO ESTADO DO PIAUÍ','A DEFINIR',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21201,'21201','INSTITUTO DE ASSISTÊNCIA A SAÚDE DO SERVIDOR PÚBLICO DO ESTADO DO PIAUÍ - IASPI','IASPI',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21203,'21203','FUNDO DE PREVIDÊNCIA DO ESTADO DO PIAUÍ','FUNPREV',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21204,'21204','AGÊNCIA DE TECNOLOGIA DA INFORMAÇÃO DO ESTADO DO PIAUÍ - ATI','ATI',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21205,'21205','EMPRESA DE GESTÃO DE RECURSOS DO ESTADO DO PIAUÍ S/A - EMGERPI','EMGERPI',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21206,'21206','FUNDO INTEGRADO DE BENS, DIREITOS E ATIVOS DA PREVIDÊNCIA SOCIAL DO ESTADO DO PIAUÍ','FIBDA',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (21207,'21207','FUNDAÇÃO PIAUÍ PREVIDÊNCIA','PIAUÍ-PREV',21,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (22101,'22101','SECRETARIA DA JUSTIÇA','SEJUS',22,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (22201,'22201','FUNDO PENITENCIÁRIO DO ESTADO DO PIAUÍ - FUNPESPI','FUNPESPI',22,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (24101,'24101','ENCARGOS GERAIS DO ESTADO','ENCARGOS',24,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (25101,'25101','PROCURADORIA GERAL DA JUSTIÇA','PGJ',25,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (25102,'25102','FUNDO ESPECIAL DO MINISTÉRIO PÚBLICO','FUNDO MPE',25,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (25103,'25103','CORREGEDORIA GERAL DO MINISTÉRIO PÚBLICO','A DEFINIR',25,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (25104,'25104','FUNDO ESTADUAL DE PROTEÇÃO E DEFESA DO CONSUMIDOR - FPCD','FPCD MPE',25,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26101,'26101','POLÍCIA MILITAR DO PIAUÍ','PM',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26102,'26102','HOSPITAL DIRCEU ARCOVERDE DA PMPI - TERESINA','HPM',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26103,'26103','2º BATALHÃO DE POLÍCIA MILITAR - PARNAÍBA','2º BPM - PARNAÍBA',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26104,'26104','3º BATALHÃO DE POLÍCIA MILITAR - FLORIANO','3º BPM - FLORIANO',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26105,'26105','4º BATALHÃO DE POLÍCIA MILITAR - PICOS','4º BPM - PICOS',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26106,'26106','7º BATALHÃO DE POLÍCIA MILITAR - CORRENTE','7º BPM - CORRENTE',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26107,'26107','CENTRO DE EDUCAÇÃO PROFISSIONAL','CEP PMPI',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26108,'26108','10° BATALHÃO DE POLÍCIA MILITAR - URUÇUÍ','10º BPM - URUÇUÍ',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26109,'26109','11° BATALHÃO DE POLÍCIA MILITAR - SÃO RAIMUNDO NONATO','11º BPM - S.R. NONATO',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26110,'26110','12° BATALHÃO DE POLÍCIA MILITAR - PIRIPIRI','12º BPM - PIRIPIRI',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26111,'26111','14° BATALHÃO DE POLÍCIA MILITAR - OEIRAS','14º BPM - OEIRAS',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26112,'26112','15° BATALHÃO DE POLÍCIA MILITAR - CAMPO MAIOR','15º BPM - CAMPO MAIOR',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26113,'26113','20º BATALHÃO DE POLÍCIA MILITAR - PAULISTANA','20º BPM - PAULISTANA',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26114,'26114','COMPANHIA INDEPENDENTE DE POLÍCIA DE TURISMO - CIPTUR - LUÍS CORREIA','CIPTUR',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26115,'26115','16º BATALHÃO DE POLÍCIA MILITAR - JOSÉ DE FREITAS','16º BPM - J. DE FREITAS',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26116,'26116','18º BATALHÃO DE POLÍCIA MILITAR - ÁGUA BRANCA','18º BPM - ÁGUA BRANCA',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (26117,'26117','19º BATALHÃO DE POLÍCIA MILITAR - BOM JESUS','19º BPM - BOM JESUS',26,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (28101,'28101','SECRETARIA DO MEIO AMBIENTE E DOS RECURSOS HÍDRICOS','SEMAR',28,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (28102,'28102','COORDENADORIA DO PROGRAMA DE GESTÃO DE RECURSOS HÍDRICOS','COOR GEST REC HID',28,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (30101,'30101','SECRETARIA DA ASSISTÊNCIA SOCIAL E CIDADANIA','SASC',30,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (30102,'30102','FUNDO ESTADUAL DE ASSISTÊNCIA SOCIAL','FUNDO SASC',30,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (30103,'30103','COORDENADORIA DE DIREITOS HUMANOS E DA JUVENTUDE','A DEFINIR',30,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (30104,'30104','FUNDO ESTADUAL DOS DIREITOS DA CRIANÇA E DO ADOLESCENTE - FEDCA','FECDA SASC',30,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (30105,'30105','COORDENADORIA DO PROGRAMA MAIS VIDA COM CIDADANIA PARA O IDOSO','COORD. IDOSO',30,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (33101,'33101','COORDENADORIA DE COMUNICAÇÃO SOCIAL','CCOM',33,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (35101,'35101','DEFENSORIA PÚBLICA DO ESTADO','DPE',35,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (35102,'35102','FUNDO DE MODERNIZAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA - FMADPEP','FMADPEP',35,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (36101,'36101','PROCURADORIA GERAL DO ESTADO','PGE',36,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (37101,'37101','CONTROLADORIA GERAL DO ESTADO','CGE',37,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (38101,'38101','SECRETARIA ESTADUAL PARA INCLUSÃO DA PESSOA COM DEFICIÊNCIA','SEID',38,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (38102,'38102','FUNDO ESTADUAL DE DEFESA DOS DIREITOS DA PESSOA COM DEFICIÊNCIA - FUNEDE','FUNEDE',38,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (39000,'39000','RESERVA DE CONTINGÊNCIA','RESERVA',39,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (44101,'44101','CORPO DE BOMBEIROS MILITAR','CBMEPI',44,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (45101,'45101','SECRETARIA DAS CIDADES','SECID',45,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (45201,'45201','DEPARTAMENTO ESTADUAL DE TRÂNSITO DO PIAUÍ - DETRAN','DETRAN',45,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (45202,'45202','AGÊNCIA DE DESENVOLVIMENTO HABITACIONAL DO PIAUÍ - ADH','ADH',45,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (45203,'45203','INSTITUTO DE ÁGUAS E ESGOTOS DO PIAUÍ','IAEPI',45,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (46101,'46101','SECRETARIA DOS TRANSPORTES','SETRANS',46,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (46102,'46102','COORDENADORIA DO PROGRAMA DE INFRAESTRUTURA AEROPORTUARIA','COOR INF AEROPORTUARIA',46,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (46106,'46106','COORDENADORIA DO PROGRAMA DE INFRAESTRUTURA AEROPORTUARIA','COOR INF AEROPORT',46,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (46201,'46201','DEPARTAMENTO DE ESTRADAS DE RODAGENS DO PIAUÍ - DER/PI','DER',46,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (46202,'46202','COMPANHIA METROPOLITANA DE TRANSPORTES PÚBLICOS - CMTP','CMTP',46,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (47101,'47101','SECRETARIA DO TURISMO','SETUR',47,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (47201,'47201','PIAUÍ TURISMO - PIEMTUR','A DEFINIR',47,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (48101,'48101','SECRETARIA DO TRABALHO E EMPREENDEDORISMO','SETRE',48,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (48102,'48102','SISTEMA NACIONAL DO EMPREGO - SINE','A DEFINIR',48,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (48103,'48103','COORDENADORIA DO PROGRAMA DE MODERNIZAÇÃO E QUALIFICAÇÃO DE EMPREENDIMENTOS PÚBLICOS','COORD. MODERNIZAÇÃO',48,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (49101,'49101','SECRETARIA DE DEFESA CIVIL','SEDEC',49,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (50101,'50101','SECRETARIA ESTADUAL DE MINERAÇÃO, PETRÓLEO E ENERGIAS RENOVÁVEIS','SEMINPER',50,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (50201,'50201','COMPANHIA DE GÁS DO ESTADO DO PIAUÍ - GASPISA','GASPISA',50,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (51101,'51101','SECRETARIA DA CULTURA','SECULT',51,true);
insert into unidadeorcamentaria (id, codigo, nome, mnemonico, orgao_id, ativo) values (90000,'90000','TESOURO ESTADUAL','TESOURO ESTADUAL',90,true);
