insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (010101,'010101','ASSEMBLEIA LEGISLATIVA','ALEPI',01101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (020101,'020101','TRIBUNAL DE CONTAS DO ESTADO','TCE',02101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (020102,'020102','FUNDO DE MODERNIZAÇÃO DO TRIBUNAL DE CONTAS ','FMTC',02102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (040101,'040101','TRIBUNAL DE JUSTIÇA','TJ',04101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (040103,'040103','CORREGEDORIA GERAL DA JUSTIÇA','CGJ',04103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (040105,'040105','FUNDO ESPECIAL DE REAPARELHAMENTO E MODERNIZAÇÃO DO PODER JUDICIÁRIO DO ESTADO DO PIAUÍ','FERMOJUPI',04105,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (040106,'040106','ESCOLA JUDICIÁRIA DO ESTADO DO PIAUÍ','EJUD',04106,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110102,'110102','GABINETE DO VICE GOVERNADOR','VICE GOVERN.',11102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110103,'110103','GABINETE MILITAR','GAMIL',11103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110110,'110110','SECRETARIA DE GOVERNO','SEGOV',11110,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110111,'110111','SUPERINTENDÊNCIA DE REPRESENTAÇÃO DO ESTADO EM BRASÍLIA','SURPI',11111,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110112,'110112','COORDENADORIA DE RELAÇÕES INTERNACIONAIS','A DEFINIR',11112,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110113,'110113','COORDENADORIA DA JUVENTUDE','COJUV',11113,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110114,'110114','COORDENADORIA DE ENFRENTAMENTO ÀS DROGAS','CENDROGAS',11114,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110115,'110115','COORDENADORIA ESTADUAL DE POLÍTICAS PARA AS MULHERES','CEPM',11115,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110116,'110116','COORDENADORIA DE DESENVOLVIMENTO SOCIAL E LAZER','CDSOL',11116,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110117,'110117','COORDENADORIA DE FOMENTO À IRRIGAÇÃO','COFIR',11117,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (110118,'110118','COORDENADORIA DE FOMENTO AO SANEAMENTO RURAL','CFSR',11118,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (120101,'120101','SECRETARIA DA SEGURANÇA PÚBLICA','SSP',12101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (120102,'120102','DELEGACIA GERAL DA POLÍCIA CIVIL','DG-PC',12102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130101,'130101','SECRETARIA DA FAZENDA','SEFAZ',13101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130116,'130116','FUNDO DE DESENVOLVIMENTO E APERFEIÇOAMENTO DA ADMINISTRAÇÃO TRIBUTÁRIA - FUNDAT','FUNDAT',13116,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130118,'130118','COORDENAÇÃO DE GERÊNCIAS REGIONAIS DE ATENDIMENTO - CGERAT','A DEFINIR',13118,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130202,'130202','LOTERIA DO ESTADO DO PIAUÍ - LOTEPI','A DEFINIR',13202,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130203,'130203','AGÊNCIA DE FOMENTO E DESENVOLVIMENTO DO ESTADO DO PIAUÍ S.A - PIAUÍ FOMENTO','FOMENTO',13203,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130204,'130204','FUNDO GARANTIDOR AOS MICRO E PEQUENOS EMPREENDIMENTOS DO ESTADO DO PIAUÍ - FUNGEP','FUNGEP',13204,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130205,'130205','FUNDO ESPECIAL DE PRODUÇÃO - FEP','FEP',13205,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (130206,'130206','FUNDO ESPECIAL DE CRÉDITO INADIMPLIDOS E DÍVIDA ATIVA  - FECIDAPI','FECIDAPI',13206,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140101,'140101','SECRETARIA DA EDUCAÇÃO','SEDUC 101',14101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140102,'140102','RECURSOS PARA O DESENVOLVIMENTO DA EDUCAÇÃO BÁSICA','SEDUC 102',14102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140103,'140103','COORDENADORIA DO PROGRAMA DE EDUCAÇÃO POR MEIO DE MEDIAÇÕES TECNOLÓGICAS','COORD MED TEC',14103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140201,'140201','FUNDAÇÃO UNIVERSIDADE ESTADUAL DO PIAUÍ - FUESPI','FUESPI',14201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140202,'140202','FUNDAÇÃO CULTURAL DO PIAUÍ - FUNDAC','A DEFINIR',14202,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140203,'140203','FUNDAÇÃO DOS ESPORTES DO PIAUÍ - FUNDESPI','FUNDESPI',14203,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140204,'140204','FUNDAÇÃO RÁDIO E TV EDUCATIVA DO PIAUÍ','FUNART',14204,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140205,'140205','FUNDO DE INCENTIVO AO ESPORTE E LAZER','A DEFINIR',14205,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (140207,'140207','INSTITUTO SUPERIOR DE EDUCAÇÃO ANTONINO FREIRE - ISEAF','A DEFINIR',14207,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150101,'150101','SECRETARIA DO DESENVOLVIMENTO RURAL','SDR',15101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150103,'150103','COORDENADORIA DO PROGRAMA DO AGRONEGÓCIO E DOS CERRADOS','COORD. AGRONEGÓCIO',15103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150104,'150104','COORDENADORIA DE CONVIVÊNCIA COM O SEMI-ÁRIDO','A DEFINIR',15104,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150105,'150105','COORDENADORIA DO PROGRAMA DE COMBATE A POBREZA RURAL','CCPR',15105,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150106,'150106','COORDENADORIA DO PROGRAMA DE APOIO A PISCICULTURA','COOR DE AP PISCIC',15106,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150201,'150201','INSTITUTO DE TERRAS DO PIAUÍ - INTERPI','INTERPI',15201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150202,'150202','INSTITUTO DE ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL DO ESTADO DO PIAUÍ - EMATER','EMATER',15202,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (150204,'150204','AGÊNCIA DE DEFESA AGROPECUÁRIA DO ESTADO DO PIAUÍ - ADAPI','ADAPI',15204,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (160101,'160101','SECRETARIA DA INFRAESTRUTURA','SEINFRA',16101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (160202,'160202','ÁGUAS E ESGOTOS DO PIAUÍ S/A - AGESPISA','AGESPISA',16202,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (160208,'160208','INSTITUTO DE DESENVOLVIMENTO DO PIAUÍ - IDEPI','IDEPI',16208,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (160209,'160209','INSTITUTO DE ÁGUAS E ESGOTOS DO PIAUÍ - AGESPISA','A DEFINIR',16209,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170101,'170101','FUNSAUDE/SUS-GESTÃO PLENA ESTADUAL','FUNSAUDE',17101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170102,'170102','HOSPITAL REGIONAL MANOEL  SOUSA SANTOS - BOM JESUS','HRMSS - BOM JESUS',17102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170103,'170103','HOSPITAL REGIONAL TIBÉRIO NUNES - FLORIANO','HRTN - FLORIANO',17103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170104,'170104','HOSPITAL COLÔNIA DO CARPINA - PARNAÍBA','HCC - PARNAÍBA',17104,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170105,'170105','HOSPITAL REGIONAL JUSTINO LUZ - PICOS','HRJL - PICOS',17105,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170106,'170106','HOSPITAL SENADOR CÂNDIDO FERRAZ -  SÃO RAIMUNDO NONATO','HRCF - S.R. NONATO',17106,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170107,'170107','HOSPITAL REGIONAL DR. LEONIDAS MELO - BARRAS','HRLM - BARRAS',17107,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170108,'170108','HOSPITAL REGIONAL DE CAMPO MAIOR - CAMPO MAIOR','HRCM - CAMPO MAIOR',17108,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170109,'170109','HOSPITAL REGIONAL DR. JOÃO PACHECO CAVALCANTE - CORRENTE','HRJPC - CORRENTE',17109,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170110,'170110','HOSPITAL REGIONAL DEOLINDO COUTO - OEIRAS','HRDC - OEIRAS',17110,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170111,'170111','HOSPITAL REGIONAL DR. CHAGAS RODRIGUES - PIRIPIRI','HRCR - PIRIPIRI',17111,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170112,'170112','LABORATÓRIO CENTRAL DR. COSTA ALVARENGA - TERESINA','LACEN',17112,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170113,'170113','HOSPITAL INFANTIL DR. LUCÍDIO PORTELA - TERESINA','HILP',17113,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170114,'170114','HOSPITAL PSIQUIÁTRICO AREOLINO DE ABREU - TERESINA','HAA',17114,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170115,'170115','MATERNIDADE DONA EVANGELINA ROSA - TERESINA','MDER',17115,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170116,'170116','INSTITUTO DE DOENÇAS TROPICAIS DR. NATAN PORTELA - TERESINA','IDTNP',17116,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170117,'170117','HOSPITAL GETÚLIO VARGAS - TERESINA','HGV',17117,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170118,'170118','CENTRO DE HEMATOLOGIA E HEMOTERAPIA DO PIAUÍ - HEMOPI -  TERESINA','HEMOPI',17118,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170119,'170119','HOSPITAL DIRCEU ARCOVERDE - PARNAÍBA','HEDA - PARNAÍBA',17119,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170121,'170121','HOSPITAL ESTADUAL DR. JÚLIO HARTMAN - ESPERANTINA','HEJH - ESPERANTINA',17121,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170123,'170123','HOSPITAL LOCAL JOSÉ DE MOURA FÉ - SIMPLÍCIO MENDES','HLJMF - SIMPLÍCIO MENDES',17123,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170124,'170124','HOSPITAL REGIONAL TERESINHA NUNES DE BARROS - SÃO JOÃO DO PIAUÍ','HRTNB - SÃO JOÃO DO PI',17124,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170125,'170125','HOSPITAL REGIONAL EUSTÁQUIO PORTELA - VALENÇA  DO PIAUÍ','HREP - VALENÇA',17125,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170126,'170126','HOSPITAL REGIONAL DIRCEU ARCOVERDE - URUÇUÍ','HRDA - URUÇUÍ',17126,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170128,'170128','HOSPITAL LOCAL DOMINGOS CHAVES - CANTO DO BURITI','HLDC - CANTO DO BURITI',17128,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170129,'170129','I - COORDENAÇÃO  REGIONAL DE SAÚDE - PARNAÍBA','1 CRS - PARNAÍBA',17129,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170130,'170130','III - COORDENAÇÃO REGIONAL DE SAÚDE - PIRIPIRI','3 CRS - PIRIPIRI',17130,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170131,'170131','V - COORDENAÇÃO REGIONAL DE SAÚDE - CAMPO MAIOR','5 CRS - CAMPO MAIOR',17131,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170132,'170132','VII - COORDENAÇÃO REGIONAL DE SAÚDE - VALENÇA DO PIAUÍ','7 CRS - VALENÇA',17132,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170133,'170133','IX - COORDENAÇÃO  REGIONAL DE SAÚDE - PICOS','9 CRS - PICOS',17133,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170134,'170134','X - COORDENAÇÃO REGIONAL DE SAÚDE - FLORIANO','10 CRS - FLORIANO',17134,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170135,'170135','XII - COORDENAÇÃO REGIONAL DE SAÚDE - SÃO RAIMUNDO NONATO','12 CRS - S.R. NONATO',17135,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170136,'170136','XIII -  COORDENAÇÃO REGIONAL DE SAÚDE - BOM JESUS','13 CRS - BOM JESUS',17136,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170137,'170137','IV - COORDENAÇÃO REGIONAL DE SAÚDE - TERESINA','4 CRS - TERESINA',17137,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170138,'170138','UNIDADE INTEGRADA DE SAÚDE DO MOCAMBINHO','UIS - MOCAMBINHO',17138,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170139,'170139','SECRETARIA ESTADUAL DE SAÚDE','SESAPI',17139,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170140,'170140','VIII - COORDENAÇÃO REGIONAL DE SAÚDE - OEIRAS','8 CRS - OEIRAS',17140,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170141,'170141','XV - COORDENAÇÃO REGIONAL DE SAÚDE - URUÇUI','15 CRS - URUÇUÍ',17141,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170142,'170142','HOSPITAL REGIONAL DR. FRANCISCO AYRES CAVALCANTE - AMARANTE','HRFAC - AMARANTE',17142,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170143,'170143','HOSPITAL LOCAL GERSON CASTELO BRANCO','HLGCB - LUZILÂNDIA',17143,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170144,'170144','UNIDADE MISTA DE SAÚDE DE BOCÁINA','UMS - BOCÁINA',17144,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170145,'170145','HOSPITAL ESTADUAL JÚLIO BORGES DE MACÊDO','HEJBC - SÃO MIGUEL DO TAPUIO',17145,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170146,'170146','HOSPITAL ESTADUAL JOÃO LUIS DE MORAIS','HEJLM - DEMERVAL LOBÃO',17146,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170147,'170147','UNIDADE MISTA DE SAÚDE DE AVELINO LOPES','UMS - AVELINO LOPES',17147,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170148,'170148','HOSPITAL ESTADUAL JOSÉ FURTADO DE MENDONÇA','HEJFM - SÃO MIGUEL DO TAPUIO',17148,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170149,'170149','UNIDADE MISTA DE SANTA FILOMENA','UMS - SANTA FILOMENA',17149,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170150,'170150','UNIDADE MISTA PEDRO LOPES - FRANCINÓPOLIS','UMS - FRANCINÓPOLIS',17150,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170151,'170151','UNIDADE MISTA DE ITAINÓPOLIS','UMS - ITAINÓPOLIS',17151,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (170152,'170152','HOSPITAL ESTADUAL NORBERTO MOURA','HENM - ELESBÃO VELOSO',17152,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (190101,'190101','SECRETARIA DO PLANEJAMENTO','SEPLAN',19101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (190103,'190103','FUNDO DE INVESTIMENTOS ECONÔMICOS E SOCIAIS - FIES','A DEFINIR',19103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (190105,'190105','COORDENADORIA DE COMBATE A POBREZA RURAL','A DEFINIR',19105,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (190106,'190106','COORDENADORIA DE CRÉDITO FUNDIÁRIO','A DEFINIR',19106,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (190201,'190201','FUNDAÇÃO CENTRO DE PESQUISAS ECONÔMICAS E SOCIAIS DO PIAUÍ - CEPRO','CEPRO',19201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (190202,'190202','AGÊNCIA DE REGULAÇÃO DOS SERVIÇOS PÚBLICOS DELEGADOS DO ESTADO DO PIAUÍ - AGRESP','A DEFINIR',19202,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200101,'200101','SECRETARIA DO DESENVOLVIMENTO ECONÔMICO E TECNOLÓGICO','SEDET',20101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200103,'200103','COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVAÇÃO','COORD. TECNOLOGIA',20103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200201,'200201','JUNTA COMERCIAL DO ESTADO DO PIAUÍ - JUCEPI','JUCEPI',20201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200203,'200203','FUNDAÇÃO DE AMPARO A PESQUISA DO ESTADO DO PIAUÍ - FAPEPI','FAPEPI',20203,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200204,'200204','COMPANHIA DE GÁS DO ESTADO DO PIAUÍ - GASPISA','A DEFINIR',20204,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200205,'200205','INSTITUTO DE METROLOGIA DO ESTADO DO PIAUÍ - IMEPI','IMEPI',20205,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200206,'200206','COMPANHIA ADMINISTRADORA DA ZONA DE PROCESSAMENTO DE EXPORTAÇÃO DE PARNAÍBA - ZPE','ZPE - PARNAÍBA',20206,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (200207,'200207','COMPANHIA DE TERMINAIS ALFANDEGADOS DO PIAUÍ - PORTO-PI','PORTO',20207,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210101,'210101','SECRETARIA DA ADMINISTRAÇÃO E PREVIDÊNCIA','SEADPREV',21101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210102,'210102','FUNDO ROTATIVO DE MATERIAL E CONSERVAÇÃO DE PATRIMÔNIO DO ESTADO DO PIAUÍ','FUNDO ROTATIVO',21102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210103,'210103','ESCOLA DE GOVERNO','A DEFINIR',21103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210104,'210104','FUNDO DE INFORMÁTICA DO PIAUÍ','A DEFINIR',21104,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210105,'210105','COORDENADORIA DE CONTROLE DAS LICITAÇÕES DO ESTADO DO PIAUÍ','A DEFINIR',21105,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210201,'210201','INSTITUTO DE ASSISTÊNCIA A SAÚDE DO SERVIDOR PÚBLICO DO ESTADO DO PIAUÍ - IASPI','IASPI',21201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210203,'210203','FUNDO DE PREVIDÊNCIA DO ESTADO DO PIAUÍ','FUNPREV',21203,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210204,'210204','AGÊNCIA DE TECNOLOGIA DA INFORMAÇÃO DO ESTADO DO PIAUÍ - ATI','ATI',21204,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210205,'210205','EMPRESA DE GESTÃO DE RECURSOS DO ESTADO DO PIAUÍ S/A - EMGERPI','EMGERPI',21205,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210206,'210206','FUNDO INTEGRADO DE BENS, DIREITOS E ATIVOS DA PREVIDÊNCIA SOCIAL DO ESTADO DO PIAUÍ','FIBDA',21206,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (210207,'210207','FUNDAÇÃO PIAUÍ PREVIDÊNCIA','PIAUÍ-PREV',21207,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (220101,'220101','SECRETARIA DA JUSTIÇA','SEJUS',22101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (220201,'220201','FUNDO PENITENCIÁRIO DO ESTADO DO PIAUÍ - FUNPESPI','FUNPESPI',22201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (240101,'240101','ENCARGOS GERAIS DO ESTADO','ENCARGOS',24101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (250101,'250101','PROCURADORIA GERAL DA JUSTIÇA','PGJ',25101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (250102,'250102','FUNDO ESPECIAL DO MINISTÉRIO PÚBLICO','FUNDO MPE',25102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (250103,'250103','CORREGEDORIA GERAL DO MINISTÉRIO PÚBLICO','A DEFINIR',25103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (250104,'250104','FUNDO ESTADUAL DE PROTEÇÃO E DEFESA DO CONSUMIDOR - FPCD','FPCD MPE',25104,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260101,'260101','POLÍCIA MILITAR DO PIAUÍ','PM',26101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260102,'260102','HOSPITAL DIRCEU ARCOVERDE DA PMPI - TERESINA','HPM',26102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260103,'260103','2º BATALHÃO DE POLÍCIA MILITAR - PARNAÍBA','2º BPM - PARNAÍBA',26103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260104,'260104','3º BATALHÃO DE POLÍCIA MILITAR - FLORIANO','3º BPM - FLORIANO',26104,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260105,'260105','4º BATALHÃO DE POLÍCIA MILITAR - PICOS','4º BPM - PICOS',26105,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260106,'260106','7º BATALHÃO DE POLÍCIA MILITAR - CORRENTE','7º BPM - CORRENTE',26106,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260107,'260107','CENTRO DE EDUCAÇÃO PROFISSIONAL','CEP PMPI',26107,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260108,'260108','10° BATALHÃO DE POLÍCIA MILITAR - URUÇUÍ','10º BPM - URUÇUÍ',26108,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260109,'260109','11° BATALHÃO DE POLÍCIA MILITAR - SÃO RAIMUNDO NONATO','11º BPM - S.R. NONATO',26109,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260110,'260110','12° BATALHÃO DE POLÍCIA MILITAR - PIRIPIRI','12º BPM - PIRIPIRI',26110,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260111,'260111','14° BATALHÃO DE POLÍCIA MILITAR - OEIRAS','14º BPM - OEIRAS',26111,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260112,'260112','15° BATALHÃO DE POLÍCIA MILITAR - CAMPO MAIOR','15º BPM - CAMPO MAIOR',26112,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260113,'260113','20º BATALHÃO DE POLÍCIA MILITAR - PAULISTANA','20º BPM - PAULISTANA',26113,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260114,'260114','COMPANHIA INDEPENDENTE DE POLÍCIA DE TURISMO - CIPTUR - LUÍS CORREIA','CIPTUR',26114,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260115,'260115','16º BATALHÃO DE POLÍCIA MILITAR - JOSÉ DE FREITAS','16º BPM - J. DE FREITAS',26115,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260116,'260116','18º BATALHÃO DE POLÍCIA MILITAR - ÁGUA BRANCA','18º BPM - ÁGUA BRANCA',26116,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (260117,'260117','19º BATALHÃO DE POLÍCIA MILITAR - BOM JESUS','19º BPM - BOM JESUS',26117,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (280101,'280101','SECRETARIA DO MEIO AMBIENTE E DOS RECURSOS HÍDRICOS','SEMAR',28101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (280102,'280102','COORDENADORIA DO PROGRAMA DE GESTÃO DE RECURSOS HÍDRICOS','COOR GEST REC HID',28102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (300101,'300101','SECRETARIA DA ASSISTÊNCIA SOCIAL E CIDADANIA','SASC',30101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (300102,'300102','FUNDO ESTADUAL DE ASSISTÊNCIA SOCIAL','FUNDO SASC',30102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (300103,'300103','COORDENADORIA DE DIREITOS HUMANOS E DA JUVENTUDE','A DEFINIR',30103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (300104,'300104','FUNDO ESTADUAL DOS DIREITOS DA CRIANÇA E DO ADOLESCENTE - FEDCA','FECDA SASC',30104,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (300105,'300105','COORDENADORIA DO PROGRAMA MAIS VIDA COM CIDADANIA PARA O IDOSO','COORD. IDOSO',30105,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (330101,'330101','COORDENADORIA DE COMUNICAÇÃO SOCIAL','CCOM',33101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (350101,'350101','DEFENSORIA PÚBLICA DO ESTADO','DPE',35101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (350102,'350102','FUNDO DE MODERNIZAÇÃO E APARELHAMENTO DA DEFENSORIA PÚBLICA - FMADPEP','FMADPEP',35102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (360101,'360101','PROCURADORIA GERAL DO ESTADO','PGE',36101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (370101,'370101','CONTROLADORIA GERAL DO ESTADO','CGE',37101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (380101,'380101','SECRETARIA ESTADUAL PARA INCLUSÃO DA PESSOA COM DEFICIÊNCIA','SEID',38101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (380102,'380102','FUNDO ESTADUAL DE DEFESA DOS DIREITOS DA PESSOA COM DEFICIÊNCIA - FUNEDE','FUNEDE',38102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (390000,'390000','RESERVA DE CONTINGÊNCIA','RESERVA',39000,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (440101,'440101','CORPO DE BOMBEIROS MILITAR','CBMEPI',44101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (450101,'450101','SECRETARIA DAS CIDADES','SECID',45101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (450201,'450201','DEPARTAMENTO ESTADUAL DE TRÂNSITO DO PIAUÍ - DETRAN','DETRAN',45201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (450202,'450202','AGÊNCIA DE DESENVOLVIMENTO HABITACIONAL DO PIAUÍ - ADH','ADH',45202,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (450203,'450203','INSTITUTO DE ÁGUAS E ESGOTOS DO PIAUÍ','IAEPI',45203,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (460101,'460101','SECRETARIA DOS TRANSPORTES','SETRANS',46101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (460102,'460102','COORDENADORIA DO PROGRAMA DE INFRAESTRUTURA AEROPORTUARIA','COOR INF AEROPORTUARIA',46102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (460106,'460106','COORDENADORIA DO PROGRAMA DE INFRAESTRUTURA AEROPORTUARIA','COOR INF AEROPORT',46106,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (460201,'460201','DEPARTAMENTO DE ESTRADAS DE RODAGENS DO PIAUÍ - DER/PI','DER',46201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (460202,'460202','COMPANHIA METROPOLITANA DE TRANSPORTES PÚBLICOS - CMTP','CMTP',46202,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (470101,'470101','SECRETARIA DO TURISMO','SETUR',47101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (470201,'470201','PIAUÍ TURISMO - PIEMTUR','A DEFINIR',47201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (480101,'480101','SECRETARIA DO TRABALHO E EMPREENDEDORISMO','SETRE',48101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (480102,'480102','SISTEMA NACIONAL DO EMPREGO - SINE','A DEFINIR',48102,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (480103,'480103','COORDENADORIA DO PROGRAMA DE MODERNIZAÇÃO E QUALIFICAÇÃO DE EMPREENDIMENTOS PÚBLICOS','COORD. MODERNIZAÇÃO',48103,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (490101,'490101','SECRETARIA DE DEFESA CIVIL','SEDEC',49101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (500101,'500101','SECRETARIA ESTADUAL DE MINERAÇÃO, PETRÓLEO E ENERGIAS RENOVÁVEIS','SEMINPER',50101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (500201,'500201','COMPANHIA DE GÁS DO ESTADO DO PIAUÍ - GASPISA','GASPISA',50201,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (510101,'510101','SECRETARIA DA CULTURA','SECULT',51101,true);
insert into unidadegestora (id, codigo, nome, sigla, unidadeorcamentaria_id,ativo) values (900000,'900000','TESOURO ESTADUAL','TESOURO ESTADUAL',90000,true);
