
package webservices.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "server.webservicesPortType", targetNamespace = "urn:server.webservices")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServerWebservicesPortType {


    /**
     * 
     * @param cpf
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:server.servidorxml#servidorxml")
    @WebResult(partName = "return")
    public String servidorativoxml(
        @WebParam(name = "cpf", partName = "cpf")
        String cpf);

}
