insert into orgaocertificado (id, sigla, nome) values (1,'04 BPMPI','04 BATALHAO DE POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, sigla, nome) values (2,'10 BPMPI','10 BATALHAO DE POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, sigla, nome) values (3,'10 CRS','10 COORDENAÇÃO REGIONAL DE SAÚDE');
insert into orgaocertificado (id, sigla, nome) values (4,'11 BPMPI','11 BATALHAO POLICIA MILITAR');
insert into orgaocertificado (id, sigla, nome) values (5,'12 BPMPI','12 BATALHAO DE POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, sigla, nome) values (6,'14 BPMPI','14 BATALHAO POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, sigla, nome) values (7,'15 BPMPI','15 BATALHAO DE POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, sigla, nome) values (8,'19 BPMPI','19 BATALHAO DE POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, sigla, nome) values (9,'20 BPMPI','20 BATALHAO POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, sigla, nome) values (10,'02 BPMPI','02 BATALHAO DE POLICIA MILITAR');
insert into orgaocertificado (id, sigla, nome) values (11,'03 CRS','03 COORDENAÇÃO REGIONAL DE SAÚDE');
insert into orgaocertificado (id, sigla, nome) values (12,'07 BPMPI','07 BATALHAO DE POLICIA MILITAR DO PIAUI');
insert into orgaocertificado (id, codigo, nome, sigla) values (13,'13','ADAPI – AGENCIA DE DEFESA AGROPECUARIA DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (14,'14','ADH – AGENCIA DE DESENVOLVIMENTO HABITACIONAL DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (15,'15','AGESPISA – AGUAS E ESGOTOS DO PIAUI S/A','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (16,'16','ALEPI – ASSEMBLEIA LEGISLATIVA DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (17,'17','ATI – AGENCIA DE TECNOLOGIA DA INFORMACAO DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (18,'18','CBMEPI – CORPO DE BOMBEIROS MILITAR DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (19,'19','CCOM – COORDENADORIA DE COMUNICAÇÃO SOCIAL','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (20,'20','CCPR-COORDENADORIA DO PROGRAMA DE COMBATE A POBREZA RURAL','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (22,'22','CEAPI – CENTRAL DE ABASTECIMENTO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (28,'28','CEPRO – FUNDACAO CENTRO DE PESQUISAS ECONOMICAS E SOCIAIS DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (36,'36','CGE – CONTROLADORIA GERAL DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (38,'38','SECCID – SECRETARIA DAS CIDADES','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (40,'40','CMTP-COMPANHIA METROPOLITANA DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (41,'41','CODROGAS – COORDENADORIA DE ENFRENTAMENTO AS DROGAS','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (42,'42','CDSOL – COODENADORIAA DE DESELVOLVIMENTO SOCIAL E LAZER','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (43,'43','COJUV – COORDENADORIA DA JUVENTUDE DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (44,'44','COMEPI-COORDENADORIA DO PROGRAMA DE MODERNIZACAO E QUILIFICACAO DE EMPRENDIMENTO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (46,'46','CEPMPI – COORDENACAO ESTADUAL DE POLÍTICAS PÚBLICAS PARA AS MULHERES','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (47,'47','COORDENADORIA DE FOMENTO A IRRIGACAO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (48,'48','COODENADORIA DE FOMENTO AO SANEAMENTO RURAL','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (50,'50','CPAP-COORDENADORIA DO PROGRAMA DE APOIO A PSICULTURA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (51,'51','COPEMTEC-COORDENADORIA DO PROGRAMA DE EDUCACAO POR MEIOS DE MEDIACOES TECNOLOGIA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (52,'52','CPTEI-COORDENADORIA DO PROGRAMA DE TECNOLOGIA E INOVACAO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (53,'53','AEROPORTO-COORDENADORIA DO PROGRAMA DE INFRAESTRUTURA AEROPORTUARIA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (54,'54','CRH-COORDENADORIA DO PROGRAMA DE GESTAO DE RECURSOS HIDRICOS','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (55,'55','CVCI-COORDENADORIA DO POGRAMA MAIS VIDACOM CIDADANIA PARA O IDOSO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (56,'56','DER – DEPARTAMENTO DE ESTRADAS DE RODAGEM DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (57,'57','DETRAN – DEPARTAMENTO ESTADUAL DE TRANSITO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (58,'58','DIRETORIA REGIONAL DE SAÚDE DE PARNAÍBA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (59,'59','DPG – DEFENSORIA PUBLICA DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (61,'61','EMATER – INSTITUTO DE ASSISTENCIA TECNICA E EXTENSAO RURAL DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (62,'62','EMGERPI – EMPRESA DE GESTAO DE RECURSOS DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (64,'64','ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (65,'65','FAPEPI - FUNDAÇAO DE AMPARO A PESQUISA DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (66,'66','FUNDAC – FUNDACAO CULTURAL DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (67,'67','FUNDAÇÃO ANTARES – FUNDAÇÃO RADIO E TELEVISÃO EDUCATIVA DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (68,'68','FUNDESPI – FUNDAÇÃO DO DESENVOLVIMENTO DO ESPORTE DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (69,'69','FUNDO DE MODERNIZACAO E APARELHAMENTO DA DEFENSORIA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (70,'70','DPG – DEFENSORIA PUBLICA DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (71,'71','FUNDO INTEGRADO DE BENS DIREITOS E ATIVOS FI BDA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (73,'73','FUNSAUDE - FUNDO DE SAUDE DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (74,'74','GAMIL – GABINETE MILITAR','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (76,'76','GOVERNO DO ESTADO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (77,'77','HAA – HOSPITAL AREOLINO DE ABREU','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (78,'78','HCC – HOSPITAL COLONIA DO CARPINA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (82,'82','HEGCB – HOSPITAL ESTADUAL GERSON CASTELO BRANCO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (83,'83','HEMOPI – CENTRO DE HEMATOLOGIA E HEMOTERAPIA DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (84,'84','HETNB – HOSPITAL ESTADUAL TERESINHA NUNES DE BARROS','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (86,'86','HILP – HOSPITAL INFANTIL LUCIDIO PORTELA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (90,'90','IAPEP – INSTITUTO DE ASSISTENCIA E PREVIDENCIA DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (91,'91','IASP – INSTITUTO DE ASSIST E PREVID DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (92,'92','IDEPI – INSTITUTO DE DESENVOLVIMENTO DO PIAUÍ IDEPI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (93,'93','IDTNP – INSTITUTO DE DOENCAS TROPICAIS NATAN PORTELA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (94,'94','IMEPI – INSTITUTO DE METROLOGIA DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (95,'95','IAEPI – INSTITUTO DE AGUAS E ESGOTOS DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (96,'96','INTERPI - INSTITUTO DE TERRAS DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (98,'98','JUCEPI – JUNTA COMERCIAL DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (99,'99','PIAUI GOVERNO DO ESTADO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (100,'100','LACEN – LABORATORIO CENTRAL DE SAUDE PUBLICA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (101,'101','MDER – MATERNIDADE DONA EVANGELINA ROSA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (102,'102','MPPI – PROCURADORIA GERAL DE JUSTICA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (104,'104','PGE – PROCURADORIA GERAL DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (105,'105','PMPI – POLICIA MILITAR DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (107,'107','SASC – SECRETARIA DE ASSISTENCIA SOCIAL E CIDADANIA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (108,'108','SDR – SECRETARIA DE DESENVOLVIMENTO RURAL','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (109,'109','SEAD – SECRETARIA DE ESTADO DA ADMINISTRACAO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (110,'110','SECULT – SECRETARIA DA CULTURA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (111,'111','DEFESA CIVIL – SECRETARIA DE ESTADO DA DEFESA CIVIL','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (112,'112','SEDET – SECRETARIA DE DESENVOLVIMENTO ECONOMICO E TECNOLOGICO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (113,'113','SEDUC – SECRETARIA DE ESTADO DA EDUCAÇÃO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (114,'114','SEFAZ – SECRETARIA DE ESTADO DA FAZENDA DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (115,'115','SEGOV – SECRETARIA DE GOVERNO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (116,'116','SEID – SECRETARIA ESTADUAL PARA INCLUSAO DA PESSOA COM DEFICIENCIA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (117,'117','SEINFRA – SECRETARIA DA INFRAESTRUTURA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (118,'118','SEJU – SECRETARIA DA JUSTICA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (119,'119','SEMAR – SECRETARIA DO MEIO AMBIENTE E RECURSOS HIDRICOS','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (120,'120','SEMINPER – SECRETARIA DE MINERACAO PETROLE E ENERGIAS RENOVAVEIS','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (121,'121','SEPLAN – SECRETARIA DO PLANEJAMENTO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (122,'122','SESAPI – SECRETARIA DE ESTADO DA SAUDE DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (123,'123','SETRANS – SECRETARIA ESTADUAL DOS TRANSPORTES','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (124,'124','SETRE – SECRETARIA DO TRABALHO E EMPREENDEDORISMO','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (125,'125','SETUR – SECRETARIA DO TURISMO DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (126,'126','SSP – SECRETARIA DE SEGURANCA PUBLICA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (128,'128','SURPI-SUPERINTENDENCIA DE REPRESENTAÇAODO PIAUI EM BRASILIA','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (129,'129','TCE – TRIBUNAL DE CONTAS DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (136,'136','UESPI – FUNDACAO UNIVERSIDADE ESTADUAL DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (171,'171','VG – VICE-GOVERNADORIA DO ESTADO DO PIAUI','sem');
insert into orgaocertificado (id, codigo, nome, sigla) values (173,'173','PC-POLICIA CIVIL DO ESTADO DO PIAUI','sem');
